src/hugr.rs
I reproduced @cqc-alec 's circuit (minus a Hadamard gate) and here's what it looks like now:
=> [fix] Display each port's type, rather than whole signature in dot

.github/workflows/drop-cache.yml
Following
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
Each branch consumes about 1.5GB of the 10GB cache limit, so dropping it on merge should improve hit rates.
=> Drop cache for closed PRs

Cargo.toml, src/hugr.rs, src/hugr/multiportgraph.rs
This PR introduces a layer on top of a portgraph that allows multiple edges to be connected to the same port.
Internally, it automatically creates and deletes "copy nodes" associated with the multi-connected ports (_multiports_).
To be able to distinguish between different connections to the same port, there's a new `SubPortIndex` that contains the main PortIndex plus the offset of the port in the copy node (or 0 if there is no copy node).
Most of the interface of a `portgraph` has been carried over, replacing `PortIndex` with `SubPortIndex` where appropriate, or adding specialized variations (e.g. `unlink_port` vs `unlink_subports`).
This PR is the first split change from #100. It does not contain any iterator definitions.
=> Base definition for the MultiPortGraph

src/algorithm/nest_cfgs.rs, src/builder.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/circuit_builder.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module_builder.rs, src/builder/tail_loop.rs, src/hugr/hugrmut.rs, src/hugr/validate.rs, src/hugr/view.rs, src/ops/dataflow.rs
to allow for building non-module root HUGR
Closes #82
=> Allow any op as root

src/hugr/multiportgraph.rs, src/hugr/multiportgraph/iter.rs
This is a work in progress for implementing implicit copies as a thin layer an top of a portgraph.
Switching the graph in a hugr for this should be almost frictionless, except `LinkError::AlreadyConnected` should not be thrown when connecting already-connected ports.
There's just some slight API changes when compared to portgraph, and some new methods needed to manipulate the subports.
Ideally this should be upstreamed to portgraph in the future.
Implementation progress:
- Iterators:
=> MultiPortGraph layer for implicit copies

specification/hugr.md, src/hugr.rs, src/lib.rs, src/replacement.rs, src/replacement/simple_replace.rs
This PR includes and implements #85 .
Since we don't yet have DFG-rooted HUGRs we use a workaround where the replacement graph is specified as a HUGR with a unique DFG node. Once #112 is merged we can remove this workaround.
=> Implement `SimpleReplace`

src/builder/build_traits.rs, src/hugr/view.rs
Since we now support multiple links to the same port
=> Replace `linked_port` with `linked_ports` in HugrView

specification/hugr.md
This is intended to enact what we've discussed a couple of times about extensions, unifying some concepts. It may need more work on phrasing and some details, e.g. I haven't learnt about `serde` yet, and there's that bit about downcasting...
Also there is some uncertainty about terminology. I've been using "operation-definition" for what we at one point called "OpFactory", but I've also removed the previous term "OpDef" (along with CustomOp - I think these terms just live in the code) so it is tempting to use that. Thoughts?
I've deleted a fair bit of the old text that seemed to be talking about implementation, I'm happy to negotiate which bits of that to bring back and how.
* I removed operations outside resources, as we think these should be done by writing them as `call`s to functions …
=> Rewrite Extension section for type info

src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module_builder.rs, src/builder/tail_loop.rs, src/hugr/hugrmut.rs, src/hugr/validate.rs, src/ops/dataflow.rs, src/ops/module.rs, src/ops/validate.rs, src/replacement/simple_replace.rs, src/types.rs
Resource requirements for a dataflow node can be represented by a pair of the resources requirements of the inputs and the resource requirements of the outputs (see the very bottom of the diff).
Inside of a dataflow node, the input requirements are uniformly associated with the wires coming out of the source (Input) node, and the output requirements are associated with the sinks in the Output node
In this PR:
* Add input & output resources to signatures
* Change function interfaces to deal with signatures when possible, so that resources aren't forgotten about
* Include resource requirements in Input/Output nodes, so that their signatures can be computed
=> [refactor] Add resources to signatures

src/algorithm/nest_cfgs.rs, src/builder.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module_builder.rs, src/builder/tail_loop.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/validate.rs
This turned out significantly harder than I'd expected, I'd not realized how much parameterization over hugr/ref/hugrmut there was in the builder. But I think I got there....
* Anything returning a (new) HugrMut has to return an actual Hugr, it's the only concrete implementation of HugrMut we have.
* `Container` having both `base()` and `hugr()` methods now seems a bit strange. But one is mutable and one is not....so left as is for now (TODO's can be removed if we are happy)?
* Other things are variously parameterized over HugrMut and HugrMutRef...this was quite hard to satisfy `rustc` and I'm not sure I've got all these as consistent as I could have. The acid test will be when we have mutable views onto subregions and want to use HugrMut methods on those, but that's not in this PR!
* …
=> Make HugrMut a trait

specification/hugr.md
=> Update spec to require that I/O + Entry/Exit are first two children

src/hugr/serialize.rs
So the port counts correspond to the operation's.
We do not currently check the port counts when deserializing, but we may in the future (see #159).
=> Set valid OpTypes in the serialization tests

src/algorithm/nest_cfgs.rs, src/builder.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module_builder.rs, src/builder/tail_loop.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/ops/handle.rs, src/ops/tag.rs, src/ops/validate.rs, src/replacement/simple_replace.rs
The spec states _any_ container, however here we restrict to Dataflow containers as usage in other containers is not useful.
Builder methods are renamed for clarity (define function adds a Def from scratch now)
Closes #149
=> Allow Def in any Dataflow container

specification/hugr.md
And try to clarify a bit.
Hierarchy edges don't fit that neatly (they don't fit any of the localities), ideas welcome - do we need to write "non-hierarchy edges"? I'm hoping this here is fine...
Also add a glossary entry for "dataflow edge".
=> Rename "Inter-graph edges" to "non-local edges"

Cargo.toml, src/utils.rs
`urlencoding` is a lot more stable. Fixes #176.
=> Replace broken url_encode with urlencoding

Cargo.toml, src/algorithm/nest_cfgs.rs, src/hugr/view.rs
In preparation for new hugr abstractions.
Replaces the hand-written `PortLinks` with `context-iterators` primitives.
=> Make HugrView iterators generic

.github/workflows/ci.yml
Uses a fixed nightly toolchain to run miri.
This should get rid of the spurious [CI errors](https://github.com/CQCL-DEV/hugr/actions/runs/5343712720/jobs/9687171092) when miri is not yet available on the latest nightly.
=> Pin the miri toolchain in CI

README.md, src/lib.rs
- Clarify the package vs library name difference. Closes #67 
- Reexport `HugrView` on the crate's root.
=> doc: Crate name as README title + add reexport

Cargo.toml, src/hugr/serialize.rs
If a copy node made the op nodes non-contiguous, the edge serialization didn't translate the endpoints `Node`s.
This is a one-liner fix + a new check on the node index when deserializing + the previously-failing test.
Closes #202
=> Fix edge serialization not compacting the nodes

src/builder/build_traits.rs, src/hugr.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/validate.rs, src/ops/constant.rs, src/ops/custom.rs, src/ops/dataflow.rs, src/ops/module.rs, src/types.rs
=> s/EdgeKind::Const/EdgeKind::Static/

.github/workflows/ci.yml, .github/workflows/unsoundness.yml
Only runs on `main`. I copied the [official example](https://github.com/rust-lang/miri#running-miri-on-ci).
Adds a workflow_dispatch trigger so we can run it on other branches when needed.
=> Don't run miri for PRs

Cargo.toml, src/hugr.rs, src/hugr/region.rs, src/hugr/region/petgraph.rs, src/hugr/view.rs
Adds a `RegionView` and `FlatRegionView` hugr views that show a single region in the Hugr, either containing all the descendant nodes or just the direct children of the root.
These regions implement `petgraph`'s visit traits, exposing the internal graph. Closes #125 
- We do not implement `petgraph::visit::IntoEdgeReferences` nor the `IntoEdge*` derivates.
The weight of an edge should be an `EdgeKind`s, but petgraph requires the iterators to return an `EdgeRef : Copy` which has a method that returns an `&EdgeKind`.
Since the edge kinds are computed on the fly from the signature we have to store them somewhere temporarily, but `EdgeRef` is `Copy` so it cannot contain it.
I tried some alternatives with cached structures on the iterators, but it quickly became lifetime hell.
I'll leave that …
=> Region views of a portgraph

src/ops/constant.rs, src/ops/custom.rs
in https://github.com/CQCL-DEV/tket2proto/tree/hugr
=> `ConstValue::F64` and `OpaqueOp::new`

specification/hugr.md, src/builder/build_traits.rs, src/builder/dataflow.rs, src/builder/module_builder.rs, src/hugr/hugrmut.rs, src/hugr/validate.rs, src/ops.rs, src/ops/handle.rs, src/ops/module.rs, src/ops/tag.rs, src/ops/validate.rs, src/types/simple.rs
Def => FuncDefn
Declare => FuncDeclare (there are a couple of uses of "Declare" as a verb that I've preserved)
Alias => AliasDefn
AliasDeclare => AliasDecl
Also update spec.
=> [refactor] Rename Alias/Func Def/Decl nodes

src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/serialize.rs
Defines the canonical order as the BFS traversal of the hierarchy.
This updates the code from #210 to enforce the canonical order when serializing.
Closes #208
=> Node canonicalization method in HugrMut

src/types.rs
Adds a `df_types` method to a signature to return a slice of values without allocating.
=> feat: return a slice of types from the signature

Cargo.toml, src/builder/build_traits.rs, src/builder/dataflow.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/region.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/view.rs
This is a proposal for basic metadata support in the HUGR.
It adds a new SecondaryMap from nodes to a `OpMetadata` type, currently aliased to `serde_json::Value`.
The specification doesn't specify whether this map should be in or alongside the Hugr, but doing it like this lets us seamlessly integrate it into building, serializing, and rewriting (the serialization remains backwards-compatible).
The metadata itself is fully unstructured. We may want to enforce some minimal schema in the future, perhaps requiring a dictionary at the head so we can more easily merge different values, but that's left as future work.
Closes #235.
=> Node metadata

.github/workflows/compare-coverage, .github/workflows/coverage.yml
On this run the check took 3m38s which makes it the slowest of the CI checks ("tests (nightly, true)" took 3m0s).
I took the simplest approach which was:
* run on PR only;
* compute coverage both for PR branch and for main;
* compare only the total line coverage (ignoring function coverage and region coverage whatever that is, and ignoring individual file reports).
This means we don't need to store anything persistently, but we do need to run the coverage checks _twice_, which increases the run time.
Obviously we could refine the checks in future, e.g. to include function coverage statistics. We could also look into running on push to main and storing the result persistently, but I'm not very happy with how tket does this (by pushing a file to the magic `gh-pages` branch).
=> Add coverage check.

src/hugr/typecheck.rs, src/ops/constant.rs, src/types/simple.rs
* Wrong signature
* Add assert that the value is of the type we'll claim. Such errors should be caught by `Hugr::validate()` but are not, so this is a temporary measure/sanity check, mostly while I'm playing around with types, but until #231 is fixed
* Improve `typecheck_const` errors, and test some of the cases
* Also add a test of a "bad" constant, but this is `should_panic` for now (i.e. the assert fails)
* Also remove `SimpleType::new_unit`. If it was going to be used anywhere, `ConstValue::simple_predicate` seems the most likely place, and...it isn't. (But, if we want to keep it, I can revert the last commit but let's go for the form in 76b47232dc4cfd47ec8c9b5b2872dcec14e65c83)
Links from code to issues may not be the right way, depending on how much we are thinking about the code …
=> Cleanup ConstValue::predicate and some ConstTypeErrors

src/extensions/rotation.rs, src/resource.rs
- Adds a blanket `CustomSignatureFunction` implementation for closures, for we don't want to add a description.
- Drops the `name` and `misc` parameters, since they can be taken directly when creating the function along with the OpDef.
So we can just do:
```rust
let name = "MyOp".into();
let description = "".into();
let args = vec![];
let mut misc = HashMap::new();
let sig: Signature = todo!(); // Some complex computation
let signature = move |_args: &[TypeArg]| {
Ok((sig.input.clone(), sig.output.clone(), ResourceSet::new()))
};
OpDef::new_with_custom_sig(name, description, args, misc, signature)
```
=> Add a blanket implementation for CustomSigFn

Cargo.toml, src/hugr.rs, src/hugr/view.rs
It's the same code, but now it can be called on any view.
Updates to portgraph 0.7.1 to fix https://github.com/CQCL/portgraph/pull/91.
=> feat: Move `dot_string` to `HugrView`

src/builder/build_traits.rs, src/builder/dataflow.rs
Another chunk pulled out from a one-line comment in #252, specifically [here](https://github.com/CQCL-DEV/hugr/pull/252/files#r1258050562) - which lead to a bugfix/enhancement, in that we can can easily catch linear non-local edges at build time.
=> [refactor] Remove ValueKind, error on nonlocal linear edges in Builder

specification/hugr.md
Markdown treats
```markdown
- A
- B
```
as two lists, not one.
=> Compact lists and remove redundant newlines

src/ops/custom.rs
So that external users can use their custom operations.
=> Add an ExternalOp::args getter

specification/hugr.md, src/builder.rs, src/builder/build_traits.rs, src/builder/dataflow.rs, src/builder/module_builder.rs, src/hugr/region.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/ops/constant.rs, src/ops/handle.rs, src/ops/leaf.rs, src/ops/module.rs, src/types.rs, src/types/simple.rs, src/types/simple/serialize.rs
First step in refactoring the type hierarchy! (I'm heading towards the creation of a Hashable subset of ClassicType but it's a long way to go)
There seemed some confusion in the type hierarchy here. Partly this stems from that TypeRow always contains SimpleType, so statically Container<T> can have tuples of SimpleType (regardless of T). However, if we imagine that TypeRow might be parameterized by the type contained within it (hint hint - that PR is upcoming, but I found there was a lot to sort out first) then the old LinearType should not have the option of `Container<LinearType>` but `Container<SimpleType>` as that's the only way we'd be able to have "mixed" types like Tuple(Qubit,Int).
After sorting out Linear/Simple confusion it didn't seem that LinearType really meant anything: …
=> Remove LinearType; ClassicTypes are the only subtype of SimpleTypes

Cargo.toml, src/builder/build_traits.rs, src/builder/module.rs, src/hugr/typecheck.rs, src/hugr/validate.rs, src/ops/constant.rs, src/ops/handle.rs, src/ops/leaf.rs, src/ops/module.rs, src/types.rs, src/types/simple.rs, src/types/simple/serialize.rs
[Note there are a few small/preliminary commits here before the bulk starts.]
This was surprisingly painless...
* Add a new TypeTag enum, replacing `is_classical()` bool with a ternary; `is_classical` and `is_hashable` move here.
* Keep `purely_classical` and `purely_hashable` on TypeRow - it's silly to fall back to having to handle TypeTag::Any when you have a row of types already known to be Classic.
* PrimType: add a `.tag()` method. However, keep SerializableType with its `const CLASS` as for well-formed instances we do not need to check the runtime value.
* There is some fun with `new_sum` and `new_tuple` requiring adding these methods to ClassicType *as well as* SimpleType
Unresolved issues:
* What about type variables. These are not really sorted before, specifically that a type …
=> Add HashableType as subset of ClassicType

src/builder.rs, src/hugr.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/types/simple.rs
- Expose Hugr and some other structs as opaque python objects.
- Does not implement any pymethods. We'll leave that for later.
- Implement `Into<PyErr>` for some custom errors
=> Add so minimal pyo3 impls

src/builder/cfg.rs, src/hugr/rewrite/outline_cfg.rs
This requires copying the created nodes, but there are, like, 6 of them, and means we can drop CfgBuilder::from_existing, easing the path to #282.
Also merge identical-signature impl Blocks and add `BlockBuilder::finish_hugr_with_outputs`, but no other Builder refactoring was required :)
=> OutlineCfg use insert_hugr; remove CfgBuilder::from_existing

src/extensions/rotation.rs, src/resource.rs, src/types/custom.rs
Fly-by refactor out arg checking for future reuse
=> Correct field names for op/type args/params

specification/hugr.md
matches implementation in #308
=> spec rename OpDef args -> params

specification/hugr.md
I'm assuming this wasn't done on purpose?
=> [fix] Spec formatting

devenv.nix
Solution found via this issue: 
https://github.com/cachix/devenv/issues/617
=> explicitly set macos frameworks in devenv.nix

src/extensions/logic.rs, src/hugr/typecheck.rs, src/types/type_param.rs
* Add an option to parameterize by a hashable type - this should have gone in #283 really
* And, replace TypeParam::Int, TypeParam::String, etc., by "a value of any (given) Hashable Type"
The latter is a bit more complex (e.g. we now have to specify widths of ints). And, Hashable types include sums/tuples/lists/etc. - however, TypeArg (rather like ConstValue) doesn't let one provide values of most of these yet.
I've commoned up checking of int widths with `typecheck_const`, I think the next step might be to common up the representation of *values* of hashable type, extending both to include more containers. So yeah, either I should add tests, or go straight to that. I'm gonna see how hard a full-blown "ContainerValue" is...
=> Allow any Hashable type as a TypeParam

src/hugr/typecheck.rs, src/ops/constant.rs
AFAICT our manual implementation does exactly what the derive one would, except for one case - ConstValue::Opaque. But with a bit of "wizardry" (?!) we can get provide that ourselves and get Rust to derive the rest.
The extra level of tupling inside `ConstValue::Opaque` was because without that the `derive(serde::Serialize)` on ConstValue produced a complex error about moving out of a Box<dyn CustomConst>. A `struct OpaqueValue(CustomType, Box<dyn CustomConst>)` is one way to do that but just the tuple works too.
=> [Refactor] Derive PartialEq for ConstValue

devenv.nix
otherwise clippy has a different version and pre-commit fails
=> keep rust on nixpkgs version in devenv

src/builder.rs, src/builder/build_traits.rs, src/hugr/validate.rs, src/ops/constant.rs
`typecheck_const` is currently called from `validate_edge` - that is, once per outgoing edge. This is (a) repetitive, (b) doesn't complain about malformed constants with no edges, (c) confusing and hard to find ;-).
Instead, make Const constructible only via a new `new()` method (returning a Result), and validate only there.
=> Check Const's are well-formed using a constructor

src/algorithm/nest_cfgs.rs, src/builder.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/tail_loop.rs, src/hugr.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/validate.rs, src/ops/constant.rs, src/ops/constant/typecheck.rs, src/ops/handle.rs, src/types/type_param.rs
Partially addresses #318 , still need to add `CustomConst` checking
* new error variant where value doesn't check
* new constructor for Const
* specify const type when building
=> Make ConstValue checkable not synethesisable

src/extensions/rotation.rs, src/ops/constant/typecheck.rs, src/resource.rs, src/types/custom.rs
* Hopefully this will fix problems you were seeing @ss2165
=> CustomType's are Simple not necessarily Classic, and report their TypeTag

src/macros.rs, src/types.rs, src/types/simple.rs, src/types/simple/serialize.rs, src/types/type_row.rs
Increase modularity - TypeRow is just a row of *things* really, it doesn't require them to be "types" so there's no need to require elements to support `.tag()` or even to limit it to sealed things.
The additional trait TypeRowElem has the advantage that we no longer need to implement `.tag()` for `SerSimpleType`.
This is pulled out of #324 but can stand alone, and shouldn't conflict with any of the other stuff, so can go in first.
Update: I added a "blanket" implementation of TypeRowElem in commit 66f25691. I'm not certain about this, but don't really see why not.
---> Should we rename "TypeRow" (and others) to just Row? It is, basically, just a list-like data structure...
=> Move TypeRow into own file, introduce TypeRowElem

src/builder.rs, src/extensions/rotation.rs, src/hugr/validate.rs, src/lib.rs, src/ops/constant.rs, src/ops/constant/typecheck.rs, src/values.rs
* No additional sharing of code with TypeParam/TypeArg yet, but the idea is that we will be able to
* Still have both `serde_yaml::Value` and `Box<dyn CustomConst>` in different places
* `typecheck.rs` remains, as the code that's used by both the new and the old, not-yet-updated (TypeParam/TypeArg) code. When we update the latter, the classes/routines in `typecheck.rs` should only have one caller (in values.rs) and then they can be moved into values.rs. [So, this is kinda in the wrong place now, if we want to move it.]
=> Add HashableValue as part of ConstValue, and ContainerValue

src/extensions/rotation.rs, src/ops/constant.rs, src/values.rs
Tests in progress but see if this agrees with what you were thinking.
* Remove ContainerValue::Opaque (which previously contained YAML)
* Do not move ConstValue::Opaque into ContainerValue (rather, remove the TODO saying that). ContainerValue will be shared with TypeArg, so keep `dyn CustomConst` well away from that.
=> [Refactor] struct CustomSerialized contains Yaml (+ CustomType)

src/ops/constant.rs, src/values.rs
* HashableValue's are Eq, that's the whole point of them ;-)
* ContainerValue's can also be Eq if they contain things that are
* CustomSerialized probably should not be
* But, provide missing impl of `equal_const`
=> A few more Eq fixes

src/builder/conditional.rs
This should cover the code which checks for existing cases and maintains order (Line 124 of this file)
=> [tests] Swap the order of case building in conditional test

devenv.nix
otherwise the pre-commit uses 1.70
=> force pre commit to use same rust

src/resource.rs, src/types/type_param.rs
The code was in there, but seemingly in the wrong place. Not sure if my comment on `TypeArgError::WrongNumber` had mislead so I've corrected that ;)
=> [bugfix] Check #TypeArgs == #TypeParams for TypeDefs as well as OpDefs

specification/hugr.md
This is defined in the Arithmetic Resource.
=> Remove `float64` from core

src/builder.rs, src/builder/circuit.rs, src/hugr/validate.rs, src/ops/constant.rs, src/ops/leaf.rs, src/resource/type_def.rs, src/types/custom.rs, src/types/simple.rs, src/types/simple/serialize.rs
Spec was updated already in #358. I took out `LeafOp::Rzf64` too (the only LeafOp that actually used it), also `SerSimpleType::F`. Added a couple of other ClassicType instances for use in tests because we need some (specifically, `ClassicType::Graph`s are a pain to construct, cannot be `const` as they contain Boxes, and do not yet have ConstValue instances)
=> Remove f64

src/types/simple.rs, src/types/simple/serialize.rs, src/types/type_row.rs
* Also inlining singly-used methods `box_convert` and `box_convert_try`
* And switch TypeRowElem from a blanket impl to "elective" - we elect to allow only TypeRows of SimpleType/ClassicType/HashableType
=> SerSimpleType: use Vec not TypeRow

src/types/basic.rs
Means in public code it is clear that upcasting is an operation only valid for types
leaves are more free, and hopefully mostly used in pattern matching and internal code.
=> only implement upcast for Type

specification/hugr.md, src/builder.rs, src/builder/tail_loop.rs, src/extensions/arithmetic/int_types.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/macros.rs, src/ops/constant.rs, src/ops/custom.rs, src/ops/leaf.rs, src/ops/validate.rs, src/types/simple.rs, src/types/simple/serialize.rs, src/values.rs
=> Use a 64-bit `USize` as the sole integer type in the core

src/hugr/validate.rs
Add a validation check that dataflow graph's input and output nodes have the same resource requirements as the incoming/outgoing wires of the parent.
=> [new] Validate IO nodes have resources matching parent signatures

src/algorithm/nest_cfgs.rs, src/hugr/hierarchical_views.rs, src/hugr/hierarchical_views/petgraph.rs, src/hugr/validate.rs
Add's a `Root: NodeHandle` parameter to the views to restrict the hugr type. The root tag is dynamically checked at construction time.
The next step would be to tag the `Hugr`s too, and add dynamic casting between handle types.
=> Tag the regions with their root node handle

src/types/custom.rs
`CustomType::new_simple` was removed in #315 but I don't see why we can't. This version allows specifying type-arguments too.
There are uses of `CLASSIC_T` (all in tests) in `src/ops/constant.rs`, `src/resource/type_def.rs`, `src/types/simple/serialize.rs` and a mention in `src/types/simple.rs`. We *could* now create local versions of `CLASSIC_T` for each of those (whereas before there was only one place that we could construct such). But for test code I'm not feeling worried. If you think I should be less lazy then please shout and I will do so ;-)
=> Reinstate CustomType::new_simple

src/hugr.rs, src/hugr/validate.rs, src/resource.rs, src/resource/validate.rs
This PR adds a new `resources::validate` module, and moves the different resource logic bits from the Hugr validation there.
This is a tidying up change before adding new things for #362.
The only behaviour change is that `gather_resources` is ran on initialization of the validation context, and the check for whether a node has concrete input resources is done during the validation, when calling `query_resources`.
Drive-by: Some missing docs for NodeType
=> Move resource validation routines to new module

src/builder/circuit.rs, src/ops/custom.rs, src/ops/leaf.rs
Low-hanging fruit to reduce the OpType footprint.
Reduces LeafOp footprint from 216b to 88b, and OpType from 216b to 152b
=> Put LeafOp::CustomOp inside a box.

src/hugr/views.rs, src/hugr/views/hierarchy.rs
I'll say this closes #380.
We could go further and add a type parameter in `Hugr<T: NodeHandle>`, but that would probably be annoying to use and it'd break the pyo3 machinery.
Instead, most things should be interfacing via `HugrView`. #284 / #293 will move the builder references to views instead, so we will be able to statically check the root type.
=> Add a root NodeHandle type param to HugrView

src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/ops/custom.rs
First step of #284 
Moves the mutating methods to a sealed trait, and makes `HugrMut` `pub`.
It also relates it to `HugrView` via a borrowing method.
=> `s/HugrMut/HugrInternalsMut/` as a sealed trait, and expose a minimal HugrMut

specification/hugr.md
*Not* done function polymorphism, and have not added array (or indeed prelude) to standard library. @ss2165 were you in the process of doing that?
=> Update Type System part of spec wrt "types redux"

.github/workflows/ci.yml
#ci-shedding-friday
Currently we are running all the CI jobs when checking in the merge queue, even though only `checks` and `stable tests` are checked.
This skips all the unneded checks.
It also enables MSRV tests as per the TODO.
=> Avoid running unnecessary checks in the merge queue

src/builder.rs, src/builder/tail_loop.rs, src/extensions/arithmetic/conversions.rs, src/extensions/arithmetic/int_ops.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/hugr/views/hierarchy.rs, src/ops/constant.rs, src/ops/leaf.rs, src/ops/validate.rs, src/resource.rs, src/resource/prelude.rs, src/types.rs, src/types/custom.rs, src/types/serialize.rs
Isolate PRELUDE "stringy" codes to the `prelude` module - can be improved with statics etc. in future.
=> Const usize, qubit, and ERROR type definitions in the prelude

src/builder/tail_loop.rs, src/extensions/logic.rs, src/extensions/rotation.rs, src/hugr/validate.rs, src/ops/constant.rs, src/resource.rs, src/resource/prelude.rs, src/values.rs
* Addition and retrieval of typed ops::Const to resources
* simplify constant definitions with `KnownConstType`
* move `ConstUsize` to prelude
=> Add static values to resources

src/std_extensions.rs, src/std_extensions/collections.rs
map is left for future (tierkreis)
=> add Collections extension with list type and operations

src/builder/circuit.rs, src/builder/dataflow.rs, src/extension.rs, src/extension/op_def.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/hugr/views/hierarchy.rs, src/ops/custom.rs, src/ops/leaf.rs, src/std_extensions.rs, src/std_extensions/logic.rs, src/std_extensions/quantum.rs
Closes #365
remove quantum ops that are not used in tests
more can be added later as required
Early commits also remove XOR and replace use with logic extension
Required some fixups to enable use of `ExtensionOp`
=> Quantum extension

src/algorithm/half_node.rs, src/algorithm/nest_cfgs.rs, src/builder/build_traits.rs, src/hugr/rewrite/outline_cfg.rs, src/ops/custom.rs, src/ops/validate.rs, src/std_extensions/collections.rs
Preventively fixes CI errors before rust 1.72 is released, and rustfmt starts having opinions on let-else formatting.
https://blog.rust-lang.org/2023/07/01/rustfmt-supports-let-else-statements.html
=> chore: Format let-else with nightly rustfmt

src/types/type_param.rs
=> Add Type{Param,Arg}::Extensions

src/builder/dataflow.rs, src/hugr.rs, src/hugr/validate.rs, src/hugr/views.rs, src/ops/tag.rs
Fix the logic of `get_io` and update the wording of the `is_superset` function.
Due to this bug, some tests weren't having their extension requirements validated, so update those too
=> [fix] Fix the logic of get_io

specification/hugr.md, src/extension/prelude.rs, src/ops/constant.rs, src/std_extensions/arithmetic/conversions.rs, src/std_extensions/arithmetic/int_ops.rs, src/std_extensions/arithmetic/int_types.rs, src/std_extensions/arithmetic/mod.rs, src/std_extensions/collections.rs, src/std_extensions/logic.rs, src/types/type_param.rs
Closes #437 
BREAKING CHANGE: `USize` type param and type arg changed to `BoundedNat` with optional maximum. For previous behaviour use `TypeParam::max_nat()`
=> feat: Change `TypeParam::USize` to `TypeParam::BoundedNat` and use in int extensions

src/extension/prelude.rs, src/ops/custom.rs, src/std_extensions/arithmetic/float_types.rs, src/std_extensions/quantum.rs
* make prelude types pub
* getter for ExtensionOp::def
* Deref ConstF64 to float (should this be replicated for other CustomConst values?)
* Add rzf64 op to quantum resource. (This is likely to be a recurring problem though - perhaps the quantum resource should move to tket2 and become a test dependency here?)
=> feat: TKET2 compatibility requirements 

src/builder/dataflow.rs, src/extension/infer.rs, src/extension/validate.rs, src/hugr.rs, src/hugr/validate.rs
Fixes #454.
Return from extension inference an extra solution set, which instantiates all of the inference variables to the empty set, meaning metavariables which depend on them can be solved
=> feat: Extension validation can take a closure of solutions

devenv.lock
including update to rust stable 1.72
=> chore: devenv update

devenv.lock
on my mac aarch64 system at least I was getting link errors due to some other update...
I believe something to do with mktemp
=> chore: undo nixpkgs update

src/hugr/views.rs, src/hugr/views/hierarchy.rs, src/hugr/views/tests.rs
Uses portgraph `get_connections`
=> feat: add `HugrView::node_connections` to get all links between nodes

src/builder/build_traits.rs, src/hugr/validate.rs, src/std_extensions/logic.rs
Fixes #455 .
Fixes #447 .
Fixes #435 .
=> Check for acyclicity; remove boundedness requirement

src/builder/build_traits.rs, src/builder/conditional.rs, src/builder/tail_loop.rs, src/extension/infer.rs, src/hugr.rs, src/ops/controlflow.rs
N.B. this does nothing with `input_extensions`
`Conditional` ops can now have a set of extension reqs which are added by their child `Case` ops. It's expected that the difference is the same set for the `Conditional` and all of its children
=> refactor: Add extension info to `Conditional` and `Case`

src/hugr.rs, src/hugr/rewrite.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs
Closes #471
BREAKING CHANGE: implementers of `Rewrite` must define `ApplyResult`.
=> feat: add `ApplyResult` associated type to `Rewrite`

src/hugr/rewrite.rs, src/hugr/rewrite/insert_identity.rs, src/hugr/rewrite/simple_replace.rs
Returns inserted identity node.
Closes #470
=> feat: Implement rewrite `IdentityInsertion`

src/hugr/rewrite/insert_identity.rs
means the unwrap is always safe in a valid hugr
=> fix: check kind before unwrap in insert_identity

src/extension/infer.rs
Variables are _allowed_ to be unsolved in an extension inference solution, but it's okay if they _are_ solved.
=> fix: Allow for variables to get solved in inference

src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module.rs, src/hugr.rs, src/hugr/validate.rs
This does NOT provide a full solution to #424 (even just for DFGs) yet, but is a first step towards doing so.
- In inference tests, when we want concrete resources we need to avoid using builder methods.
- We should do inference on every kind of graph (instead of assuming some kinds will be closed).
- Default _some_ DFG builder methods to instantiating nodes with open resources (but not enough)
=> feat: Default DFG builders to open extension sets

src/builder/build_traits.rs, src/extension.rs, src/extension/prelude.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/insert_identity.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/validate.rs
=> perf: use lazy static definittion for prelude registry

src/hugr.rs, src/ops.rs
Adds a couple of helper methods that'd be useful downstream.
- `OpType::is_container`
- `CircuitUnit::is_linear` and `is_wire`
=> feat: Some helper methods

src/extension/infer.rs, src/extension/validate.rs, src/hugr.rs, src/hugr/validate.rs
Only input extensions need to be inferred. From the values of the input extensions, the outputs can always be calculated
=> refactor: `ExtensionSolution` only consists of input extensions

src/hugr/views/sibling.rs
Exposing a HUGR-specific convex checker is required to be able to construct it from outside the hugr crate.
=> feat: Add ConvexChecker

src/builder.rs, src/extension/infer.rs, src/hugr.rs, src/hugr/serialize.rs, src/hugr/validate.rs
And add a helper method to reduce size of those tests
=> refactor: Remove builder from more DFG tests

src/builder.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/tail_loop.rs
Another step towards #424 (but not all the way there yet)
=> feat: Default more builder methods to open extension sets

src/hugr.rs
I need something like this to be able to serialize pattern matcher in TKET2 (more specifically: to serialize predicates for matching). I'm not sure this is the right approach or you'd rather I expose a different serialization API in HUGR for this purpose.
=> feat: Port is serializable

src/extension/prelude.rs, src/extension/type_def.rs, src/hugr/validate.rs, src/ops/constant.rs, src/ops/custom.rs, src/std_extensions/arithmetic/int_types.rs, src/std_extensions/arithmetic/mod.rs, src/std_extensions/collections.rs, src/std_extensions/logic.rs, src/types/check.rs, src/types/type_param.rs, src/values.rs
Adds a serde tag to the `Value`, `PrimValue`, and `TypeArg` enums.
BREAKING CHANGE: Turn all variants of the `Value`, `PrimValue`, and `TypeArg` enums into struct variants
=> fix!: Serialise `Value`, `PrimValue`, and `TypeArg` with internal tags

specification/hugr.md
Among others, uniformly refer to graph edges as edges rather than wires.
Note that SimpleType and ClassicalType have been mostly removed from the spec, my mentions here should be checked.
=> [doc] Tidy hugr specification

src/values.rs
Enables internal tagging for `typetag::serde` serialisation of `CustomConst`
=> fix: Serialise custom constants with internal tag

specification/hugr.md, src/std_extensions/arithmetic/int_types.rs
This is required for serialisation since msgpack doesn't support `i128` and `u128`: https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family
=> fix!: Reduce max int width in arithmetic extension to 64

src/std_extensions/arithmetic/float_types.rs
This simplifies serialisation with pydantic
=> refactor!: Use named struct for float constants

src/builder/build_traits.rs, src/builder/dataflow.rs, src/hugr.rs, src/hugr/serialize.rs, src/ops/custom.rs
This might be the most extreme refactor/rename/etc. that answers [your comment](https://github.com/CQCL-DEV/hugr/pull/510#pullrequestreview-1617148177) - but, well, is there a reason *not* to do this? :)
=> refactor: allow NodeType::new to take any Into<Option<ExtensionSet>>

src/hugr/validate.rs, src/ops.rs, src/ops/validate.rs, src/types/type_param.rs
The TypeArgs might contain malformed things like "the type List<5>" - we can only check that they make sense (i.e. that `5` is valid as an argument for List) *given the ExtensionRegistry*, and nowhere outside validation has the ExtensionRegistry, so we need to do this here.
Also rename `validate_children` (in ValidateOp) to `validate_op_children)`, and `validate_operation` to `validate_children`.
=> feat: Validate TypeArgs to ExtensionOp

src/ops/custom.rs
This turns out to be pretty trivial, as ExtensionRegistry looks exactly the same as HashMap as far as this code is concerned. Most of the effort here is in fixing up imports and doclinks.
This addresses the first (easy) part of #508 but the second remains as an issue/question for discussion, not attempting to resolve that here.
=> [refactor] resolve_extension_ops: take an ExtensionRegistry

src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/views/sibling_subgraph.rs
Given `apply_rewrite` just does a bounce dispatch to `Rewrite::apply`, rather than any actual work, this seems the right place to put it! (The alternative might be to drop `apply_rewrite` altogether but I think it's kinda nice and aids discovery)
=> Refactor: move apply_rewrite from Hugr to HugrMut

src/hugr/rewrite/simple_replace.rs, src/hugr/views/sibling_subgraph.rs
I have added a TODO on line 234 in `sibling_subgraph.rs`, I suspect there is a bug here that I will look into now.
EDIT: I've opened #518 but I won't have time to fix it until next sprint. This can be merged in independently of that bug.
=> refactor: use SiblingSubgraph in SimpleReplacement

src/builder/build_traits.rs
`define_function` is passed a `NodeType` which contains information about input extensions. It uses this to inform the input extensions of I/O nodes, but wasn't using it for the parent node until now.
=> fix: Use given input extensions in `define_function`

src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs
* Avoid calling validate on the subgraph in outline cfg while it isn't valid (because it has no entry node yet)
* Loosen constraints on tests for rewrites such that we're happy if they pass validation after their extensions are inferred
=> fix: Lessen requirements for hugrs in outline_cfg

src/builder/build_traits.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs
...bringing these in line with the other methods. Yes, this involves a `Result<&mut, ...>` but that works ok!
Also inline `HugrMutInternals::add_node` and `add_op`, these are only used once and it's fairly trivial (but against, restores uniformity)
=> HugrMut: validate nodes for set_metadata/get_metadata_mut, too

src/algorithm/nest_cfgs.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/tail_loop.rs, src/extension/infer.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/insert_identity.rs, src/hugr/rewrite/outline_cfg.rs, src/ops/constant.rs
When using builder methods to put `Const` nodes on the graph, users must pass an extra "provenance" argument which specifies which extension the type of the constant value is coming from. The argument is an `Option`, where `None` means that the constant is of a built-in type (like our true and false predicates).
The `Const` nodes will be added to the graph with `input_extensions` which are either the empty set or the singleton set of the const value's provenance. Constant loading methods in the builder will make the `LoadConst` node's `input_extensions` match those of the constant it's connected too.
This also adds a constraint to extension inference that extension requirements are the same on both ends of `Static` and `ControlFlow` edges.
Resolves #525
=> feat: Const nodes are built with some extension requirements

src/builder/build_traits.rs, src/builder/cfg.rs, src/hugr/validate.rs, src/ops/controlflow.rs
=> refactor: CFG takes a FunctionType

src/algorithm/nest_cfgs.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/validate.rs, src/hugr/views.rs, src/hugr/views/descendants.rs, src/hugr/views/sibling.rs, src/hugr/views/sibling_subgraph.rs, src/ops.rs
* Move `valid_node` and `valid_non_root` from `HugrMutInternals` into HugrView
* HugrView provides default implementations of `get_parent`, `get_nodetype`, `get_optype` and `get_metadata` that perform node-validity checks; remove the other implementations.
* Add DEFAULT_NODETYPE + DEFAULT_OPTYPE constants
*  Change HierarchyView::new->try_new, add explicit checks that root node is valid in the base view.
* Remove manual implementations of Clone for SiblingGraph + DescendantsGraph, just derive
* Remove the `Base` parameter to SiblingGraph/DescendantsGraph - instead parameterize only constructor (via `: impl`) and cache the base's `.base_hugr()` rather than the base.
=> HugrView: validate nodes, and remove Base

src/builder/build_traits.rs, src/builder/cfg.rs, src/hugr/rewrite/outline_cfg.rs
Mostly by updating the builder to allow specifying ExtensionSets in places not previously possible: cfg_builder(), BlockBuilder::new, and BlockBuilder::create.
I could go further: there is `fn block_builder` (and `fn simple_block_builder` and others), which frustratingly take `FunctionType`s (that I cannot update to Signature because Sig requires an ExtensionSet not an Option thereof, so extra argument again)....
I guess requiring to specify `None` as extra param in the builder, may be an OK price to keep the current behaviour of "run inference later"??
The above then avoids needing to `infer_and_validate` in OutlineCfg tests after the rewrite, just `validate` works. It'd be good to keep the other Inline/Outline rewrites and InsertIdentity like this too, but it's probably not a desirable …
=> Avoid need to rerun extension inference after outline-cfg rewrite

src/builder/build_traits.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/outline_cfg.rs
Also corresponding builder methods. `insert_hugr_internal` already returns this, so just wrap in a new `struct InsertionResult` translating the NodeIndex's into Nodes.
=> feat: insert_hugr/insert_view return node map

src/extension.rs, src/extension/op_def.rs, src/ops/custom.rs, src/std_extensions/collections.rs, src/std_extensions/logic.rs, src/std_extensions/quantum.rs
Without this, impl's can't necessarily construct instances of custom types like List - we rely on implementations to have the definitions themselves already, by some backdoor. (And for implementations to store a reference the ExtensionRegistry, leads to cyclic data, as they are going to be part of it!)
=> Pass &ExtensionRegistry to compute_signature (etc.)

src/extension/infer.rs
The `Plus` constraint has up till now been too strict in extension unification. So far we have been deriving things like the following:
```
a := Plus("C", b)
a := {"A", "B", "C"}
implies
b := {"A", "B"}
```
(as in `minus_test`, which this PR removes)
However, plus should be meant as the union of the the singleton set that it specifies with the extension set of another metavariable. Hence in the above example the solution for `b` could be either `{"A", "B"}` or `{"A", "B", "C"}`.
This means that if we have chains of circuit operations which all add the "quantum" resource, they can all be represented as `Plus` constraints
=> fix: Make unification logic less strict

specification/hugr.md
=> docs: add operation constraint to quantum extension

src/hugr/rewrite/simple_replace.rs
The rewrite was incorrectly using the old node id when updating the metadata in the target hugr.
=> fix: Simple replace incorrectly copying metadata

src/extension/infer.rs
Nowadays, DFGBuilder creates parent and child I/O nodes all with open extensions. Since this development, this test has been too strict since, in the absence of any other constraints, it can resolve all extension sets on the graph to `{A}`. Improvements to inference in the near future to address #497 will cause it to fail
=> tests: Update inference test to not use DFG builder

src/builder/build_traits.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/insert_identity.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/ops.rs, src/types/signature.rs, src/types/type_row.rs
Add a `PortIndex` trait implemented by both `Port` and `usize`, to use in all the methods that expect an undirected port offset (instead of asking for an `usize`).
=> feat: PortIndex trait for undirected port parameters

src/builder/build_traits.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/views/sibling_subgraph.rs
With this we can efficiently extract subgraphs from a HUGR, and insert other HUGR's subgraphs.
=> feat: Insert/extract subgraphs from a HugrView

src/hugr/rewrite/outline_cfg.rs
This seems like a good use of the facility for a rewrite to return a rewrite-specific result, and preliminary to other upcoming PRs (specifically #247)
The new CFG node is non-trivial to find given its parent (basic block) as that has several children: not only Input and Output but also constant nodes to build the predicate.
=> OutlineCfg rewrite returns new BB and CFG nodes

src/extension/infer.rs
When comparing for equality of metavars, we need to consider that they might have been merged to form a new meta, so `UnificationContext::resolve` must be used. In this case, the variable (LHS) is updated to the merged value in `UnificationContext::merge_equal_metas` so we don't need to resolve that one.
=> fix(Inference): Consider shunted metas when comparing equality

src/types.rs, src/types/check.rs, src/types/primitive.rs
A missing doc is added for `PrimType::check_type` while I was there.
=> feat: Make TypeEnum and it's contents public

.github/workflows/issue.yml
In Jira, "priority" is not a mere string field, but an object, whose "name" field must be specified. I think this is what was going wrong with the last attempt
=> chore: Add priority to Jira issues

src/hugr/views/sibling_subgraph.rs
We connected the temporary built graph inputs and outputs, but the logic didn't take into account reordering in the signature, or non-linear parameters.
We can avoid the headache by not validating the intermediate construct.
=> fix: Don't insert temporary wires when extracting a subgraph

src/builder/build_traits.rs, src/hugr.rs, src/hugr/hugrmut.rs
So `connect` throws an error when passed invalid ports, but we still support `usize`s.
Closes #565. I choose not to allow backwards edges as that introduces a new failure mode when the directions are the same (and weird behaviour when passed one `Port` and one `usize`).
=> feat: Optional direction check when querying a port index

src/builder/module.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/rewrite.rs, src/hugr/validate.rs, src/hugr/views.rs, src/hugr/views/descendants.rs, src/hugr/views/sibling.rs, src/ops/custom.rs
* Add HugrError::InvalidTag, use in HierarchyView::try_new and SiblingMut::try_new
* In HugrMut::replace_op, check that changing the root-node's op does not invalidate the Root: NodeHandle tag.
* Hence, make HugrMut::replace_op return a Result
=> [new + bugfix] replace_op checks bound, adding HugrError::InvalidTag

src/hugr/views/sibling_subgraph.rs
Fixes #518 .
I changed the `non_convex_subgraph` test because the graph it was constructing seemed to meet the criteria for convexity, and replaced it with another one which doesn't. But please check -- I was a little confused by the definitions and may be missing something.
=> fix: Improve convexity checking and fix test

src/hugr/views/sibling_subgraph.rs
Added a `InvalidSubgraphBoundary` error variant so we get some info when the subgraph verification fails.
Fixes:
- It seems that the check for boundary nodes having outside neighbours (now `DisconnectedBoundaryPort`) was using an exhausted iterator, so it was not running.
With that fixed, now I get errors in the `portmatching` crate.
- `try_new_dataflow_subgraph` would return invalid subgraphs when the input is directly connected to an output.
It now ignores the wires. I'll add an issue to discuss what should be best behaviour in those cases.
=> feat: Better subgraph verification errors

src/hugr/views/sibling_subgraph.rs
And some drive-bys to modernise the code.
=> fix: ignore input->output links in SiblingSubgraph::try_new_dataflow_subgraph

src/algorithm/nest_cfgs.rs, src/extension/infer.rs
rust 1.73 is now stable and main breaks on these three. `clippy --fix` did the necessary :)
=> [chore] clippy updates - use Entry::or_default

src/hugr/views/sibling.rs
When creating a SiblingMut with a root whose type is constrained by being the root of the parent, ensure the "child" SiblingMut only narrows the constraint
=> fix: enforce covariance of SiblingMut::RootHandle

src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/insert_identity.rs, src/hugr/views.rs, src/hugr/views/descendants.rs, src/hugr/views/root_checked.rs, src/hugr/views/sibling.rs, src/hugr/views/sibling_subgraph.rs
* Factor out RootTagged as a subtrait of HugrView to allow separate implementation. Most things can still just use HugrView (as it happens everything that implements HugrView also implements RootTagged, but this is not required).
* HugrMut a subtrait of RootTagged not just HugrView
* Then add a new RootChecked struct storing any `AsRef<Hugr>` with a fixed RootHandle.
* It allows `.as_ref()`, throwing away the extra information in the RootHandle
* If the underlying view is a HugrMut then it is too
* Use trait-default implementations of Hugr(View,(Mut)Internals), as the latter check that `replace_op` does not break the bound on root-type
* But do not provide `.as_mut()` as that would allow bypassing and invalidating the extra info in the RootHandle
* Like SiblingMut, check that nested …
=> Add RootChecked to guarantee root node type

specification/hugr.md
* Clarify various characteristics of mu_in and mu_out maps in SimpleReplace
* Remove definitions (inc duplicate) of Partial Hugr and Separated (inlining into single use)
* Replace requires unique parent node P, removes set of children of P, adds new subtrees only as children of P (so drop `T` map)
* nu_in/nu_out use $\Gamma \setminus R$ rather than $\Gamma \setminus S^*$
* New children of $P$ added at positions vacated by removed children where possible
* Extend/clarify definition of what can be missing in the RHS, and what edges can be in the nu_in/nu_out
=> Update definition of Replace (and clarify SimpleReplace)

src/algorithm/half_node.rs, src/algorithm/nest_cfgs.rs, src/hugr/views/root_checked.rs
* IdentityCfgMap and HalfNodeView require RootTagged w/ CfgID rather than just HugrView
* Derive `Clone` for RootHandle
* implement a `fn borrow` (returning `RootHandle<&Hugr>`) for `RootHandle<&mut Hugr`
* Avoid some redundant checks and unwraps, remove a misleading `pub` (the structure it's on isn't pub)
=> [Refactor] Tidy some CFG structuring code, require RootHandle=CfgID

src/hugr/rewrite.rs, src/hugr/rewrite/insert_identity.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs
=> feat: Move `SimpleReplace::invalidation_set` to the `Rewrite` trait

src/extension/infer.rs, src/extension/op_def.rs, src/hugr/validate.rs, src/ops/custom.rs
* Refactor `resolve_extension_ops` to allow resolving, one node at a time, without mutation
* Use this in validation, to check OpaqueOp's are correct
* Improve the CustomOpError structure a bit
* Remove `check_opaque` - we've just done it properly, and it has no callers
* Update `infer.rs` tests - opaque operations must be from an unknown extension
=> Resolve opaque ops during validation (no mutation)

src/extension.rs, src/extension/type_def.rs
`check_custom_impl` had only one callsite.
=> Refactor: remove check_custom_impl by inlining into check_custom

specification/hugr.md
I read this as part of #557 and was just bewildered, so thought I'd see if I can do better. Admit it's not easy! How does this strike you?
=> spec: Rephrase confusing paragraph about TailLoop inputs/outputs

src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module.rs, src/extension/infer.rs, src/hugr.rs, src/hugr/rewrite/insert_identity.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/hugr/views/sibling.rs
BREAKING CHANGE: rename infer_and_validate -> update_validate
=> feat: resolve extension ops (mutating Hugr) in (infer_and_->)update_validate

src/builder/build_traits.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/views/sibling_subgraph.rs
insert_subgraph reused InsertionResult by making new_root into an Option. The "reuse" is trivial - what's left is a single field - so this avoids confusion as to when `new_root` is or is not None and thus a bunch of unwraps.
=> refactor: insert_subgraph just return HashMap, make InsertionResult new_root compulsory

.github/pre-commit, .github/workflows/pr-title.yml, DEVELOPMENT.md, README.md
Extracted from `tket2`, with minimal changes.
Adds a `DEVELOPMENT.md` file mentioning it the Conventional Commits format.
=> ci: Start checking conventional commit titles

Cargo.toml, src/hugr/views/sibling_subgraph.rs
- Update to `portgraph` `0.10`. Replaces `&mut ConvexChecker` parameters with `&`.
- Update to `pyo3` `0.20`.
BREAKING CHANGE: `pyo3` updated to `0.20`. Dependencies must have matching pyo3 versions since it links with python libs.
=> chore(deps)!: Update portgraph 0.10 and pyo3 0.20

specification/hugr.md, src/algorithm/nest_cfgs.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/tail_loop.rs, src/extension/infer.rs, src/extension/prelude.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/validate.rs, src/hugr/views/root_checked.rs, src/ops/constant.rs, src/ops/controlflow.rs, src/ops/validate.rs, src/std_extensions/logic.rs, src/types.rs, src/types/serialize.rs, src/values.rs
Closes #448
BREAKING CHANGE: previous uses of type/value constructor methods for "predicates" will need updating
=> refactor!: rename predicate to TupleSum/UnitSum

src/extension/infer.rs
No need to store `err` - there is exactly one case where we know it's Some, so we can always know what `unwrap_or` will do.
=> refactor: simplify infer.rs/report_mismatch using early return

src/builder.rs, src/builder/build_traits.rs, src/builder/circuit.rs, src/core.rs, src/extension/infer.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/hugr/views.rs, src/hugr/views/descendants.rs, src/hugr/views/petgraph.rs, src/hugr/views/sibling.rs, src/hugr/views/sibling_subgraph.rs, src/lib.rs, src/ops.rs, src/types/signature.rs, src/types/type_row.rs
Moves `CircuitUnit, Direction, IncomingPort, Node, NodeIndex, OutgoingPort, Port, PortIndex, Wire`
to a private `::core` module, and re-exports this from the root.
Most of the noise comes from modules accessing the internals of `Port` and `Node`, that now have to go through an accessor.
=> refactor: move the core types to their own module

src/builder/build_traits.rs, src/extension/infer.rs, src/hugr.rs
* Remove `impl From<&NodeType> for &OpType`
* Add new NodeType `fn op(&self) -> &OpType`
=> refactor: change &NodeType->&OpType conversion into op() accessor

.github/workflows/coverage.yml
The action is currently failing due to a missing artifact.
https://github.com/CQCL/hugr/actions/runs/6707167902/job/18225079786
=> ci: fallback for missing previous coverage report

src/extension/infer.rs
* No need for `&self` to be mutable
* Make control-flow more obvious
* Also, in merge_equal_metas(), do if contains ... remove.unwrap in one step
No change to semantics.
=> refactor: infer.rs 'fn results'

src/std_extensions/arithmetic/int_types.rs, src/std_extensions/quantum.rs
Use a trick suggested by @acl-cqc to remove the `unsafe`.
Drive-by: Remove unneeded clippy annotation.
=> refactor: Be safe

src/builder.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/dataflow.rs, src/builder/module.rs, src/builder/tail_loop.rs, src/extension/infer.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/hugr/views/root_checked.rs, src/hugr/views/sibling.rs
* Rename NodeType::open_extensions to NodeType::new_open
* Rename NodeType::pure to NodeType::new_pure
* Add NodeType::new_auto, which uses Pure for module-ops and Open for others
* Remove special-case in infer.rs solving some module-ops to empty set
* Switch builder/HugrMut methods from new_open to new_auto
=> refactor: NodeType constructors, adding new_auto

src/extension.rs, src/extension/infer.rs, src/std_extensions/arithmetic/conversions.rs
* Convert ExtensionSet from HashSet to BTreeSe => trivially derive Hash
* Constraint::Plus stores an ExtensionSet, rather than a single Extension => gen_union_constraint avoids long chains of metas
* Inline gen_union_constraint (no longer recursive)
=> refactor: Constraint::Plus stores an ExtensionSet, which is a BTreeSet

src/extension/op_def.rs, src/ops.rs, src/ops/custom.rs, src/ops/leaf.rs, src/types.rs, src/types/signature.rs
BREAKING CHANGES: `SignatureDescription` no longer exists.
=> refactor!: remove `SignatureDescription`

.gitignore, DEVELOPMENT.md, justfile
drive-by: Copy relevant rules from tket2's justfile.
=> docs: Coverage check section in DEVELOPMENT.md

Cargo.toml, src/core.rs, src/lib.rs
This replaces boilerplate like
```rust
match port.direction() {
Direction::Incoming => {
let incoming = port.as_incoming().unwrap();
...
}
Direction::Outgoing => {
let outgoing = port.as_outgoing().unwrap();
...
}
}
```
with
```rust
match port.as_directed() {
Left(incoming) => ...
Right(outgoing) => ...
}
```
drive-by: Drop leftover `Port::try_new_outgoing`.
=> feat: port.as_directed to match on either direction

src/hugr/views/petgraph.rs
Since PetgraphWrapper is a reference to a HugrView, we implement GraphRef directly. This simplifies the implementation of several traits.
=> feat: impl GraphRef for PetgraphWrapper

src/extension/op_def.rs, src/extension/prelude.rs, src/std_extensions/arithmetic/conversions.rs, src/std_extensions/arithmetic/float_ops.rs, src/std_extensions/arithmetic/int_ops.rs, src/std_extensions/collections.rs, src/std_extensions/logic.rs, src/std_extensions/quantum.rs
Ooops, these were accidentally hit by renaming in #642 .
Driveby: change a couple of `add_op_custom_sig`'s in extension.rs to use the `custom_sig_simple` variant
=> refactor: rename accidentally-changed Extension::add_node_xxx back to add_op

.github/workflows/notify-coverage.yml
Renames the workflow to better indicate its purpose, so it doesn't get mixed up with the PR coverage reports.
=> ci: Better name for the daily coverage notif workflow

src/builder/build_traits.rs, src/builder/dataflow.rs, src/hugr.rs, src/hugr/hugrmut.rs, src/hugr/rewrite/simple_replace.rs, src/hugr/serialize.rs, src/hugr/views.rs
=> feat: Require the node's metadata to always be a Map

src/extension/prelude.rs
to allow angle extension to be moved out
=> feat: make prelude error type public

src/ops/constant.rs, src/values.rs
=> feat: shorthand for retrieving custom constants from `Const`, `Value`

src/extension/op_def.rs, src/extension/prelude.rs, src/hugr/validate/test.rs, src/std_extensions/arithmetic/conversions.rs, src/std_extensions/arithmetic/float_ops.rs, src/std_extensions/arithmetic/float_types.rs, src/std_extensions/arithmetic/int_ops.rs, src/std_extensions/arithmetic/int_types.rs, src/std_extensions/collections.rs, src/std_extensions/logic.rs, src/utils.rs
Closes #658 
As a drive by improve extensions test coverage as I went.
Definition can be a bit unintuitive, should improve after #676 is done.
=> refactor: use type schemes in extension definitions wherever possible

src/extension/op_def.rs
These were the wrong way around.
Closes #683
=> fix: Serialise dynamically computed opaqueOp signatures

src/extension/infer/test.rs, src/extension/op_def.rs, src/hugr/rewrite/replace.rs, src/hugr/validate/test.rs, src/hugr/views/sibling_subgraph.rs, src/lib.rs, src/types.rs, src/types/serialize.rs, src/types/signature.rs, src/utils.rs, src/values.rs
Closes #664 .
BREAKING_CHANGES: `FunctionType::new_linear()` renamed to `FunctionType::new_endo()`.
=> refactor!: Rename `new_linear()` to `new_endo()`.

.github/workflows/notify-coverage.yml
We store the last commit we notified about, so the notifications actually cover the period we care about.
=> ci: Compare coverage using specific commit shas

src/extension/infer.rs, src/extension/infer/test.rs, src/extension/validate.rs, src/hugr.rs, src/types/signature.rs
The signature() method on NodeType basically only existed so the caller could get both the input and output extensions (Signature providing the `.output_extensions()` method). Instead, provide `nodetype.io_extensions()` returning the same information.
This does leave Signature itself, which is a bit of a carbuncle.
=> refactor: Replace NodeType::signature() with io_extensions()

src/extension.rs, src/extension/op_def.rs, src/extension/prelude.rs, src/hugr/rewrite/replace.rs, src/hugr/validate/test.rs, src/lib.rs, src/ops/constant.rs, src/ops/leaf.rs, src/std_extensions/arithmetic/conversions.rs, src/std_extensions/arithmetic/int_ops.rs, src/std_extensions/collections.rs, src/types.rs, src/types/poly_func.rs, src/utils.rs
Closes #676 
* Replace PolyFunc::new_validated with ::new to allow (a) building without an ExtensionRegistry and (b) PolyFuncTypes with free variables (necessary for nested instances)
* Update a bunch of code in std_extensions code and elsewhere using a `temp_reg` or similar, this is no longer needed
* Change `[Extension1, Extension2, ...].into()` into `ExtensionRegistry::try_new` which does validation and can fail with an `(ExtensionId, SignatureError)`
* This required updating the test_quantum extension's registry to include float_types
* Some commoning up of registries, and move `test_registry` to the one file that actually used it (it doesn't seem so distinguished now we have registries all over the place!)
=> refactor: validate ExtensionRegistry when built, not as we build it

src/extension/op_def.rs, src/types/type_param.rs
Add test that we can pass typevars to TypeScheme part but not binary part. Fix inconsistency between validate_args and compute_signature.
Also add `impl From<Type> for TypeArg`, this is so much easier than the awkward brace syntax `TypeArg::Type {ty:...}`, tho sometimes that's good for explicitness :)
=> fix: binary compute_signature returning a PolyFuncType with binders

.github/workflows/notify-coverage.yml
We computed everything correctly, but printed the old value twice >.<
=> ci: Fix incorrect coverage reported

src/extension.rs, src/extension/op_def.rs, src/extension/prelude.rs, src/lib.rs, src/std_extensions/arithmetic/conversions.rs, src/std_extensions/arithmetic/float_ops.rs, src/std_extensions/arithmetic/int_ops.rs, src/std_extensions/collections.rs, src/std_extensions/logic.rs, src/types/poly_func.rs, src/types/serialize.rs, src/utils.rs
Closes #675 but not exactly as specified in the issue - SignatureFunc is still an enum, but something close to the desired interface is achieved.
BREAKING_CHANGES: `Extension::add_op...` methods simplified and renamed, there is only `add_op` and `add_op_simple` now.
=> feat!: simplify `SignatureFunc` and add custom arg validation.

src/extension/op_def.rs, src/extension/prelude.rs, src/lib.rs, src/std_extensions/arithmetic/conversions.rs, src/std_extensions/arithmetic/float_ops.rs, src/std_extensions/arithmetic/int_ops.rs, src/std_extensions/collections.rs, src/std_extensions/logic.rs, src/utils.rs
Methods to allow appending extra data to opdef after adding to extension.
BREAKING_CHANGES: `add_op` behaves like the now-removed `add_op_simple`
=> refactor!: one way to add_op to extension

Cargo.toml, README.md, src/builder.rs, src/core.rs, src/hugr.rs, src/hugr/serialize.rs, src/hugr/validate.rs, src/hugr/views/sibling_subgraph.rs, src/lib.rs, src/types.rs, src/types/signature.rs, src/types/type_row.rs
Drop the remaining python binding definitions from the crate.
We currently re-wrap all objects in `tket2-py`, and only required this for the `Into<PyErr>` implementations. As of https://github.com/CQCL/tket2/pull/258, this is no longer needed.
The main benefit of removing this dependency is avoiding linking problems when mismatching versions of `pyo3` are used by different dependencies. The error is unavoidable due to it dynamically linking to a single `python` lib, and cargo doesn't provide an easy way to deal with it.
=> feat!: Drop the `pyo3` feature

.github/workflows/ci.yml
Performance is about the same, but this is consistent with tket2's CI worflows.
=> ci: Use sccache instead of rust-cache

src/extension/op_def.rs, src/extension/prelude.rs, src/extension/type_def.rs, src/hugr/validate/test.rs, src/std_extensions/collections.rs, src/types.rs, src/types/poly_func.rs, src/types/type_param.rs
Needed for Pydantic serialisation.
BREAKING_CHANGES: Turn the `TypeParam` enum variants into struct variants
=> fix!: Add serde tag to TypeParam enum

Cargo.toml, src/extension.rs, src/extension/op_def.rs, src/extension/simple_op.rs, src/ops/custom.rs, src/ops/leaf.rs, src/std_extensions/logic.rs
BREAKING_CHANGES: const logic op names removd
Closes #656 
Have demonstrated with logic operations, pending comments on general approach can port other larger extension op sets:
TODO:
=> feat!: `OpEnum` trait for common opdef functionality

src/builder/build_traits.rs, src/builder/dataflow.rs, src/builder/module.rs, src/ops/validate.rs, src/types/poly_func.rs
required to update tket2 to latest hugr commits
=> feat: getter for `PolyFuncType::body`

src/hugr/serialize.rs
The tests all checked something different after the serialization rountrip.
This adds a check function to tests hugrs after the rondtrip.
Also drops the `metadata_hugr_ser` test, which was a duplicate from `weighted_hugr_ser`.
=> test: Unify the serialisation tests

src/builder/circuit.rs, src/extension/infer/test.rs, src/extension/op_def.rs, src/hugr/rewrite/replace.rs, src/hugr/serialize.rs, src/ops/custom.rs, src/ops/leaf.rs
Closes #689 
Adds a previously-failing test for the serialiser, where the signature of an opaque op was discarded and couldn't be recovered. Depends on #730.
=> feat: Always require a signature in `OpaqueOp`

src/algorithm/nest_cfgs.rs, src/builder/build_traits.rs, src/builder/cfg.rs, src/builder/conditional.rs, src/builder/tail_loop.rs, src/extension.rs, src/extension/infer.rs, src/extension/prelude.rs, src/hugr.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/replace.rs, src/hugr/validate/test.rs, src/hugr/views/tests.rs, src/ops.rs, src/ops/constant.rs, src/ops/controlflow.rs, src/ops/dataflow.rs, src/std_extensions/arithmetic/float_types.rs, src/std_extensions/arithmetic/int_types.rs, src/std_extensions/collections.rs, src/values.rs
* Make each Value able to report its ExtensionSet needed at runtime (and hence, also each CustomConst)
* Also give OpTrait a method for the extension-delta. This is the delta of the FunctionType, *for dataflow ops*, but can be defined for other optypes too - specifically (here), Const ops and also Case. Use this in both inference and for `NodeType::io_extensions()`
* Input extensions of every Const node can now be the empty set (i.e. the default-for-ModuleOp `pure`), as the relevant extension will be added in the delta - thus, drop separate extension parameter in builder (add_constant, add_load_const, etc.). LoadConstant ops can now also have an empty delta and open input-extensions as these can be figured out from the Const. This is thus a step towards fixing #702...
* Also note slight …
=> feat: Values (and hence Consts) know their extensions

Cargo.toml, src/hugr/views/sibling_subgraph.rs
A new portgraph release is needed for this.
=> feat!: use ConvexChecker trait

src/extension/infer/test.rs, src/hugr/rewrite/replace.rs, src/ops/controlflow.rs
Previously it was incorrectly reporting the internal signature as the node signature.
Fixes #750 
Required further fixes to `replace.rs`:
* test was looking for an error that should have been hidden behind another (that was not previously reported because of #750). Look for the latter, not the former.
* Fix node indices not being correctly reported from `apply`
=> fix: case node should not have an external signature

src/ops/constant.rs, src/std_extensions/arithmetic/conversions.rs, src/std_extensions/arithmetic/float_ops.rs, src/std_extensions/arithmetic/float_types.rs, src/std_extensions/arithmetic/int_ops.rs, src/std_extensions/collections.rs, src/utils.rs
BREAKING CHANGES: extension() function replaced with EXTENSION static ref for float_ops and conversions
=> refactor!: use enum op traits for floats + conversions

specification/hugr.md
=> docs: Spec updates

specification/hugr.md
I believe the question of causal cones was definitively resolved by #468, and the codebase seems clear on that point - however, I just stumbled across this I-believe-erroneous reference in the spec. (FWIW, searching through the spec for "causal" has only one other occurrence, which appears to explicitly say we don't need this rule.)
=> docs: [spec] Remove references to causal cone and Order edges from Input

Cargo.toml, devenv.lock, devenv.nix, src/hugr/views.rs, src/hugr/views/tests.rs
and devenv update to 1.75 stable
=> chore: remove rustversion

src/builder/cfg.rs, src/extension/infer/test.rs, src/hugr/rewrite/outline_cfg.rs, src/hugr/rewrite/replace.rs, src/hugr/validate/test.rs, src/hugr/views/root_checked.rs, src/ops.rs, src/ops/controlflow.rs, src/ops/handle.rs, src/ops/validate.rs
BREAKING_CHANGES: `BasicBlock::{DFB, Exit}` are now standalone structs `DataflowBlock, ExitBlock`. A level of nesting in serialization is also removed for these operations.
=> refactor!: unwrap BasicBlock enum 

src/hugr/hugrmut.rs, src/hugr/serialize.rs, src/ops.rs, src/ops/constant.rs, src/ops/dataflow.rs, src/ops/module.rs
Closes #777.
Now `OpTrait` clearly separates `other_port` from `static_port`, and `OpType` has a uniform interface for `value` ports (from the signature), `static` ports (contstants), and `other` ports.
Fixes #779. The bug was caused by the encoder ignoring the constant input port offset, so the decoder reconnected the edge to the `StateOrder` port instead. Now we use the proper OpType methods.
Fixes #778.
=> fix!: Normalize input/output value/static/other ports in `OpType`

specification/hugr.md, src/algorithm/const_fold.rs, src/hugr/rewrite/consts.rs
Renames the rewrite to better reflect it's goal.
Closes #767
=> refactor!: `s/RemoveConstIgnore/RemoveLoadConstant`

.github/workflows/ci.yml, Cargo.toml, src/extension.rs, src/extension/infer/test.rs, src/extension/validate.rs, src/hugr.rs, src/hugr/validate.rs, src/hugr/validate/test.rs
Add a feature flag "extension_inference", without which `Hugr::infer_extensions` is replaced by a dummy method, and `ValidationContext` doesn't use a `ExtensionValidator`, and tests that require extension inference to be done are disabled.
Our CI runs tests and benchmarks once with default features, then again with all features, so extension inference is still being tested by CI. The workflow has only been altered to tell `clippy` to run with all features as well.
Resolves #784
=> refactor: Put extension inference behind a feature gate

src/algorithm/const_fold.rs, src/std_extensions/logic.rs
=> feat: constant folding for logic extension

src/hugr/rewrite/replace.rs, src/ops/controlflow.rs
Basic blocks should not have a `dataflow_signature`, they have no dataflow ports! But, for DataflowBlock, implement `extension_delta` instead (and fix replace.rs test correspondingly)
=> fix: No dataflow_signature for block types

src/algorithm/const_fold.rs, src/extension.rs, src/std_extensions/collections.rs
+ utility enums and structs for dealing with list ops and types
Closes #774
=> feat: constant folding for list operations

src/hugr/serialize.rs
The miri test in CI currently [fails](https://github.com/CQCL/hugr/actions/runs/7447240566/job/20259152793) with an error `"unknown variant 'ConstF64', there are no variants"`.
This is due to `CustomConst` serialization depending on `typetag`, which registers each constant variant at the start of the program using `ctor` (i.e. running code before `main`).
Miri does not currenly [support running this](https://www.github.com/rust-lang/miri/issues/450), so the deserialization finds the CustomConst registry empty (hence the "there are no variants").
The solution until support is added to miri is just to ignore test with constants.
=> fix: Ignore unsupported test in miri

specification/hugr.md
=> docs: collection of spec updates for 0.1

src/hugr/serialize.rs
otherwise fails miri checks by opening file
running workflow manually to check
=> fix: include schema rather than read file

specification/hugr.md
* Move "Operation Extensionsibility" to after Type System (and up one level), rename to "Extension System"
* Add Polymorphism section inside Type System: any `Function` type may be polymorphic
* Clarify working of operations, including adding Appendix 3 with full details binary `compute_signature`
* Add `OpaqueOp` as a dataflow node operation
fixes #790
=> docs: Update spec wrt. polymorphism

README.md
Seems I forgot to link the image >.<
=> docs: Fix crates.io badge in README

README.md
These broke when rendered in another site like docs.rs.
I'm keeping these pointed to HEAD, as we'll generally want to use the latest version.
=> docs: Use absolute links in the README

src/extension/infer.rs, src/hugr/rewrite.rs, src/hugr/rewrite/inline_dfg.rs, src/utils.rs
* The spec doesn't have a lot to say here, but in particular, we handle Order edges both internal (to/from the inner Input/Output) and external (to/from the inlined DFG)
* And, works for permutation (swap) DFGs
* Includes fix to extension inference (search_variable_deps) to handle metas with a solution but no constraints
=> feat: Add InlineDFG rewrite

src/algorithm/const_fold.rs, src/extension/prelude.rs, src/hugr/validate/test.rs, src/ops/constant.rs, src/std_extensions/arithmetic/float_types.rs, src/std_extensions/arithmetic/int_types.rs, src/std_extensions/collections.rs, src/types/check.rs, src/values.rs
We remove `trait KnownTypeConst` as it is now redundant. We move the body of `check_known_type` into a new default implementation of `CustomConst::check_custom_type`.
=> feat!: impls of CustomConst must be able to report their type

examples/extension/declarative.yaml, specification/hugr.md, src/extension.rs, src/extension/declarative.rs, src/extension/declarative/ops.rs, src/extension/declarative/signature.rs, src/extension/declarative/types.rs, src/extension/op_def.rs, src/extension/type_def.rs, src/types.rs, src/types/custom.rs, src/utils.rs
This PR add a method `hugr::extensions::declarative::load_extensions` that dynamically loads a set of extensions defined as YAML onto a registry.
The code is mostly comprised of struct definitions to match the human-readable serialisation format described in the spec, and some methods to translate them into the internal hugr definitions.
There's a myriad of TODOs that should be addressed in future PRs, including:
- Most parametric things (operations, type bounds, number of ports in a signature, ...).
- Lowering functions, operations with non explicit signatures.
- Resolving the signature types.
- The syntax for describing these is not defined in the spec, so currently there's just a couple of basic hard-coded types used for testing: "Q" and "USize".
Here's an example of a supported …
=> feat: Minimal implementation for YAML extensions

Cargo.toml
From the `cargo-release` log:
```
warning: the following are not valid category slugs and were ignored: Compilers.
Please see https://crates.io/category_slugs for the list of all category slugs. 
```
The category should be in [lower-case](https://crates.io/category_slugs).
=> chore: Fix crates.io category capitalization

examples/extension/declarative.yaml, src/extension/declarative.rs, src/extension/declarative/signature.rs
The current yaml extension definitions only support hard-coded types in the operation signatures.
This PR leaves the existing `Q` and `USize` hardcoded values, but tries to dereference the type name from the extensions in scopes otherwise.
drive-by: Extend the module doc with an example on how to load the extension.
=> feat: Arbitrary types in the yaml extension definition

specification/hugr.md, specification/schema/serialization.md, src/algorithm/nest_cfgs.rs, src/extension/infer/test.rs, src/hugr/views/sibling_subgraph.rs
- docs: fix hugr URLs
- docs(spec): normalize gremlins
- fix: prefer DOI/handle links over others for papers
- style: markdownlint it
- fix(spec): several edits
=> docs: HUGR spec copyediting

src/core.rs
Implements serialization on some core types that where missing it (Incoming/Outgoing ports, Wires, ...)
Required for https://github.com/CQCL/tket2/issues/220
=> feat: Make all core types serializable

src/builder.rs, src/builder/build_traits.rs, src/builder/circuit.rs, src/hugr/rewrite/simple_replace.rs
drive-by: Make the `CircuitBuilder` constructor a bit more generic.
=> docs: Add builder module docs + example

.github/workflows/unsoundness.yml, quantinuum-hugr/src/hugr/views/tests.rs
- Fixes the failing unsoundness check in `main`
https://github.com/CQCL/hugr/actions/runs/8158956607/job/22302072598
The test change in #852 moved the miri ignore flag, and it seems it has to be placed after `rstest`'s cases.
- Adds a concurrency group for the unsoundness check.
The check currently takes around 15mins (and it will only grow as we add more tests).
This makes it so old jobs get cancelled when pushing new changes to main, and a new check is started.
=> ci: Skip invalid miri test, avoid concurrent undsoundness checks

quantinuum-hugr/src/builder.rs, quantinuum-hugr/src/builder/build_traits.rs, quantinuum-hugr/src/builder/cfg.rs, quantinuum-hugr/src/builder/conditional.rs, quantinuum-hugr/src/builder/dataflow.rs, quantinuum-hugr/src/builder/module.rs, quantinuum-hugr/src/extension/infer/test.rs, quantinuum-hugr/src/hugr.rs, quantinuum-hugr/src/hugr/hugrmut.rs, quantinuum-hugr/src/hugr/rewrite.rs, quantinuum-hugr/src/hugr/rewrite/consts.rs, quantinuum-hugr/src/hugr/rewrite/inline_dfg.rs, quantinuum-hugr/src/hugr/rewrite/insert_identity.rs, quantinuum-hugr/src/hugr/rewrite/outline_cfg.rs, quantinuum-hugr/src/hugr/rewrite/replace.rs, quantinuum-hugr/src/hugr/rewrite/simple_replace.rs, quantinuum-hugr/src/hugr/serialize.rs, quantinuum-hugr/src/hugr/validate/test.rs, quantinuum-hugr/src/hugr/views.rs, quantinuum-hugr/src/hugr/views/render.rs, quantinuum-hugr/src/hugr/views/root_checked.rs, quantinuum-hugr/src/hugr/views/sibling.rs, quantinuum-hugr/src/hugr/views/sibling_subgraph.rs
While all `HugrView` methods are infallible (panicking when a node is not found), most `HugrMut` methods returned a `Result`, even though they only failed on the same case.
This PR makes most `HugrMut` methods infallible (except for `replace_op`). This simplify the API and lets us remove a lot of `unwrap`s all around the codebase.
We can further cascade the `unwrap` removal to the builder (as `create_with_io` and others can now be made infallible), but I'll do that on another PR as this one is noisy enough.
The first commit contains the relevant changes. The 2nd one just removes all the `unwrap`s.
BREAKING CHANGE: Made most `HugrMut` methods infallible.
=> feat!: infallible `HugrMut` methods

quantinuum-hugr/src/builder.rs, quantinuum-hugr/src/builder/circuit.rs, quantinuum-hugr/src/builder/handle.rs, quantinuum-hugr/src/utils.rs
Adds `add_ancilla` and `discard_ancilla` methods to the circuit builder, to modify the list of tracked wires.
Also adds extra info in the error messages.
Closes #854.
=> feat: Ancilla support in CircuitBuilder

quantinuum-hugr/src/builder.rs, quantinuum-hugr/src/builder/build_traits.rs, quantinuum-hugr/src/builder/circuit.rs, quantinuum-hugr/src/builder/handle.rs, quantinuum-hugr/src/utils.rs
- Fleshes out `utils::collect_array`, and uses it in all the methods that return a fixed size array.
- Adds `CircuitBuilder::append_with_output_arr`.
Follow up to  https://github.com/CQCL/hugr/pull/867#discussion_r1517711129
=> feat: `CircuitBuilder::append_with_output_arr`

quantinuum-hugr/src/algorithm/const_fold.rs, quantinuum-hugr/src/algorithm/nest_cfgs.rs, quantinuum-hugr/src/builder/build_traits.rs, quantinuum-hugr/src/builder/cfg.rs, quantinuum-hugr/src/builder/conditional.rs, quantinuum-hugr/src/builder/dataflow.rs, quantinuum-hugr/src/builder/module.rs, quantinuum-hugr/src/builder/tail_loop.rs, quantinuum-hugr/src/extension/prelude.rs, quantinuum-hugr/src/hugr/rewrite/consts.rs, quantinuum-hugr/src/hugr/rewrite/inline_dfg.rs, quantinuum-hugr/src/hugr/rewrite/outline_cfg.rs, quantinuum-hugr/src/hugr/rewrite/replace.rs, quantinuum-hugr/src/hugr/serialize.rs, quantinuum-hugr/src/hugr/validate/test.rs, quantinuum-hugr/src/hugr/views/tests.rs, quantinuum-hugr/src/ops/constant.rs
Updated methods that could only return `Err` on internal bugs.
This is a followup to #869, doing some more cleaning on the `build_traits::Container` interface.
Changes outside `build_traits.rs` are just fixing the call sites.
BREAKING CHANGE: Multiple methods in `Container` no longer return a `Result`
=> feat!: Make some `Container` methods infallible

quantinuum-hugr/Cargo.toml, quantinuum-hugr/benches/bench_main.rs, quantinuum-hugr/src/builder.rs
#868 didn't actually enable the lints in `quantinuum-hugr` when the config was moved to the workspace.
=> chore: Re-enable missing-docs lint

quantinuum-hugr/src/algorithm/const_fold.rs
This tests fails at runtime if extension inference is enabled.
We should however compile it, so compiler errors are more easily catched.
=> chore: Compile the test skipped due to extension_inference

quantinuum-hugr/src/extension/infer.rs
I think these are generally `pub` methods of *non-pub* classes, so not generally accessible anyway, but (a) just in case and (b) makes it clearer that they aren't `pub`
Also remove `pub fn new` from `Meta` as if it's not there to make things more-pub, then it really doesn't do much.
=> refactor: Extension Inference: make fewer things public, rm Meta::new

quantinuum-hugr/src/hugr/views.rs, quantinuum-hugr/src/hugr/views/descendants.rs, quantinuum-hugr/src/hugr/views/sibling.rs, quantinuum-hugr/src/types/check.rs
`get_function_type` was confusing, as it didn't specify that it only worked for dataflow containers, and required manually checking for function declarations on the side.
BREAKING CHANGE: `HugrView::get_function_type` now returns a `PolyFuncType`.
=> feat!: Return the type of FuncDecl in `HugrView::get_function_type`

quantinuum-hugr/src/algorithm/const_fold.rs, quantinuum-hugr/src/algorithm/nest_cfgs.rs, quantinuum-hugr/src/builder/cfg.rs, quantinuum-hugr/src/extension/prelude.rs, quantinuum-hugr/src/hugr/rewrite/inline_dfg.rs, quantinuum-hugr/src/hugr/validate/test.rs, quantinuum-hugr/src/lib.rs, quantinuum-hugr/src/ops.rs, quantinuum-hugr/src/ops/constant.rs, quantinuum-hugr/src/ops/constant/custom.rs, quantinuum-hugr/src/std_extensions/arithmetic/conversions.rs, quantinuum-hugr/src/std_extensions/arithmetic/conversions/const_fold.rs, quantinuum-hugr/src/std_extensions/arithmetic/float_types.rs, quantinuum-hugr/src/std_extensions/arithmetic/int_ops.rs, quantinuum-hugr/src/std_extensions/arithmetic/int_types.rs, quantinuum-hugr/src/std_extensions/collections.rs, quantinuum-hugr/src/std_extensions/logic.rs, quantinuum-hugr/src/types.rs, quantinuum-hugr/src/types/check.rs, quantinuum-hugr/src/types/poly_func.rs, quantinuum-hugr/src/values.rs, specification/schema/hugr_schema_v1.json
`Const` was a struct with a `Value` + a defined type. In practice, the only `Value` that couldn't report its full type was `Sum`.
This PR merges the two structs, adding an explicit `sum_type` to the sum variant.
Also:
- Removes `Type::check_type`, as this is now unnecessary. 
- Splits and clarifies the type check and constant errors;
`SumTypeError` is not a `ConstTypeError` is not a `CustomCheckFailure`.
- Adds contexts to those errors, so we get better messages.
- `CustomConst` is now accessible from `::ops::custom` instead of `::values`.
This change breaks the serialisation format.
Closes #874.
BREAKING CHANGE: Removed `Value`, merged into `Const`
=> feat!: Merge `Value` into `Const`

.github/workflows/ci-py.yml, .github/workflows/ci-rs.yml
The change detection job is failing for non-pull-request checks, because we need to explicitly checkout the repo on those cases.
See https://github.com/CQCL/hugr/actions/runs/8342261546/job/22830024125
I'm also adding `changes` as a requirement to the required check, so it fails on errors like this.
=> ci: always checkout the repo, even if we don't need the change detection

quantinuum-hugr/benches/bench_main.rs, quantinuum-hugr/benches/benchmarks/hugr.rs, quantinuum-hugr/benches/benchmarks/mod.rs, quantinuum-hugr/benches/benchmarks/types.rs
Adds some actual benchmarks, mainly extracted from the unit tests:
- Construct a complex `Type`
- Construct a `DFG` hugr
- Construct a `CFG` hugr
I intended to include these in a PR implementing this optimisation suggestion https://github.com/CQCL/hugr/pull/891#issuecomment-2018046379, but the actual tests showed a consistent 4% slowdown on the hugr builders.
So I'd say it's important to have benchmarks :)
=> perf: Add some simple benchmarks

cliff.toml
Imports part of the github template from `git-cliff`, so the changelog mentions the new contributors to the repo.
See https://git-cliff.org/docs/integration/github.
E.g.:
```
New Contributors:
* @Cobord made their first contribution in [#889](https://github.com/CQCL/hugr/pull/889)
* @qartik made their first contribution in [#843](https://github.com/CQCL/hugr/pull/843)
…
```
=> chore: Show new contributors in the changelog

cliff.toml
Reverts #893 
It seems git-cliff's github extension is not yet supported by release-plz >.<
See this PR: https://www.github.com/MarcoIeni/release-plz/pull/1305
I'll reopen the PR once this release-plz is updated.
This reverts commit 25b1013fa9943f4af90030d5842da1d682cc1286.
=> revert: Show new contributors in the changelog

quantinuum-hugr/src/builder/build_traits.rs, quantinuum-hugr/src/hugr/validate/test.rs, quantinuum-hugr/src/ops/dataflow.rs
* Store the polymorphic type of the called function in Call node, use for the static input
* Also store the typeargs, and the cache of the instantiation
BREAKING CHANGE: `Call` nodes now constructed via `try_new` function
=> fix: polymorphic calls

.github/workflows/ci-py.yml, .github/workflows/python-wheels.yml, pyproject.toml, quantinuum-hugr-py/README.md, quantinuum-hugr-py/pyproject.toml
Adds a CI job that
- Publishes each push to main to the **test** pypi repository.
- When a `quantinuum-hugr-py-v*` tag is pushed, publishes the python package to pypi
(this is done generically, so other python
Closes #907 
I will make another PR configuring `release-please`, to automate the changelog and releases side.
Until we are ready to publish `0.1.0`, we can publish alpha versions manually by pushing tags.
=> ci: Publish python package to pypi

.github/workflows/python-wheels.yml
The `format` template expression needs an index inside the `{}` placeholder.
See error: https://github.com/CQCL/hugr/actions/runs/8539664657/job/23394814844#step:9:1
=> ci: Fix wheels job

specification/hugr.md
Turns out the implementation in the constant-folding code is already in line with this modified specification, so this is not a breaking change.
Closes #771 .
=> docs: Modify specification of `trunc_u` and `trunc_s`.

.github/workflows/release-please.yml, .pre-commit-config.yaml, .release-please-manifest.json, release-please-config.json
Fixes some config in release-please so now it looks for the right version tags `hugr-py-v*.*.*`. It doesn't seem to like alphas though, so the first releases will need some manual tweaking (it tries to do 0.1.0 otherwise).
The CI job is failing with some github permission error... I copied the guppy one to try and fix that, but I can run it locally via the CLI if needed for these first releases.
=> ci: fix package name in release-please

.github/workflows/python-wheels.yml, release-please-config.json
Try to debug why why the release of https://github.com/CQCL/hugr/releases/tag/hugr-py-v0.1.0 didn't trigger a the wheels publishing action.
I relaxed the tag filter from `*` to `**` (i.e. include sub-paths) to see if that works.
drive-by: Unset `prerelease` flag in release please, so the release gets the published status.
=> ci: Debug logging on python wheels job

hugr/src/hugr/rewrite/replace.rs, hugr/src/hugr/rewrite/simple_replace.rs
This is a preliminary step towards using merging basic blocks, where the Replace rewrite needs to be used as part of a larger   transformation - this makes it possible to use compositionally.
Along the way, refactor the tests a bit (changing `verify_apply` to `check_same_error` and doing all the bad/`Err`-returning cases after the success case).
=> feat: 'Replace' rewrite returns node map

hugr/src/ops/leaf.rs
The struct definitions are now `non_exhaustive`, so they cannot be build with the `Noop {ty: ..}` syntax outside of this crate.
=> feat: `new` methods for leaf ops

hugr/src/ops/custom.rs
Small utility function, both variants of a `CustomOp` expose their extension already.
=> feat: `CustomOp::extension` utility function

hugr/src/algorithm/nest_cfgs.rs, hugr/src/builder/conditional.rs, hugr/src/extension/declarative.rs, hugr/src/extension/infer.rs, hugr/src/extension/simple_op.rs, hugr/src/extension/validate.rs, hugr/src/hugr/rewrite/consts.rs, hugr/src/hugr/rewrite/inline_dfg.rs, hugr/src/hugr/rewrite/insert_identity.rs, hugr/src/hugr/rewrite/outline_cfg.rs, hugr/src/hugr/rewrite/replace.rs, hugr/src/hugr/rewrite/simple_replace.rs, hugr/src/hugr/serialize.rs, hugr/src/hugr/validate.rs, hugr/src/hugr/views/sibling_subgraph.rs, hugr/src/ops/constant.rs, hugr/src/ops/custom.rs, hugr/src/ops/validate.rs, hugr/src/std_extensions/arithmetic/conversions.rs, hugr/src/std_extensions/arithmetic/float_ops.rs, hugr/src/std_extensions/arithmetic/int_ops.rs, hugr/src/std_extensions/collections.rs, hugr/src/std_extensions/logic.rs, hugr/src/types.rs, hugr/src/types/check.rs, hugr/src/types/type_param.rs
Mainly to `std_extensions` definitions and error enums.
This missing caused #942 to be a breaking change, since it adds new variants to the `FloatOps` and `IntOpDef` extensions. See the failing semver-checks in #928.
=> feat!: Add `non_exhaustive` to various enums

hugr-py/src/hugr/__init__.py, hugr-py/src/hugr/serialization/serial_hugr.py, hugr/src/hugr/serialize.rs, justfile, specification/schema/hugr_schema_v1.json
Closes #950.
Adds a `hugr-rs v0.3.0` or a `hugr-py v0.1.0` label to the serialialised hugrs under the optional `encoder` field.
This should help with debuggability and error reporting in the future, for now we just ensure that we start adding the labels. The added field to the schema is backwards-compatible.
I had to add a `__version__` field at the root of the python package. This is automatically updated by `release-please`, so it shouldn't be much of an issue.
drive-by: force `poetry update` before generating the schema in `just update-schema`, to make sure we are using the same pinned pydantic version as CI.
=> feat: Encoder metadata in serialized hugr

hugr/CHANGELOG.md, hugr/Cargo.toml
Merges the patch published for `hugr-v0.3.1`, to keep the changelog consistent.
=> chore: Merge v0.3.1 changes onto main

.github/workflows/pr-title.yml
Prints a helpful message when the PR title does not follow the conventional commits format.
The message gets deleted automatically once the title is fixed.
=> ci: Make a comment when the PR title is wrongly formatted

.pre-commit-config.yaml
This is the check run in CI, so it should be also included in the hooks
=> chore: Add cargo doc check to pre-commit

hugr/src/algorithm/const_fold.rs, hugr/src/hugr/rewrite/inline_dfg.rs, hugr/src/std_extensions/arithmetic/conversions/const_fold.rs, hugr/src/std_extensions/arithmetic/int_types.rs
Fixes #970 .
Drive-by: change name of integer constant to show width rather than log width, e.g. `u32(1000)` not `u5(1000)`.
(Note that the name always shows the unsigned interpretation. We could make it show both, but I'm not sure it's worth it.)
I assume this will break serialization. Do I need to change the serialization version?
=> fix!: Combine `ConstIntU` and `ConstIntS`

.github/change-filters.yml, .github/workflows/ci-py.yml, .github/workflows/ci-rs.yml
Cleanup PR. Centralises the file filter used by `dorny/paths-filter` when detecting changes in a single `.yml`.
=> ci: Move file change filter definitions to a file

.github/workflows/pr-title.yml
=> ci: Require BREAKING CHANGES footer in breaking PRs

.github/workflows/pr-title.yml
Don't insert github expressions directly in the bash script.
- It breaks if there are [backticks] or [quotes] inside the variable.
- It's a security issue, it allows arbitrary code injections from the PR description.
The solution is to put them into env variables first.
=> ci(pr-title): Escape variables used in bash scripts

hugr-py/src/hugr/serialization/ops.py, specification/schema/hugr_schema_strict_v1.json, specification/schema/hugr_schema_v1.json, specification/schema/testing_hugr_schema_strict_v1.json, specification/schema/testing_hugr_schema_v1.json
The existing implementation of `insert_port_types` was wrong, we can just get rid of it
=> fix: Remove insert_port_types for LoadFunction

hugr/src/hugr/rewrite/outline_cfg.rs, hugr/src/hugr/rewrite/replace.rs, hugr/src/hugr/validate/test.rs
Turns out that `assert_matches!(subject, pattern => STMT)` executes STMT and drops the result....
We have several cases where STMT returns a bool and we were expecting this to be true, but in fact assert_matches doesn't check the bool. So, change these to `=> assert_eq!`
Indeed, there was one case here where the bool was actually false - fix that assert....
=> test: fix some bad assert_matches

hugr/src/hugr/validate/test.rs
Now includes a polymorphic function that instantiates an extension op with the function's own type parameters; that function is then in turn instantiated in a Call in the main Hugr. The parameters include one of kind Extensions, which are used in the signature of the function itself.
=> test: Expand test of instantiating extension sets

hugr/src/hugr/validate/test.rs
While trying to separate out extension validation from the rest of validation, I found that the graph here was invalid! The extension error gets thrown before it starts complaining about all of the unconnected outputs.
=> test: Fix unconnected ports in extension test

hugr/src/algorithm.rs, hugr/src/algorithm/merge_bbs.rs
Any basic block with a single successor that has no other predecessors can be merged. (So long as the successor is not the exit block; nor the entry block, as that implicitly has another predecessor).
Implement via Replace (2 BBs - > one BB containing 2 DFGs, which adopt the original BB's children) and 2*InlineDFG.
Closes #561.
=> feat: merge basic blocks algorithm

hugr/src/extension.rs, hugr/src/extension/declarative/signature.rs, hugr/src/extension/declarative/types.rs, hugr/src/extension/type_def.rs
The docs say it was intended for sharing code between OpDef and TypeDef, but it was actually impl'd only by TypeDef (following earlier cleanups I think). So, simplify by removing it...(nothing here was ever `pub`)
=> refactor: Remove "trait TypeParametrised"

hugr/src/extension/prelude.rs
Closes #915 .
BREAKING CHANGE: `PANIC_OP_ID` now instantiated with expected input and output types.
=> feat!: Allow panic operation to have any input and output wires

hugr/src/algorithm/nest_cfgs.rs, hugr/src/hugr/rewrite/outline_cfg.rs
This is in preparation for moving `algorithm` out to a separate crate.
* Rewrite tests in `outline_cfg.rs` to use a single CFG, specific to that test
* Add a test where the outlined cfg has multiple incoming edges (to the same node)
* And another where there is an incoming edge and also the entry node (another implicit edge, making this illegal)
* Tidy the left-behind test code in `nest_cfg.rs`
* Now that the OutlineCfg tests don't depend, `build_cond_then_loop_cfg(bool)` is only called with `false`, so fold
* Also inline/remove a few other "helpers" whose interface contract is more confusing than helpful
* And, e.g., use `FunctionType::new_endo` (and remove now-unnecessary `type_row!`)
=> test: Reorg OutlineCfg/nest_cfgs tests so hugr doesn't depend on algorithm

.github/workflows/python-wheels.yml, .github/workflows/release-please.yml
Fixes merging release-please PRs not triggering the pypi release workflow.
This is due to workflows not triggering other workflows when using the default `GITHUB_TOKEN`.
The pypi release workflow ran when a tag matching `hugr-py-v**` was pushed by anyone. This was a bit dangerous and prone to fat-fingering.
Now the workflow is triggered either by new releases with a matching tag (as created by release-please), or by manually triggering the workflow on a tag (so we can still trigger it if needed).
This should be harder to trigger by accident.
=> ci: publish to pypi on releases or workflow_dispatch for tags

.github/CODEOWNERS, .github/workflows/release-plz.yml
This setups a restricted ownership over the changelog files, so the release PRs by `release-please` or `release-plz` have to be approved by a restricted set of people.
We can then enable auto-releases for rust (for python is already enabled).
Feel free to suggest other users to add to the list.
=> ci: Enable crates.io auto-release, but require certain people to approve the PRs

.github/workflows/ci-rs.yml, hugr/src/hugr/validate.rs
Parallelises running stable tests with `--no-features` and `-all-features`.
This should reduce the critical path latency for the required checks.
I'm not doing this for the other compiler versions, as the delay is not that critical there and splitting workers pollutes the cache.
Closes #1064.
=> ci: Improve times by splitting stable test runs

hugr/build.rs
Rust 1.80 will require pre-declaring configuration flags that we want to set via RUSTFLAGS.
See the [blog post](https://blog.rust-lang.org/2024/05/06/check-cfg.html).
Fixes #1067.
=> chore: Declare ci_run flag in build.rs

hugr/src/algorithm/const_fold.rs, hugr/src/hugr/serialize/test.rs, hugr/src/std_extensions/arithmetic/float_ops/const_fold.rs, hugr/src/std_extensions/arithmetic/float_types.rs, specification/hugr.md
Fixes #1049 .
Other solutions (custom serialization/deserialization for `ConstF64`, or custom deserializer taking "null" to NaN) are difficult or otherwise problematic, and it may actually be a good thing to disallow non-finite float constants as it can catch bugs earlier.
=> fix: Disallow non-finite values for `ConstF64`

.pre-commit-config.yaml
hugr-py has no actual tests yet, but we should start running pytest here before it does.
=> chore: Run pytest on pre-commit check

hugr/src/types/signature.rs, hugr/src/types/type_row.rs
TypeRow is not just used for node input/output signatures, but also for elements of tuples/sums, and FunctionTypes that are not part of Nodes. So, using Port to index into it seems odd...
BREAKING CHANGE: get() and get_mut() now take only usize, so must call PortIndex::index() on the argument first
=> refactor!: No Ports in TypeRow

hugr-py/src/hugr/serialization/ops.py, hugr-py/src/hugr/serialization/serial_hugr.py, hugr-py/src/hugr/serialization/tys.py, hugr-py/tests/serialization/test_basic.py
add a test that triggers the warnings
https://docs.pydantic.dev/2.7/migration/#changes-to-config
=> fix(py):  get rid of pydantic config deprecation warnings

release-please-config.json
This setting should make release-please create it's PRs as draft requests (to avoid annoying reviewers unnecessarily), but it doesn't seem to have worked https://github.com/CQCL/hugr/pull/1092
The config json schema seemed to validate this as a global option, but it seems the value is not picked from there :/
This change moves the "use a draft PR" option to the project-specific section.
=> ci: Fix release-please not creating draft PRs

hugr/Cargo.toml, hugr/src/cli.rs, hugr/src/lib.rs, hugr/src/main.rs, hugr/tests/cli.rs
Closes #1095
currently validates against std extensions 
can read from stdin with `echo "<json>" | hugr -` 
binary depends on optional feature to limit dependencies, but not put in sub crate to allow `cargo install hugr`
add integration testing of binary behaviour
based on https://docs.rs/assert_cmd/2.0.14/assert_cmd/cmd/struct.Command.html#method.write_stdin
=> feat: hugr binary cli tool

release-plz.toml
This is mainly to avoid fails on CI due to `hugr-passes` trying to use the published `hugr 0.4.0`
https://github.com/CQCL/hugr/actions/runs/9208802531/job/25331815962#step:4:325
=> ci: Disable release-plz publishing hugr-passes for now

.github/workflows/notify-coverage.yml
Reduces the frequency of the slack notification from daily to once a week (Mondays at 4h).
Closes #1106
=> ci: Notify coverage changes only once a week

hugr/src/hugr/validate.rs, hugr/src/hugr/validate/test.rs, specification/hugr.md
Closes #936 
Test for `ext` edges only in this PR. (Would be good to have one for `dom` edges too but that can follow.)
BREAKING CHANGE: Hugr's with nonlocal ("Inter-Graph") edges that enter FuncDefns will now fail validation
=> feat!: Disallow nonlocal value edges into FuncDefn's

release-plz.toml
I set an invalid flag for release-plz...
https://release-plz.ieni.dev/docs/config#the-git_release_enable-field
This triggered an error in CI: https://github.com/CQCL/hugr/actions/runs/9270279819/job/25502921479#step:4:216
=> ci: Fix release-plz field config

release-plz.toml
> you can't create a git release without a git tag
So that was a lie. The releases [are still created](https://github.com/CQCL/hugr/actions/runs/9271742453/job/25507885562#step:4:281).
#1119 shouldn't have dropped the `git_release_enable` lines.
=> ci: fix the release-plz fix

.github/workflows/ci-rs.yml, hugr-core/src/hugr/hugrmut.rs
Nightly rust tests are failing, seemingly due to [rust-lang/rust#125474](https://github.com/rust-lang/rust/issues/125474).
This PR fixes the toolchain to the last working nightly until the problem is resolved.
CI fail: https://github.com/CQCL/hugr/actions/runs/9281876942/job/25538729650#step:6:856
=> ci: Pin nightly rust version

.github/workflows/ci-rs.yml
The `benches` CI job likes to run even when it is not required
https://github.com/CQCL/hugr/actions/runs/9270412094
It seems the `if` statement is wrong. *Why* is it wrong escapes me.
Here I'm just copying the one from the other conditional tests, which we know works.
drive-by: Add a name to make clear it is not _running_ the benchmarks.
=> ci: Stop `benches` ci job from always running

.pre-commit-config.yaml
pre-commit started failing to parse the `cargo doc` command;
```
cargo doc................................................................Failed
- hook id: cargo-doc
- exit code: 1
Executable `RUSTDOCFLAGS=-Dwarnings` not found
```
it may be related to a version update.
The solution, as we've done in other steps, is to wrap everything as a `sh -c` command.
=> ci: Wrap failing pre-commit command

release-plz.toml
Now that the crates are published in crates.io, allow release-plz to push updates.
I updated the token to allow pushing updates to `hugr-*` crates.
=> ci: auto-release the new crates

Cargo.toml
All sub crates will be targeted 
specifically now `cargo run` will hit the cli binary
=> refactor: remove `default_members` field in workspace Cargo.toml

hugr-core/src/extension/infer/test.rs, hugr-core/src/hugr/validate.rs, hugr-passes/src/merge_bbs.rs
This was missed in prior validation, and there are a few instances in our codebase, so fix them.
I also had to comment out a failing merge_bbs test, see #1143
BREAKING CHANGE: BasicBlocks with multiple successors from the same outport will now fail to validate (as they should!)
=> fix!: Validate that control-flow outputs have exactly one successor

Cargo.toml, hugr-passes/src/merge_bbs.rs
Updates `portgraph` to include the fix in https://github.com/CQCL/portgraph/pull/132.
Uncomments the previously-failing mentioned in #1143.
Fixes #1143.
=> fix: merge_bbs creating too many self-loop edges

.github/change-filters.yml
The clever `hugr-*` filter also catches changes from `hugr-py` -.-
=> ci: Fix rust checks running for python-only changes

hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_exceptions.py, hugr-py/src/hugr/_hugr.py, hugr-py/tests/test_hugr_build.py
uses a slightly dodgy -1 offset hack
hack currently means if you query the hugr for outgoing edges the state order edges are ignored.
=> feat(hugr-py): automatically add state order edges for inter-graph edges

hugr-core/src/hugr.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/sibling.rs
Add a `extract_hugr` method to extract regions into owned `Hugr`s.
The implementation is short-circuited for `Hugr` to avoid unnecessary clones.
Closes #1171.
=> feat: `HugrView::extract_hugr` to extract regions into owned hugrs.

hugr-py/src/hugr/_exceptions.py, hugr-py/src/hugr/_hugr.py, hugr-py/tests/test_hugr_build.py
Could instead bite the bullet and iterate through every node for calculating the children of a node, but this implementation seems like a decent code complexity/runtime balance
Closes #1159
=> feat(hugr-py): store children in node weight

.github/workflows/ci-rs.yml, hugr-core/src/builder/tail_loop.rs
The ICE on nightly got fixed with a revert commit
https://github.com/rust-lang/rust/commit/98489f2487465f3765e5dd28d7305ebfd40f0865
=> ci: Unpin nightly

hugr-core/src/hugr/views/sibling_subgraph.rs
Fixes #1175 
Signatures have three components:
- The input type row
- The output type row
- The set of extensions used by the local operations
Many interesting replacements in a graph changes the latter, but `SiblingSubgraph::create_simple_replacement` required the signatures to match exactly.
=> fix: Do not require matching extension_reqs when creating a replacement

hugr-core/src/hugr/views/sibling_subgraph.rs
Adds some context to the errors.
BREAKING CHANGE: Added more attributes to the `InvalidReplacement` and `InvalidSubgraph` error enums.
=> feat!: Make the rewrite errors more useful

.github/workflows/python-wheels.yml
Ported from https://github.com/CQCL/tket2/pull/394
The if condition that decided whether to publish to pypi always evaluate to true -.-
Passing (skipped) CI:
https://github.com/CQCL/hugr/actions/runs/9419287281/job/25948715096
=> fix: pypi publish running unconditionally

hugr-py/src/hugr/serialization/tys.py
I was originally suspicious why this contained a PolyFuncType not a FunctionType, but AFAICS this isn't used, turns out that it doesn't change what goes into `specification/schema/` at all...
BREAKING CHANGE: the Signature class is gone, but it's not clear how or why you might have been using it...
=> refactor!: Remove "Signature" from hugr-py

hugr-core/src/builder/circuit.rs
Removes the conditional test skip introduced in https://github.com/CQCL/hugr/pull/1168#issuecomment-2154936867, now that #1142 is merged.
=> chore: Unskip test now that input_extensions is no more

hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_hugr.py, hugr-py/src/hugr/_ops.py, hugr-py/src/hugr/_tys.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/src/hugr/serialization/tys.py, hugr-py/src/hugr/utils.py, hugr-py/tests/test_hugr_build.py, poetry.lock, specification/schema/hugr_schema_strict_v1.json, specification/schema/hugr_schema_v1.json, specification/schema/testing_hugr_schema_strict_v1.json, specification/schema/testing_hugr_schema_v1.json
Closes #1172
Changes in first commit.
Note second commit is just running the schema update, which appears to be trivial and non-breaking. 
Coverage not great because this hierarchy is comprehensive (unlike the Ops) but not all are tested. Deemed not worth adding a load of boiler plate tests for now.
=> feat(hugr-py): define type hierarchy separate from serialized

hugr-cli/tests/cli.rs, hugr-core/src/ops/constant/custom.rs, justfile
The unsoundness check was [failing on `main`](https://github.com/CQCL/hugr/actions/runs/9512637937/job/26221038735).
- Skips the hugr-cli tests when running miri, as it does not support calling external processes.
- Move `impl Arbitrary for CustomSerialized` out of a block of miri-skipped tests.
- Adds a `just miri` command with the correct flags to get proptests working with miri.
CI run: https://github.com/CQCL/hugr/actions/runs/9518163988/job/26238422543
=> chore: Fix failing unsoundness checks

hugr-core/src/hugr/rewrite/simple_replace.rs
=> fix: SimpleReplacement panic on multiports

hugr-py/src/hugr/_cfg.py, hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_exceptions.py, hugr-py/src/hugr/_hugr.py, hugr-py/src/hugr/_ops.py, hugr-py/src/hugr/_tys.py, hugr-py/tests/test_cfg.py, hugr-py/tests/test_hugr_build.py
=> feat(hugr-py): CFG builder

hugr-py/src/hugr/_cfg.py, hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_hugr.py, hugr-py/tests/test_cfg.py, hugr-py/tests/test_hugr_build.py
makes compositional building much easier, builders are their nodes
=> feat(hugr-py): ToNode interface to treat builders as nodes

hugr-py/src/hugr/_cfg.py, hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_hugr.py
this exists as a tension between global/compositional building. Inter-graph edges necessitate global, all-at-once building for some cases. ~These update functions are required when inserting graphs in to other ones~ Instead replaced with `new_nested` classmethods inspired by https://github.com/CQCL/hugr/pull/1192#discussion_r1642486028
=> refactor(hugr-py): simplify hugr replacement

hugr-py/src/hugr/_cfg.py, hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_exceptions.py, hugr-py/src/hugr/_hugr.py, hugr-py/src/hugr/_ops.py, hugr-py/src/hugr/_tys.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/tests/test_cfg.py, hugr-py/tests/test_hugr_build.py
Closes #1198
- ops have to report their signature, but may be initialised incomplete
- dataflow ops have hooks to update themselves based on the types flowing in to them
- parent ops can update themselves based on the types flowing out of them
- Tag needs to know all possible variants, can't infer from input types
- calculate cfg outputs by looking at output types of blocks that connect to exit block
reviewing commit by commit might be easier
=> feat(hugr-py): only require input type annotations when building

hugr-py/src/hugr/_ops.py
avoids some bugs I kept making because of name similarities
=> refactor(hugr-py): common up a null check

hugr-py/src/hugr/_cfg.py, hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_hugr.py, hugr-py/src/hugr/_ops.py, hugr-py/src/hugr/_val.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/src/hugr/serialization/serial_hugr.py, hugr-py/tests/test_cfg.py, hugr-py/tests/test_hugr_build.py
=> feat(hugr-py): add values and constants

hugr-py/src/hugr/_cfg.py, hugr-py/src/hugr/_cond_loop.py, hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_ops.py, hugr-py/src/hugr/_tys.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/tests/test_cfg.py, hugr-py/tests/test_cond_loop.py, hugr-py/tests/test_hugr_build.py
Closes #1204 
Including a short hand for if/else style conditionals
Includes some other simplifications and refactors, reccommend going commit by commit
=> feat(hugr-py): add builders for Conditional and TailLoop

hugr-py/src/hugr/_cfg.py, hugr-py/src/hugr/_cond_loop.py, hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_function.py, hugr-py/src/hugr/_hugr.py, hugr-py/src/hugr/_node_port.py, hugr-py/src/hugr/_ops.py, hugr-py/src/hugr/_tys.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/tests/test_hugr_build.py
Closes #1211 
review commits separately, first is just a trivial refactor moving code in to its own file
=> feat(hugr-py): builder for function definition/declaration and call

hugr-py/src/hugr/_dfg.py, hugr-py/src/hugr/_function.py, hugr-py/src/hugr/_ops.py, hugr-py/src/hugr/_tys.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/tests/test_hugr_build.py
all ops covered!
commits are independent 
Closes #1213
=> feat(hugr-py): add CallIndirect, LoadFunction, Lift, Alias

hugr-core/src/extension.rs, hugr-core/src/hugr.rs, hugr-core/src/hugr/validate.rs
* Add an ExtensionId TO_BE_INFERRED
* On Case, Cfg, Conditional, DataflowBlock, Dfg, TailLoop, `Hugr::infer_extensions` replaces TO_BE_INFERRED with the smallest set of ExtensionIds that's correct wrt. its child nodes (i.e., the union of the child node deltas). If there are other ExtensionIds alongside TO_BE_INFERRED these will be kept (allowing a "lower bound" to be specified for individual nodes)
* `Hugr::infer_extensions` also takes a `remove: bool` which, if true, modifies deltas of the same OpTypes that do *not* have TO_BE_INFERRED, by removing ExtensionIds. (Thus, non-inferred deltas act as upper bounds).
Relates to #640 but does not address the builder where this should be the default behaviour.
BREAKING CHANGE: ExtensionError moved from hugr::validate to hugr; …
=> feat!: Infer extension deltas for Case, Cfg, Conditional, DataflowBlock, Dfg, TailLoop 

hugr-core/src/builder.rs, hugr-core/src/builder/build_traits.rs, hugr-core/src/builder/cfg.rs, hugr-core/src/builder/conditional.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/builder/module.rs, hugr-core/src/builder/tail_loop.rs, hugr-core/src/hugr/rewrite/consts.rs, hugr-core/src/hugr/rewrite/outline_cfg.rs, hugr-core/src/hugr/rewrite/simple_replace.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/sibling.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/hugr/views/tests.rs
Currently FunctionBuilder::new and the `define_function` method both take a PolyFuncType; this PR changes that to a more-general `impl Into<PolyFuncType>`.
BREAKING CHANGE: clients calling these methods with a FunctionType's `.into()` will fail to compile with a "type annotations required" error, which can be fixed by deleting the `.into()`.
=> refactor!: FunctionBuilder takes impl Into<PolyFuncType>

hugr-core/src/hugr/validate/test.rs, hugr-core/src/ops/validate.rs, resources/test/issue-1189.json
Closes #1189
Failing example generated using hugr-py
=> fix: cfg not validating entry/exit types

hugr-core/src/builder.rs, hugr-core/src/builder/build_traits.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/hugr/rewrite/inline_dfg.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views/tests.rs, hugr-core/src/ops/constant.rs, hugr-passes/src/const_fold.rs
* Add `builder::ft2` that takes 2 `Into<Typerow>`s, and builds a FunctionType with extension delta TO_BE_INFERRED
* And `builder::ft1` that takes a single `Into<TypeRow>` and makes an endomorphic FunctionType similarly
* Use these to update a bunch of tests made worse by earlier PRs (i.e. these now use inference rather than manually specifying deltas)
* Correct some doc comments....
* ....and add a `dfg_builder_endo` method that was hinted at by one of the incorrect doc comments, and that infers the delta.
=> feat: Helper functions for requesting inference, use with builder in tests

hugr-py/src/hugr/dfg.py, hugr-py/src/hugr/exceptions.py, hugr-py/src/hugr/hugr.py, hugr-py/src/hugr/ops.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/src/hugr/val.py, hugr-py/tests/conftest.py, hugr-py/tests/test_hugr_build.py
go commit by commit
mostly things like making methods/classes internal
=> refactor: cleanups from writing docstring

hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/sibling.rs
=> fix: `extract_hugr` not removing root node ports

hugr-cli/README.md, hugr-core/CHANGELOG.md, hugr-core/src/extension/op_def.rs, hugr-core/src/hugr.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/ops/constant.rs, hugr-core/src/ops/constant/custom.rs, hugr-core/src/types/type_param.rs, hugr-py/CHANGELOG.md, hugr-py/src/hugr/ops.py, hugr-py/src/hugr/tys.py, hugr-py/src/hugr/utils.py, hugr-py/src/hugr/val.py, hugr/CHANGELOG.md, specification/hugr.md
Did: `git grep -l -i 'serialis' | xargs sed -i 's/erialis/erializ/g'`
The "-ize" spelling is already used much more often, so let's be consistent.
=> style: Change "serialise" etc to "serialize" etc.

.github/workflows/docs.yml, hugr-py/docs/_static/_redirect.html, hugr-py/docs/api-docs/_templates/versioning.html, hugr-py/docs/api-docs/conf.py, hugr-py/docs/build.sh, hugr-py/poetry.lock, hugr-py/pyproject.toml
Closes #1215
Will build and publish for main branch + every tagged version with docs (currently none), using [sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/index.html)
With multiple versions looks like:
Will follow-up with a PR adding links to readme etc. once I've seen the workflow succeeds.
=> docs(hugr-py): build and publish docs

.github/workflows/docs.yml
Need full history to build docs for old versions
If this becomes too heavy in the future we can optimise
=> chore: docs fetch all tags

Cargo.toml, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__mmd_cfg.snap, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__mmd_dfg.snap, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__mmd_empty_dfg.snap
Includes the fix in https://github.com/CQCL/portgraph/pull/139 that closes #1197
=> chore: Update portgraph to `0.12.2`

hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/sibling.rs, hugr-core/src/ops/constant.rs
Closes #957
- `mono_fn_type` now enforces function value monomorphism
- get_df_function_type -> inner_function_type so it matches the actual op function being called more obviously.
- The culprit `get_function_type` changed to `poly_func_type` which _only_ reports polymorphic type from func defn/decl
BREAKING CHANGE: 
- rename `get_df_function_type` to `inner_function_type`
- `get_function_type` replaced with `poly_func_type` which only reports polymorphic function type for Func(Defn/Decl) rooted HUGRs
=> refactor!: rename `HugrView` function type methods + simplify behaviour

hugr-core/src/extension/simple_op.rs, hugr-core/src/std_extensions/arithmetic/conversions.rs, hugr-core/src/std_extensions/arithmetic/float_ops.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-core/src/std_extensions/logic.rs
Closes #1241 
Used to ensure `try_from_name` only succeeds when the extension is correct
BREAKING CHANGE:
- `MakeOpDef` trait has new required `extension` method.
- `try_from_name` takes the OpDef extension and checks it
=> feat!: `MakeOpDef` has new `extension` method.

hugr-core/src/hugr/serialize.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/ops/module.rs
Fixes #1270 without keeping the unused `input_extensions` field. 
BREAKING CHANGE: `ops::Module` no longer unit struct, must be constructed with `new()` or `default()`
=> fix!: `ops::Module` now empty struct rather than unit struct

hugr-py/src/hugr/cfg.py, hugr-py/src/hugr/cond_loop.py, hugr-py/src/hugr/dfg.py, hugr-py/tests/test_cfg.py, hugr-py/tests/test_cond_loop.py, hugr-py/tests/test_hugr_build.py
Currently the context doesn't do anything much, just offers syntactical nesting to make it easier to write HUGRs
The exception being Conditional, where we use the exit as an opportunity to check all cases have been built.
This can be extended to other cases (e.g. ensure expected  outputs have been set when exiting a dfg).
Closes #1243
=> feat(hugr-py): context manager style nested building

hugr-py/src/hugr/ops.py, hugr-py/tests/conftest.py
Makes singletons like `Measure = MeasureDef()` safer, as the instance isn't going to get mutated between uses
=> refactor(hugr-py): freeze custom ops

hugr-py/src/hugr/dfg.py, hugr-py/src/hugr/tracked_dfg.py, hugr-py/tests/test_tracked_dfg.py
Both `add` and `append`  take commands, but `append` allows commands with indices in. We can therefore replace `append` with an `add` override. Makes for a more consistent interface.
Allows `extend` to be defined on Dfg too.
BREAKING CHANGE:
- `TrackedDfg.append` removed, use `add` instead.
- `extend` now takes `*args` rather than an iterable.
=> feat(hugr-py)!: Override `add` rather than `append` + `extend` on all `_DfBase`

hugr-py/src/hugr/std/__init__.py, hugr-py/src/hugr/std/float.py, hugr-py/src/hugr/std/int.py, hugr-py/src/hugr/std/logic.py, hugr-py/tests/conftest.py, hugr-py/tests/test_cfg.py, hugr-py/tests/test_cond_loop.py, hugr-py/tests/test_hugr_build.py, hugr-py/tests/test_tracked_dfg.py
Not complete, see #1287
Quantum operations left in tests as they are not part of std extensions set (maybe they should be...?)
=> feat(hugr-py): move std extension types/ops in to `std` module

hugr-py/src/hugr/ops.py, hugr-py/src/hugr/std/int.py, hugr-py/src/hugr/std/logic.py, hugr-py/tests/conftest.py, hugr-py/tests/test_custom.py
Downstream users can implement this protocol to use their own convenience classes. Typically a use wants to implement:
- `to_custom`
- `__call__` to provide a useful calling signature.
- `from_custom` if different instances of the type correspond to different ops (non-singleton).
Replace existing custom operation types with this.
Follow ups:
- Similar thing for custom types.
- Optional: allow these types to register themselves with `serialization.ops.CustomOp` so they can be deserialized directly.
=> feat(hugr-py): `AsCustomOp` protocol for user-defined custom op types.

.github/workflows/release-please.yml
The repository changed names.
This should include the fix in [release-please#2241](https://www.github.com/googleapis/release-please/pull/2241), which was causing the release PRs to be open as non-draft.
=> ci: Update deprecated `release-please` action

hugr-core/src/hugr/views/sibling_subgraph.rs
=> fix: NonConvex error on SiblingSubgraph::from_nodes with multiports

hugr-core/src/builder.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/hugr/rewrite/inline_dfg.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views/tests.rs, hugr-core/src/ops/constant.rs, hugr-passes/src/const_fold.rs
In response to [this comment](https://github.com/CQCL/hugr/pull/1226#pullrequestreview-2158309800) that "the builder...helpers are quite confusing", this offers a better compromise between brevity and readability, i.e. slightly more of the latter.
BREAKING CHANGE: builder::ft1 is now `builder::endo_ft`, similarly `ft2` is new `inout_ft`
=> refactor!: Rename builder helpers: ft1->endo_ft, ft2->inout_ft

hugr-passes/src/force_order.rs
I don't think "dominance" is what you want here - `n1` dominates `n2` if *all* paths from the root to `n2` go via `n1`, I don't think this is really relevant. (I also found it a little hard to understand what guarantee we did offer given the explicit disclaimer....)
Hopefully this is less ambiguous, although I suspect it is somewhat redundant/repetitive, maybe it could be improved further...
=> docs: attempt to correct force_order docs

hugr-py/src/hugr/std/float.py, hugr-py/src/hugr/std/int.py, hugr-py/src/hugr/std/logic.py, hugr-py/src/hugr/tys.py, hugr-py/tests/conftest.py
=> fix(hugr-py): ops require their own extensions

.github/change-filters.yml, .github/workflows/ci-py.yml
A python test failure didn't cause the required checks to fail...
drive-by: Add workflow files to the CI change filters, so modifications trigger the checks.
=> ci: Check python test result on required checks check

hugr-py/tests/conftest.py
Prints the error returned by `hugr-cli` when something fails, so we get better feedback.
Before:
```
subprocess.CalledProcessError: Command '['/Users/agustinborgna/src/hugr/target/debug/hugr', '-']' returned non-zero exit status 1.
```
After:
```
RuntimeError: Error validating HUGR: Parent node Node(0) has extensions [] that are too restrictive for child node Node(5), they must include child extensions [IdentList("quantum.tket2")]
```
=> test: Print `hugr-cli`'s errors on python tests

hugr-core/src/hugr/rewrite/simple_replace.rs
Fixes #1323
This fix generalises the one from #1191.
SimpleReplace was too eager in disconnecting/connecting edges to the replacement graph, and that caused issues when querying the neighbours of multiports.
This gets resolved by delaying all new connections to the replacement until after we have computed all of them.
We don't need to do explicit disconnections to the replaced subgraph, since the nodes get removed anyway.
=> fix: Panic on `SimpleReplace` with multiports

hugr-core/src/builder/handle.rs, hugr-core/src/builder/tail_loop.rs, hugr-core/src/hugr/validate/test.rs
DFGWrapper handles incorrectly were using internal dfg output number as the outputs from the container node. Fixed for function, case and tailloop. Also fixed a test that relied on this incorrect behaviour.
Closes #1257
=> fix: dfg wrapper build handles incorrect output wire numbers

hugr-core/src/extension/declarative/ops.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/ops/constant.rs, hugr-core/src/ops/constant/custom.rs, hugr-core/src/proptest.rs
Closes #1048
BREAKING CHANGE: use `serde_json::Value` rather than `serde_yaml::Value` in `CustomSerialized`, `OpDef`, `OperationDeclaration`
=> refactor!: use JSON rather than YAML in opaque fields.

hugr-py/src/hugr/cfg.py, hugr-py/src/hugr/dfg.py, hugr-py/src/hugr/exceptions.py, hugr-py/src/hugr/hugr.py, hugr-py/src/hugr/node_port.py, hugr-py/src/hugr/ops.py, hugr-py/src/hugr/serialization/ops.py, hugr-py/src/hugr/serialization/serial_hugr.py
Small refactor adding a type alias for node indices and port offsets.
=> refactor(py): `NodeIdx` and `PortOffset` aliases for `int`

hugr-core/Cargo.toml, hugr-core/README.md, hugr-core/src/extension.rs, hugr-core/src/utils.rs, hugr/Cargo.toml, hugr/README.md
Closes #1340 
BREAKING CHANGE: `hugr::extension::declarative` now only available with "declarative" feature
=> refactor(hugr-core)!: declarative module behind optional feature flag

hugr-core/src/extension/simple_op.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-core/src/std_extensions/logic.rs
When there are custom types standing in for opdefs and concrete versions of those ops, implementing these simple traits (how to instantiate one from the other) allows them to be loaded from `CustomOp`.
Avoids some common boilerplate: https://github.com/CQCL/tket2/blob/d9a713c068077dfea8c12301c1973575ddc8ca2c/tket2-hseries/src/extension/result.rs#L384 (in other extensions there too)
Used in #1337
=> feat(hugr-core): `HasDef` and `HasConcrete` traits for def/concrete op design pattern

hugr-core/src/std_extensions.rs, hugr-core/src/std_extensions/ptr.rs
ptr<T> type and new, read and write operations.
=> feat(hugr-core): Add pointer standard extension

hugr-core/src/hugr/views/sibling_subgraph.rs
The signature computation for a `SiblingSubgraph` takes the union of the nodes' extensions. This didn't contemplate non-dataflow nodes like constants, and caused a runtime panic if one was present.
Most of the diff is adding a constant node in the tests. 
This is a fix for https://github.com/CQCL/tket2/issues/507
=> fix: Sibling extension panics while computing signature with non-dataflow nodes

hugr-cli/CHANGELOG.md, hugr-cli/Cargo.toml, hugr-core/CHANGELOG.md, hugr-core/Cargo.toml, hugr-core/src/builder/handle.rs, hugr-core/src/builder/tail_loop.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-passes/CHANGELOG.md, hugr-passes/Cargo.toml, hugr/CHANGELOG.md, hugr/Cargo.toml
This is a patch release including only some non-breaking changes since 0.9.0.
* `hugr`: 0.9.0 -> 0.9.1
* `hugr-core`: 0.6.0 -> 0.6.1
* `hugr-passes`: 0.6.0 -> 0.6.1
* `hugr-cli`: 0.2.0 -> 0.2.1
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- Dfg wrapper build handles incorrect output wire numbers ([#1332](https://github.com/CQCL/hugr/pull/1332))
- Sibling extension panics while computing signature with non-dataflow nodes ([#1350](https://github.com/CQCL/hugr/pull/1350))
</blockquote>
<blockquote>
- Dfg wrapper build handles incorrect output wire numbers ([#1332](https://github.com/CQCL/hugr/pull/1332))
- Sibling extension panics while computing signature with non-dataflow nodes ([#1350](https://github.com/CQCL/hugr/pull/1350))
</blockquote>
<blockquote>
Nothing here. …
=> chore(rs): hugr 0.9.1 patch release

DEVELOPMENT.md
Updates the instructions to use `release-plz` locally. This is easier and less error prone, since it can reuse the configuration used for normal releases.
=> docs: Update instructions for doing patch releases

specification/hugr.md
Closes #248 
There are still some visual glitches, but it should be more readable now.
Adds two invisible order edges to the input nodes, changing this
```mermaid
flowchart
subgraph CFG
direction TB
subgraph Entry
direction TB
EntryIn["Input"] -- "P" --> Entry_["P?1"]
Entry_ -- "[()|(P)]" --> EntryOut["Output"]
F
end
subgraph BB1
direction TB
BB1In["Input"]
BB1_["Const"] -- "[()]" --> BB1Out["Output"]
G -- "angle" --> BB1Out
end
subgraph BB2
direction TB
BB2In["Input"] -- "P" --> H -- "P" --> BB2_["P?2"]
BB2_ -- "[()|()]" --> BB2Out["Output"]
end
subgraph BB3
direction TB
BB3In["Input"]
BB3_["Const"] -- "[()]" --> BB3Out["Output"]
C -- "angle" --> BB3Out
end
subgraph Exit
end
Entry -- "0" --> BB1
Entry -- "1" --> BB2
BB2 -- "0" --> BB1
BB2 -- "1" --> BB3
BB1 -- "0" --> Exit
BB3 -- "0" --> …
```
=> chore(spec): Clean up non-local edges CFG example

hugr-core/Cargo.toml, hugr-core/src/extension.rs, hugr-core/src/extension/declarative.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/extension/simple_op.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/std_extensions/arithmetic/conversions.rs, hugr-core/src/std_extensions/arithmetic/float_ops.rs, hugr-core/src/std_extensions/arithmetic/float_types.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-core/src/std_extensions/arithmetic/int_types.rs, hugr-core/src/std_extensions/collections.rs, hugr-core/src/std_extensions/logic.rs, hugr-core/src/std_extensions/ptr.rs, hugr-core/src/types/poly_func.rs, hugr-core/src/utils.rs, hugr-passes/src/merge_bbs.rs, hugr/src/lib.rs
Closes #1357 
BREAKING CHANGE: `Extension::new` now requires a `Version` argument. `Extension::new_with_reqs` replaced with `with_reqs` which takes `self` (chain with `new`).
=> feat!: `Extension` requires a version

Cargo.toml, hugr-core/build.rs
Rust 1.80 [just dropped](https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html), adding a lint option that allows us to avoid the `build.rs` definition we had to add for https://github.com/CQCL/hugr/issues/1067.
(The nightly lint got updated before hitting beta, so there shouldn't be compatibility problems there).
~~Depends on #1355~~
=> chore: Replace `build.rs` with lint config in Cargo.toml

.github/workflows/ci-py.yml, .github/workflows/ci-rs.yml
CI was running tests on `{MSRV, beta, nightly}` first, and only then running tests with coverage instrumentation on nightly.
Since those tests are not on the critical path for the required checks, we can run the nightly tests directly with instrumentation on the first pass, shaving ~2mins from the commit-to-codecov report delay.
I'm only doing this for rust, as the python tests _are_ in the required checks sets and we don't want to slow down those.
drive-by: The python tests job had the same name as the linting job.
=> ci: Reduce rust coverage report delay

.github/workflows/ci-py.yml, hugr-cli/src/extensions.rs, hugr-cli/src/lib.rs, hugr-cli/src/main.rs, hugr-cli/tests/gen_extensions.rs, hugr-core/src/extension.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/extension/type_def.rs, justfile, specification/std_extensions/arithmetic/conversions.json, specification/std_extensions/arithmetic/float.json, specification/std_extensions/arithmetic/float/types.json, specification/std_extensions/arithmetic/int.json, specification/std_extensions/arithmetic/int/types.json, specification/std_extensions/logic.json, specification/std_extensions/prelude.json, specification/std_extensions/ptr.json
Closes #1228 
Add cli for generating serialised extensions, and justfile/CI for checking checked in definitions match. 
Switched from `HashMap` to `BTreeMap` in `Extension` to ensure serialization happens in alphabetical order.
=> feat: serialised standard extensions

.github/workflows/pr-title.yml
It seems that skipping reusable workflow jobs causes inconsistent check names between `pull_request_target` and `merge_group`.
For the non-skipped PR runs we get a `local_job/remote_job` name,
but the skipped jobs in the merge queue are just called `local_job`.... (even if skipped in the called workflow instead of locally).
I updated the reusable workflow to skip individual steps instead of the whole job, so now we shouldn't have to deal with that inconsistency.
I will need to update the required check name to `local/remote`
=> ci: Fix pr-title not running

release-plz.toml
Stops releases from being created by new packages pushed to `main`.
https://release-plz.ieni.dev/docs/config#the-release_always-field
This saves us from having to temporarily configure `git_tag_enable` and `git_release_enable` for each crate. https://github.com/CQCL/tket2/pull/519/commits/73d6e651c7cebc6758ac7957a6ff9c7aee1f9419
Copied from https://github.com/CQCL/tket2/pull/524
=> chore: Only release-plz after release PRs

hugr-py/src/hugr/dfg.py, hugr-py/src/hugr/function.py
Move `define_function` and `add_alias_defn` from `Module` to a common root for both it and `DFG`.
Move both `add_const` definitions to that common base.
I had to move `Function` to `dfg.py` due to circular deps, but I added a reexport to avoid breaking changes.
=> feat(hugr-py): Allow defining functions, consts, and aliases inside DFGs

hugr-core/src/ops/constant/custom.rs
This is just explaining existing behaviour, but I think it's important to explain that we are not expecting the equivalent of `Eq` on a structure that could be just an `f64`....
This does constrain impls to be symmetric and transitive, but all current ones are, and I couldn't think of any... (indeed, "either Eq or always return false" would describe all current impls, and this is still significantly more permissive than that.)
=> docs: Clarify CustomConst::equal_consts

hugr-py/src/hugr/hugr.py, hugr-py/tests/test_hugr_build.py
`Hugr` is a `Mapping[Node, NodeData]`, so its `__iter__` should return a list of `Node`s, but it was returning a list of node data with `None` holes
=> fix(py): `Hugr.__iter__` returning `NodeData | None` instead of `Node`s

hugr-py/src/hugr/dfg.py
Instead of always defining constants/functions/aliases at the root of the hugr,
defaults to the current container when using a dataflow builder, adds parameters to override it.
=> feat: Define `Const` inline by default, and add a parameter to change the parent

hugr-py/src/hugr/cfg.py, hugr-py/src/hugr/cond_loop.py, hugr-py/src/hugr/dfg.py, hugr-py/src/hugr/hugr.py
Updates the parent node with the output port count as soon as a builder knows its output.
This lets us do things like
```python
dfg = Dfg(tys.Bool)
dfg.set_outputs(*dfg.inputs())
wires: list[Wire] = list(dfg)
```
=> feat(py): Set node output# for dfgs and cfgs

hugr-core/src/builder/build_traits.rs, hugr-core/src/hugr/views/root_checked.rs, hugr-core/src/ops/controlflow.rs, hugr-core/src/ops/handle.rs, hugr-core/src/ops/tag.rs, hugr-core/src/ops/validate.rs, hugr-passes/src/force_order.rs
The optags for basic blocks where defined as
```mermaid
graph TD
classDef transparent fill:#0000,stroke:#0000
a[...]:::transparent-->DataflowParent
b[...]:::transparent-->ControlFlowChild
DataflowParent --> BasicBlock
ControlFlowChild --> BasicBlock
BasicBlock --> BasicBlockExit
```
notice that `BasicBlockExit` was a descendant from `DataflowParent`. This caused errors on code that checked for the tag, such as the [`force_order` pass](https://github.com/CQCL/hugr/blob/e485a23e0cb73b0070e5d6f3374f6de16f545d04/hugr-passes/src/force_order.rs#L58-L59).
This PR changes the hierarchy to
```mermaid
graph TD
classDef transparent fill:#0000,stroke:#0000
a[...]:::transparent-->DataflowParent
b[...]:::transparent-->ControlFlowChild
DataflowParent --> DataflowBlock
ControlFlowChild --> BasicBlockExit …
```
=> fix: BasicBlockExits should not be `OpTag::DataflowParent`

hugr-py/docs/api-docs/conf.py
=> docs(hugr-py): expand toctree

hugr-py/src/hugr/cond_loop.py, hugr-py/src/hugr/node_port.py
Missed this in #1400
drive-by: Improve the error message when a node does not have the output count set.
=> fix(py): Set output cont for Conditionals

hugr-core/src/hugr/validate.rs, hugr-core/src/ops/custom.rs
Prints the node and operation in the error message.
Before:
```console
$ hugr validate test.hugr
Error validating HUGR: Type arguments of node did not match params declared by definition: Wrong number of type arguments: 1 vs expected 0 declared type parameters
```
After:
```console
$ hugr validate test.hugr
Error validating HUGR: Error in signature of operation 'Not' in Node(27): Type arguments of node did not match params declared by definition: Wrong number of type arguments: 1 vs expected 0 declared type parameters
```
=> feat: Improve error message on failed custom op validation

hugr-py/src/hugr/std/int.py
- Adds an `int_tv` method to create parametric integer types
- Adds a `width` member to `IntVal`, so we can define constants for other integer widths
=> feat(py): Parametric int type helper, and arbitrary width int constants

hugr-py/src/hugr/tys.py, hugr-py/tests/test_tys.py
`Sum`, `Tuple` and `UnitSum` can represent the same type, but the equality fn checked the specific subclasses.
=> fix: Equality check between `Sum` types

hugr-py/src/hugr/serialization/ops.py, hugr-py/src/hugr/std/float.py, hugr-py/src/hugr/std/int.py, hugr-py/tests/conftest.py, hugr-py/tests/test_cfg.py
Fixes #1424 
I updated the roundtrip validation to compare decoded jsons rather than strings.
The values were manually compared against a rust serialization output. We cannot do better without python-side extension loading.
=> fix(py): Invalid serialization of float and int constants

hugr-py/src/hugr/dfg.py, hugr-py/src/hugr/function.py, hugr-py/src/hugr/hugr.py, hugr-py/src/hugr/node_port.py, hugr-py/src/hugr/tracked_dfg.py, hugr-py/tests/test_hugr_build.py
Adds a dictionary with metadata to the nodes.
`ToNode` now has a `metadata` property, so we can use
```python
d = Dfg(...)
d.metadata["key"] = 42
n = d.hugr.add_node(..., metadata={"something": "value"})
assert n.metadata["something"] == "value"
```
I chosed not to add a `metadata` argument to all the `add_{container}` methods in DfgBase to avoid cluttering the API.
Closes #1319
=> feat(py): Add node metadata

hugr-core/src/builder/circuit.rs, hugr-core/src/extension.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/extension/simple_op.rs, hugr-core/src/hugr/rewrite/inline_dfg.rs, hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/serialize/upgrade/testcases/hugr_with_named_op.json, hugr-core/src/hugr/validate.rs, hugr-core/src/ops.rs, hugr-core/src/ops/custom.rs, hugr-core/src/ops/validate.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-core/src/std_extensions/logic.rs, hugr-core/src/std_extensions/ptr.rs, hugr-core/src/utils.rs, hugr-passes/src/const_fold.rs, hugr-passes/src/merge_bbs.rs, hugr-py/src/hugr/ops.py, hugr-py/src/hugr/serialization/ops.py, hugr/src/lib.rs, poetry.lock, specification/schema/hugr_schema_live.json, specification/schema/hugr_schema_strict_live.json, specification/schema/testing_hugr_schema_live.json, specification/schema/testing_hugr_schema_strict_live.json
In new workflow most of the time we just want to work with extension ops, and opaque are just used for serialisation. To that end flatten `CustomOp` out.  If there are `OpaqueOp`s in the HUGR it means the extension was not available to resolve in to. Will be disallowed in follow up PR.
Relates to #1362 
BREAKING CHANGE: `CustomOp` removed, `OpType` now contains `ExtensionOp` and `OpaqueOp` directly. `CustomOpError` renamed to`OpaqueOpError`.
=> refactor!: flatten `CustomOp` in to `OpType`

hugr-core/src/builder/circuit.rs, hugr-core/src/extension.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/ops/custom.rs, hugr-py/src/hugr/ext.py, hugr-py/tests/conftest.py, hugr-py/tests/test_cond_loop.py, hugr-py/tests/test_custom.py, hugr-py/tests/test_hugr_build.py, hugr-py/tests/test_tracked_dfg.py, specification/hugr.md
Update python to pass extensions as package when validating
Use cached signatures from opaque when resolving if missing binary compute.
Closes #1362
BREAKING CHANGE: HUGRs containing opaque operations that don't point to an extension in the registry will fail to validate. Use `Package` to pack extensions with HUGRs for serialisation.
=> feat!: disallow opaque ops during validation

.pre-commit-config.yaml, hugr-py/tests/test_custom.py, poetry.lock, pyproject.toml
Ensures that the checks run by `pre-commit` are the same as the ones run in CI.
Before, we used pre-commit actions with their own versions that needed to be updated separately and tended to get out of date.
As an example, the ruff update errors from #1437 didn't appear locally when running `just check`.
drive-by: Update `ruff` to latest version
=> chore: Use local `ruff` and `mypy` for pre-commit

hugr/benches/benchmarks/hugr.rs
Criterion doesn't seem to want to tell me how much memory is used, but its not hard to just print that out (has no variance).
Headline: serialization roundtrip of a 4000 gate circuit takes 33ms, 1.5Mb size.
Closes #1434
=> test: add serialization benchmarks

hugr-core/src/export.rs, hugr-model/src/v0/mod.rs
Updated edge representation. Instead of edges referring to their input and output ports, ports now refer to the id of the edges that they are connected to. This saves some space, and guarantees that each port is part of only one edge.
=> Edge representation in model: make ports refer to the id of the edge.

specification/hugr.md
Also some driveby updates e.g. missed in #906.
Closes #1097, #745.
=> docs: update spec for Row Variables and no-input-extensions

hugr-cli/src/extensions.rs, hugr-cli/src/validate.rs, hugr-core/src/std_extensions.rs, hugr-core/src/std_extensions/collections.rs, specification/std_extensions/collections.json
Bonus lazy static for standard registry
BREAKING CHANGE: collections extension name made lowercase for consistency. ("Collections" -> "collections")
=> feat!: add collections to serialized standard extensions

hugr-core/src/builder.rs, hugr-core/src/hugr/rewrite/simple_replace.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/serialize/upgrade/test.rs, hugr-core/src/hugr/serialize/upgrade/testcases/hugr_with_named_op.json, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/hugr/views/tests.rs, hugr-core/src/std_extensions/logic.rs, hugr-passes/src/const_fold/test.rs, specification/std_extensions/logic.json
BREAKING CHANGE: And, Or, Eq are all now just binary operations. `NaryLogic` renamed to `LogicOp` and `NotOp` has been merged in to it.
=> feat!: variadic logic ops now binary

hugr-py/src/hugr/node_port.py, hugr-py/tests/test_nodes.py
Fixes #1454, and other failing cases
=> fix(py): Invalid node indexing

hugr-py/src/hugr/ops.py, hugr-py/src/hugr/serialization/extension.py, hugr-py/src/hugr/std/__init__.py, hugr-py/src/hugr/std/_json_defs/README.md, hugr-py/src/hugr/std/_json_defs/arithmetic/conversions.json, hugr-py/src/hugr/std/_json_defs/arithmetic/float.json, hugr-py/src/hugr/std/_json_defs/arithmetic/float/types.json, hugr-py/src/hugr/std/_json_defs/arithmetic/int.json, hugr-py/src/hugr/std/_json_defs/arithmetic/int/types.json, hugr-py/src/hugr/std/_json_defs/collections.json, hugr-py/src/hugr/std/_json_defs/logic.json, hugr-py/src/hugr/std/_json_defs/prelude.json, hugr-py/src/hugr/std/_json_defs/ptr.json, hugr-py/src/hugr/std/float.py, hugr-py/src/hugr/std/int.py, hugr-py/src/hugr/std/logic.py, justfile, specification/schema/hugr_schema_live.json, specification/schema/hugr_schema_strict_live.json, specification/schema/testing_hugr_schema_live.json, specification/schema/testing_hugr_schema_strict_live.json
Copies standard extensions to hugr-py source tree, as poetry won't include anything from outside the tree (not symlinks either).
Existing op/type wrappers now just point to loaded extensions.
Closes #1450
=> feat(hugr-py): use serialized extensions in python

hugr-core/src/builder.rs, hugr-core/src/export.rs
fixes one bug found with getting function names
=> test: exporting without panic

hugr-py/src/hugr/cfg.py, hugr-py/src/hugr/cond_loop.py, hugr-py/src/hugr/dfg.py, hugr-py/src/hugr/function.py, hugr-py/src/hugr/hugr.py
Closes #1441.
drive-by: Make `Hugr` covariant.
The plan was to make `ParentBuilder` / `DfBase` covariant too, but they _must_ be invariant since they contain a mutable `Hugr[OpType]` attribute.
BREAKING CHANGE: Renamed `_DfBase` to `DfBase` and `_DefinitionBuilder` to `DefinitionBuilder`
=> refactor!: Make `_DfBase` and `_DefinitionBuilder` public

.pre-commit-config.yaml, hugr-py/pyproject.toml, hugr-py/src/hugr/hugr.py, hugr-py/src/hugr/render.py, hugr-py/tests/__snapshots__/test_hugr_build.ambr, hugr-py/tests/conftest.py, hugr-py/tests/test_hugr_build.py, justfile, poetry.lock, pyproject.toml
Closes #1407.
Ports @mark-koch's rendering code from guppy, since it got deleted from there in the last hugr builder update.
Adds a `Hugr.render_dot` and a `Hugr.store_dot` method.
I'm using `syrupy`—a snapshot pytest extension—for testing it. I'm not sure if we want to be this strict with the generated output though.
=> feat: Bring in the pure-python renderer from guppy

hugr-core/src/std_extensions/arithmetic/float_ops.rs, hugr-core/src/std_extensions/arithmetic/float_ops/const_fold.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-core/src/std_extensions/arithmetic/int_ops/const_fold.rs, hugr-py/src/hugr/std/_json_defs/arithmetic/float.json, hugr-py/src/hugr/std/_json_defs/arithmetic/int.json, specification/std_extensions/arithmetic/float.json, specification/std_extensions/arithmetic/int.json
Adds some missing operations:
- `fpow`
- `fround`
- `ipow`
- `iu_to_s` / `is_to_u`. These are almost noops, but some runtimes may prefer to check and panic if the value is out-of-bounds.
- Mention that `ifrombool` / `itobool` only work with `i1` in their description.
=> feat: Add missing ops

hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/std_extensions/collections.rs, hugr-core/src/std_extensions/collections/list_fold.rs, hugr-passes/src/const_fold/test.rs
Refactors the list operations definition so it's easier to add new ones (#1467), and to bring it in line with the other extension definitions.
- Make the operation enum variants `camelCase`, to match their op names. This lets us us `strum` to auto-derive all the string conversions.
- Implemented `MakeOpDef`, `MakeRegisteredOp`,
BREAKING CHANGE: Renamed `ListOp` variants to camelCase. `collections::EXTENSION_NAME` is now called `EXTENSION_ID`.
=> refactor!: Bring the collections ext in line with other extension defs

hugr-py/src/hugr/hugr.py, hugr-py/tests/serialization/test_basic.py
=> fix(hugr-py): record node children correctly when deserializing

hugr-core/src/extension/prelude.rs, hugr-py/src/hugr/tys.py, hugr-py/src/hugr/val.py
Adds helpers for defining fallible types, so we ensure we always use the same definition. This change does _not_ modify the serialisation format, it's only helpers on top of `Sum`.
On the rust side:
- Adds prelude definitions for `option` and `result` types (special cases of `Sum`s),
including constant values for `some`/`none`, `ok`/`err`.
On the python side:
- Adds an `Option` and `None_` subtype of `tys.Sum`, and `Some`/`None`/`Ok`/`Err` value definitions (also subtypes of `val.Sum`).
These implement nicer `__repr__`, but the classes get lost on a serialisation roundtrip. I'm not sure if we want to auto-detect the special cases during deserialisation?
The names used are rusticisms. Feel free to bikeshed them.
Closes #1473
=> feat: `Option` / `Result` helpers

hugr-py/src/hugr/tys.py, hugr-py/src/hugr/val.py, hugr-py/tests/test_tys.py, hugr-py/tests/test_val.py
This was supposed to be part of #1481, but pushed it to the branch that depended on it instead 🤦 
- Adds the string/repr unit tests suggested by https://github.com/CQCL/hugr/pull/1481#pullrequestreview-2268976031
- Tests—and fixes—equality comparation between Sum values.
=> fix: Sum value equality. Add unit tests

.github/workflows/ci-py.yml, devenv.nix, hugr-py/src/hugr/_serialization/ops.py, hugr-py/src/hugr/_serialization/tys.py, hugr-py/src/hugr/build/dfg.py, hugr-py/src/hugr/ext.py, hugr-py/src/hugr/hugr/base.py, hugr-py/src/hugr/hugr/render.py, hugr-py/src/hugr/ops.py, hugr-py/src/hugr/tys.py, hugr-py/src/hugr/utils.py, hugr-py/src/hugr/val.py, hugr-py/tests/__snapshots__/test_hugr_build.ambr, hugr-py/tests/conftest.py, hugr-py/tests/test_ops.py, hugr-py/tests/test_tys.py, justfile
Closes #1468 
Closes #1470
Previous testing wasn't covering label formatting because it requires actually rendering the dot in to an image. Have enabled that, but put it behind an env var because it significantly slows down tests.
BREAKING CHANGE: rename `Custom.name` to `Custom.op_name` and `Func(Defn/Decl).name` to `f_name` to allow for new `name` method
=> feat(hugr-py)!: pretty printing for ops and types

.github/workflows/docs.yml
Fixes #1478. Passing job: https://github.com/CQCL/hugr/actions/runs/10618695798
The job sets `./hugr-py` as working directory, so the script needed a different relative path.
drive-by: Don't try to publish on non-main workflow_dispatches. That caused the job to fail.
=> ci: Fix docs build script error

hugr-core/src/extension/prelude.rs, hugr-core/src/extension/prelude/array.rs, hugr-py/src/hugr/std/_json_defs/prelude.json, specification/std_extensions/prelude.json
=> feat: fill out array ops

hugr-py/src/hugr/hugr/node_port.py, hugr-py/tests/test_nodes.py
Fixes #1498 
Python lets you slice out of range; `[0,1][90:99]` returns an empty list. This PR makes node slicing behave as such.
=> fix: IndexError on node slicing

hugr-cli/src/extensions.rs, hugr-cli/src/main.rs
To allow downstream cli tools to dump their own extensions.
BREAKING CHANGE: `ExtArgs::run_dump` now takes the registry to dump as an argument.
=> feat(hugr-cli)!: allow registry specification in `run_dump`

hugr-core/src/std_extensions/collections.rs
We changed the `Either` type to use the *right* variant to represent success.
The `insert` operations returns nothing on success, and the element on error. We had the incorrect order here.
=> fix: `std.collections.insert` wrong output order

hugr-py/src/hugr/std/collections.py, hugr-py/src/hugr/std/float.py, hugr-py/src/hugr/std/int.py
#1450 embedded the standard extension definitions in hugr-py, including `collections`, but it didn't add a way to load it as it did with all the others.
This PR adds a `hugr.std.collections` module that just loads the bundled json.
drive-by: Implement `__str__` for `FloatVal` and `IntVal`
=> feat: Export the collections extension

hugr-core/src/std_extensions/collections.rs, hugr-py/src/hugr/std/_json_defs/collections.json, specification/std_extensions/collections.json
Fixes #1543.
BREAKING CHANGE: The `length` op in the std `collections` extensions now also returns the list.
=> fix!: Make list length op give back the list

hugr-core/src/builder/handle.rs
Mini API improvement.
The alternative required creating an output wires array and checking its length...
=> feat: Make `BuildHandle::num_value_outputs` public

.github/workflows/ci-py.yml, hugr-passes/src/lower.rs
Finishing a todo
drive-by: whitespace trimming in yml
=> feat: return replaced ops from lowering

specification/hugr.md
I had to refer to this recently to check that a CFG must have at least two blocks, and found it was...very repetitive and not that easy to follow. Hoping this is a bit better....
=> docs: Try to not repeat ourselves in the spec for CFGs

hugr-py/src/hugr/ext.py, hugr-py/src/hugr/package.py, hugr-py/tests/conftest.py, hugr-py/tests/test_cond_loop.py, hugr-py/tests/test_custom.py, hugr-py/tests/test_package.py, hugr-py/tests/test_tracked_dfg.py
Closes #1561
So far just top level things, can add inner ones (cfg, blocks, etc.) later.
BREAKING CHANGE: `Package` moved to new `hugr.package` module
=> feat!: define wrappers around package that point to internals

hugr-py/src/hugr/_serialization/extension.py, hugr-py/src/hugr/ext.py, hugr-py/src/hugr/package.py, hugr-py/tests/serialization/test_extension.py
=> feat: to/from json for extension/package

hugr-core/src/builder/dataflow.rs, hugr-core/src/hugr/internal.rs
Closes #1562.
It's a chunk of code fiddling with the hugr internals, but it is something specific to function definitions so I think it should be ok to have it under `FunctionBuilder`.
=> feat: `FunctionBuilder::add_{in,out}put`

.github/workflows/unsoundness.yml
miri check currently failing because of this
working run: https://github.com/CQCL/hugr/actions/runs/11295167361
=> ci: install capnp in unsoundness check

.github/workflows/release-plz.yml, DEVELOPMENT.md
The last release workflow run failed due to capnproto not being installed.
https://github.com/CQCL/hugr/actions/runs/11325304655/job/31491921923
drive-by: Add `capnproto` to the list of dev requirements in `DEVELOPMENT.md`
=> ci: Install capnproto in release-plz ci

hugr-core/src/hugr.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__dot_cfg.snap, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__dot_dfg.snap, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__dot_empty_dfg.snap
Closes #1584 
Not having ports in the root nodes caused problems when querying information about them, as shown in #1584.
This PR changes the behaviour to instead allocate the ports, and validate that they are always disconnected.
This should help make the API more homogeneous.
=> fix: Allocate ports on root nodes

hugr-core/src/builder.rs, hugr-core/src/hugr/views/render.rs, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__dot_func.snap, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__dot_module.snap, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__mmd_func.snap, hugr-core/src/hugr/views/snapshots/hugr_core__hugr__views__tests__mmd_module.snap, hugr-core/src/hugr/views/tests.rs, hugr-core/src/types/poly_func.rs
Shows the function names when rendering a hugr.
This should come useful when working with bigger graphs like those emitted by guppy.
```mermaid
graph LR
subgraph 0 ["(0) FuncDefn: #quot;test#quot;"]
direction LR
1["(1) Input"]
2["(2) Output"]
1--"0:0<br>[]+[]"-->2
end
```
=> feat: Render function names in `mermaid`/`dot`

hugr-core/src/builder.rs, hugr-core/src/builder/conditional.rs, hugr-core/src/core.rs, hugr-core/src/extension.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/hugr/rewrite/consts.rs, hugr-core/src/hugr/rewrite/insert_identity.rs, hugr-core/src/hugr/rewrite/outline_cfg.rs, hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/hugr/serialize.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/import.rs, hugr-core/src/ops.rs, hugr-core/src/ops/constant.rs, hugr-core/src/ops/validate.rs, hugr-core/src/types.rs, hugr-core/src/types/type_param.rs, hugr-core/src/utils.rs, hugr-model/Cargo.toml, hugr-model/src/v0/mod.rs, hugr-passes/src/const_fold/test.rs
Particularly useful for cli validation errors.
- Blanket Display for OpType that uses name, can be made more specific in future.
- user derive_more::Display in more places
=> feat: make errors more readable with Display impls

DEVELOPMENT.md, justfile, release-please-config.json, release-plz.toml
Also makes both `release-plz` and `release-please` mark their PRs with `release` labels.
=> docs: Add help docs about `semver-checks`

hugr-cli/src/lib.rs, hugr-cli/src/mermaid.rs, hugr-cli/src/validate.rs, hugr-cli/tests/validate.rs, hugr-core/src/package.rs
Followup to #1587.
Ensures that rust `Package`s only contain module-rooted hugrs. Returns errors at construction times if the condition is not met.
This required fixing `hugr-cli`, as it should be able to load both packages and arbitrary hugrs.
Added `Package::from_hugr{,s}` methods that try to wrap the hugrs if possible. We'll need these for tket2.
Packages are not on the spec yet, their description should include this restriction. See #1388.
This PR does only modify the (unpublished) API introduced in #1587, so I'm not marking it as breaking.
=> feat: Ensure packages always have modules at the root

.github/workflows/ci-rs.yml
~Waiting for https://github.com/CQCL/hugrverse-actions/pull/15 to get merged, so we don't slow down the checks too much.~
=> ci: Don't semver-check if `cargo check` fails

hugr-py/src/hugr/build/cond_loop.py, hugr-py/tests/test_cond_loop.py
Closes #1596
Was tempted to just change the type of `cases` since who would be using it anyway but I've tried to be good and deprecate instead
=> fix(py): allow conditional cases to be defined out of order

.github/workflows/ci-py.yml
drive-by: Ensure `uv sync` uses the right python version and uv version
=> ci: Use `uv --frozen` instead of `--locked`

.github/workflows/notify-coverage.yml
Moved the workflow definition to https://github.com/CQCL/hugrverse-actions/pull/17
I'll update the target branch once that gets merged
=> ci: Use reusable coverage-trend workflow

.github/workflows/unsoundness.yml
Using the new notify-slack workflow from https://github.com/CQCL/hugrverse-actions/pull/18.
I'll update the target branch once that is merged.
=> ci: Notify slack when miri checks fail

hugr-core/src/types.rs
Fixes two unused import errors that only appeared when ignoring some features.
We test `cargo clippy --all-features` on CI, so this didn't get flagged.
```
warning: unused import: `poly_func::PolyFuncTypeBase`
--> hugr-core/src/types.rs:19:16
|
19 | pub(crate) use poly_func::PolyFuncTypeBase;
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `signature::FuncTypeBase`
--> hugr-core/src/types.rs:21:16
|
21 | pub(crate) use signature::FuncTypeBase;
|                ^^^
```
=> chore: Fix unused warnings on default features

hugr-core/src/hugr/hugrmut.rs
We had `set_metadata` and `get_metadata_mut`, but no way to remove the entry entirely.
=> feat: `HugrMut::remove_metadata`

hugr-core/src/package.rs, hugr-core/src/snapshots/hugr_core__package__test__cfg.snap, hugr-core/src/snapshots/hugr_core__package__test__dfg.snap, hugr-core/src/snapshots/hugr_core__package__test__funcdef.snap, hugr-core/src/snapshots/hugr_core__package__test__module.snap
=> fix: Insert DFG directly as a funcdefn in `Package::from_hugr` 

hugr-core/src/builder/build_traits.rs, hugr-core/src/ops/controlflow.rs
It doesn't seem obvious to me which way round these should be, so add constants, and use for the "definitive" `make_break` and `make_continue`.
No change to python as this doesn't even have `make_break` or `make_continue` ATM.
=> feat: Add TailLoop::BREAK_TAG and CONTINUE_TAG

hugr-py/src/hugr/build/dfg.py, hugr-py/src/hugr/hugr/base.py, hugr-py/src/hugr/ops.py, hugr-py/tests/test_hugr_build.py
The number of ports in a `PartialOp` dataflow node didn't get updated after connecting it.
We didn't see any problem with this because by default the number of output ports is grown when connecting new outputs, so the count ended up being correct.
#1625 found a bug where an `UnpackTuple` didn't connect its last output, so the serialization though the node had less output ports than it should have, and connected the order edge at an incorrect offset.
As part of this change I added various checks for the order edge index. We use a special `-1` offset to identify them, so we should panic when that is seen on invalid places.
- drive-by: Add a `Hugr::has_link` method
- drive-by: Avoid adding duplicated order edges
Closes #1625
=> fix: Update number of ports for PartialOps, and sanitize orderd edges

.github/workflows/unsoundness.yml
Looks like `continue-on-error` on a step still doesn't trigger the dependent jobs on error.
This PR ensures that the slack notification job runs when the miri checks fail by adding an `if: always()` instead.
=> ci: Fix unsoundness notification

.github/workflows/unsoundness.yml, hugr-core/src/package.rs, hugr-model/tests/text.rs, hugr-passes/src/nest_cfgs.rs, justfile
A test was using the filesystem to check insta snapshots. This is not supported by miri.
drive-by: Fix lint warning
drive-by: Don't send a slack notification when running the miri checks manually on an arbitrary commit.
CI run:
https://github.com/CQCL/hugr/actions/runs/11726988593
=> chore: Fix unsoundness tests

hugr-core/Cargo.toml, hugr-core/src/export.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/import.rs, hugr-core/tests/snapshots/model__roundtrip_call.snap, hugr-model/src/v0/text/hugr.pest, hugr-model/src/v0/text/parse.rs, hugr-model/src/v0/text/print.rs, hugr-model/tests/fixtures/model-call.edn, hugr-model/tests/fixtures/model-literals.edn, hugr-model/tests/snapshots/text__literals.snap, hugr-model/tests/text.rs
Metadata in `hugr-core` is attached to nodes and to `OpDef`s, consisting of a map from string names to `serde_json::Value`s. On top of that, `OpDef` also has a `description` field. This PR imports and exports node metadata by serializing it to a JSON string and wrapping that string with a `prelude.json` constructor. It also exports the metadata of `OpDef`s, in which case the description field can be exported as a string directly. This PR also introduces string escaping for the text format (#1549).
By wrapping the metadata in a JSON type on the `hugr-model` side, we leave open the option to have typed metadata via the usual term system in the future.
Closes #1631.
=> feat: Export/import of JSON metadata

hugr-model/tests/text.rs
Fixes #1650
Manual run: https://github.com/CQCL/hugr/actions/runs/11815871369/job/32917969928
=> ci: fix miri checks

hugr-core/src/hugr/views/sibling_subgraph.rs
Complementary improvement to #1654.
Creating a k-node subgraph in an n-node graph should ideally be `O(k)`.
However, due to https://github.com/CQCL/portgraph/issues/155 this ends up being `O(n)`.
For `k=1`, this results in a linear cost overhead.
This PR adds a special case (written by @doug-q) that completely skips the unnecessary checks.
```
group                         before                                 from_node
-----                         ------                                 ---------
multinode_subgraph/10         1.01     17.7±0.26µs        ? ?/sec    1.00     17.5±0.23µs        ? ?/sec
multinode_subgraph/100        1.00   169.1±11.34µs        ? ?/sec    1.00    168.8±4.37µs        ? ?/sec
multinode_subgraph/1000       1.01      2.3±0.46ms        ? ?/sec    1.00 …
```
=> feat: Add `SiblingSubgraph::from_node`

Cargo.toml, hugr-core/Cargo.toml, hugr-core/src/export.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/hugr/rewrite/inline_dfg.rs, hugr-core/src/hugr/rewrite/outline_cfg.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/petgraph.rs, hugr-core/src/hugr/views/sibling.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/hugr/views/tests.rs, hugr-core/src/import.rs, hugr-passes/src/half_node.rs, hugr-passes/src/merge_bbs.rs, hugr-passes/src/nest_cfgs.rs
This will simplify the update to the next portgraph release (which also moved to RPITIT), avoiding the need to use boxes around iterators to be able to name them.
- drops the dependency on `context-iterators`
- drive-by: Cleanup the implementations of `SiblingGraph` / `SiblingMut` to avoid `collect_vec().into_iter()`s.
BREAKING CHANGE: Removed `HugrView` associated iterator types, replaced with `impl Iterator` returns.
=> feat!: Replace GATs with `impl Iterator` returns (RPITIT) on `HugrView`

.github/workflows/unsoundness.yml
Requires the new `create-issue` workflow to be merged (https://github.com/CQCL/hugrverse-actions/pull/24).
=> ci: Post issues for miri check fails instead of messaging slack

hugr-core/Cargo.toml, hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/tests/model.rs, hugr-core/tests/snapshots/model__roundtrip_constraints.snap, hugr-model/capnp/hugr-v0.capnp, hugr-model/src/v0/binary/read.rs, hugr-model/src/v0/binary/write.rs, hugr-model/src/v0/mod.rs, hugr-model/src/v0/text/hugr.pest, hugr-model/src/v0/text/parse.rs, hugr-model/src/v0/text/print.rs, hugr-model/tests/binary.rs, hugr-model/tests/fixtures/model-constraints.edn
This PR translates some `TypeBound`s in `hugr-core` to the `nonlinear` constraint in `hugr-model`. This translation only occurs on parameters that take a runtime type directly.
As a driveby change before the model stabilises, this PR also moves constraints out of the parameter lists into their own list. In its previous form this could have led to confusions about which parameter a local variable index refers to when a constraint is situated between two parameters in the list. We also remove constraints from aliases for now.
Closes https://github.com/CQCL/hugr/issues/1637.
=> feat: Emulate `TypeBound`s on parameters via constraints.

hugr-cli/tests/validate.rs, hugr-core/src/extension.rs, hugr-core/src/extension/declarative.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/extension/simple_op.rs, hugr-core/src/hugr/rewrite/inline_dfg.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/ops/custom.rs, hugr-core/src/package.rs, hugr-core/src/std_extensions.rs, hugr-core/src/std_extensions/arithmetic/conversions.rs, hugr-core/src/std_extensions/arithmetic/float_ops.rs, hugr-core/src/std_extensions/arithmetic/float_types.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-core/src/std_extensions/arithmetic/int_types.rs, hugr-core/src/std_extensions/collections.rs, hugr-core/src/std_extensions/logic.rs, hugr-core/src/std_extensions/ptr.rs, hugr-core/src/types/poly_func.rs, hugr-core/src/utils.rs, hugr-passes/src/merge_bbs.rs, hugr/src/lib.rs
Extensions are defined once and shared throughout `ExtensionRegistr`ies, `Package`s, and soon `Hugr`s (#1613).
This _write-once then share around_ is a good usecase for `Arc`s, specially since the definitions are mostly read and rarely cloned.
This is a requisite for #1613, to avoid cloning all extensions for each new hugr.
BREAKING CHANGE: `ExtensionRegistry` and `Package` now wrap `Extension`s in `Arc`s.
=> feat!: Share `Extension`s under `Arc`s

.github/workflows/ci-rs.yml, Cargo.toml, hugr-core/src/extension.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/hugr/internal.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/petgraph.rs, hugr-core/src/hugr/views/sibling.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/proptest.rs, hugr-core/src/types.rs, hugr-core/src/types/custom.rs, hugr-core/tests/model.rs, hugr-model/src/v0/text/print.rs, hugr-model/tests/binary.rs, hugr-model/tests/text.rs
New rust coming on 2024-11-28. This PR fixes new lints that would make our CI runs fail.
A big noisy change is due to public test definitions now triggering the `missing_docs` lint.
See [rust-lang/rust#130025](https://www.github.com/rust-lang/rust/pull/130025). This can be fixed avoided either by adding the docs or by making functions private.
Passing check: https://github.com/CQCL/hugr/actions/runs/12013283775/job/33486450494#step:7:1
=> chore: Fix new lints in rust 1.83

hugr-core/src/builder.rs, hugr-core/src/hugr/rewrite/simple_replace.rs
=> fix: hierarchical simple replacement using insert_hugr

hugr-cli/src/validate.rs, hugr-core/src/builder/circuit.rs, hugr-core/src/export.rs, hugr-core/src/extension.rs, hugr-core/src/extension/declarative.rs, hugr-core/src/extension/declarative/ops.rs, hugr-core/src/extension/declarative/types.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/extension/prelude/array.rs, hugr-core/src/extension/simple_op.rs, hugr-core/src/extension/type_def.rs, hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/ops/custom.rs, hugr-core/src/package.rs, hugr-core/src/std_extensions/arithmetic/conversions.rs, hugr-core/src/std_extensions/arithmetic/float_ops.rs, hugr-core/src/std_extensions/arithmetic/float_types.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-core/src/std_extensions/arithmetic/int_types.rs, hugr-core/src/std_extensions/collections.rs, hugr-core/src/std_extensions/logic.rs, hugr-core/src/std_extensions/ptr.rs, hugr-core/src/types/poly_func.rs, hugr-core/src/utils.rs, hugr-llvm/src/custom/extension_op.rs, hugr-passes/src/merge_bbs.rs, hugr/benches/benchmarks/hugr/examples.rs, hugr/src/lib.rs
This change was extracted from the work towards #1613.
Now `OpDef`s and `TypeDef`s keep a `Weak` reference to their extension's `Arc`.
This way we will be able to automatically set the extension requirements when adding operations, so we can get rid of `update_validate` and the explicit registries when building hugrs.
To implement this, the building interface for `Extension`s is sightly modified.
Once an `Arc` is built it cannot be modified without doing internal mutation.
But we need the `Arc`'s weak reference to define the ops and types.
Thankfully, we can use `Arc::new_cyclic` which provides us with a `Weak` ref at build time so we are able to define things as needed.
This is wrapped in a new `Extension::new_arc` method, so the user doesn't need to think about that.
BREAKING CHANGE: …
=> feat!: OpDefs and TypeDefs keep a reference to their extension

hugr-core/src/hugr/hugrmut.rs, hugr-core/src/hugr/rewrite.rs, hugr-core/src/hugr/views.rs
* Clarify doc of HugrMut::remove_node
* Add HugrView::first_child, we have this anyway and it's useful because Rust's non-lexical lifetimes don't go far enough
* Add HugrMut::remove_subtree, test
closes #1663
=> feat: add HugrView::first_child and HugrMut::remove_subtree

hugr-core/src/std_extensions/collections.rs, hugr-llvm/src/emit/func.rs, hugr-llvm/src/emit/test.rs, hugr-llvm/src/extension.rs, hugr-llvm/src/extension/collections.rs, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__const@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__const@pre-mem2reg@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__get@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__get@pre-mem2reg@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__insert@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__insert@pre-mem2reg@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__length@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__length@pre-mem2reg@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__pop@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__pop@pre-mem2reg@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__push@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__push@pre-mem2reg@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__set@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__collections__test__set@pre-mem2reg@llvm14.snap
Closes #1701 and fixes #1645.
Note that destructors and ref-counting hooks are still missing. These will follow in a future PR once they are available in hugr-llvm.
=> feat: Lower collections extension

hugr-core/src/hugr/rewrite/simple_replace.rs
Sercond commit is optional, see PR comment on comment
=> refactor: avoid hugr clone in simple replace

hugr-model/src/lib.rs, hugr-model/src/v0/text/print.rs
=> fix: Ignare lint warnings in capnproto generated code

hugr-core/src/hugr/rewrite/replace.rs
Missed from #1721 but this is exactly the kind of code that `first_child` was intended to handle.
=> refactor: [trivial] replace.rs: use HugrView::first_child 

hugr-core/src/builder/cfg.rs, hugr-core/src/builder/conditional.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/extension/resolution/ops.rs, hugr-core/src/hugr/rewrite/outline_cfg.rs, hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/sibling.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/ops.rs, hugr-core/src/ops/constant.rs, hugr-core/src/ops/controlflow.rs, hugr-core/src/ops/custom.rs, hugr-core/src/ops/dataflow.rs, hugr-core/src/ops/module.rs, hugr-core/src/ops/sum.rs, hugr-core/src/ops/validate.rs, hugr-core/src/package.rs, hugr-core/src/std_extensions/arithmetic/int_ops.rs, hugr-llvm/src/extension/prelude/array.rs, hugr-llvm/src/utils/inline_constant_functions.rs, hugr-passes/src/dataflow/test.rs, hugr-passes/src/merge_bbs.rs
```
group                                    cows                                   serialization
-----                                    ----                                   -------------
circuit_roundtrip/capnp/0                1.02      5.3±0.52µs        ? ?/sec    1.00      5.2±0.09µs        ? ?/sec
circuit_roundtrip/capnp/1                1.00     12.5±0.74µs        ? ?/sec    1.14     14.2±0.16µs        ? ?/sec
circuit_roundtrip/capnp/10               1.00     25.9±0.39µs        ? ?/sec    1.31     34.0±0.30µs        ? ?/sec
circuit_roundtrip/capnp/100              1.00    155.8±2.01µs        ? ?/sec    1.47    229.6±2.46µs        ? ?/sec
circuit_roundtrip/capnp/1000             1.00  1483.7±64.06µs        ? ?/sec    1.43      2.1±0.04ms        ? ?/sec …
```
=> perf: Return `Cow<Signature>` where possible

hugr-core/src/ops/custom.rs, hugr-py/src/hugr/_serialization/extension.py, hugr-py/src/hugr/ext.py, hugr-py/src/hugr/ops.py, hugr-py/src/hugr/std/int.py, hugr-py/src/hugr/tys.py, hugr-py/tests/test_custom.py
Fixes #1758 
Without these changes, the validation tests fail if we remove the workaround in `custom.rs`
=> fix: hugr-py not adding extension-reqs on custom ops

hugr-core/src/types.rs
=> feat: add `is_` variant methods to `EdgeKind`

hugr-llvm/src/emit/func.rs, hugr-llvm/src/emit/func/mailbox.rs, hugr-llvm/src/emit/ops.rs, hugr-llvm/src/emit/snapshots/hugr_llvm__emit__test__test_fns__tail_loop@llvm14.snap, hugr-llvm/src/emit/snapshots/hugr_llvm__emit__test__test_fns__tail_loop@pre-mem2reg@llvm14.snap, hugr-llvm/src/emit/snapshots/hugr_llvm__emit__test__test_fns__tail_loop@pre-mem2reg@llvm14_2.snap, hugr-llvm/src/emit/snapshots/hugr_llvm__emit__test__test_fns__tail_loop_simple@llvm14.snap, hugr-llvm/src/emit/snapshots/hugr_llvm__emit__test__test_fns__tail_loop_simple@pre-mem2reg@llvm14.snap, hugr-llvm/src/emit/snapshots/hugr_llvm__emit__test__test_fns__tail_loop_simple@pre-mem2reg@llvm14_3.snap, hugr-llvm/src/emit/test.rs, hugr-llvm/src/sum.rs
Work in progress. Will address #1688
=> feat(llvm): Tail loop emission

hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-llvm/src/emit/test.rs, hugr-passes/src/lower.rs, hugr/Cargo.toml
Uses `from_node` in lowering code to take advantage of this
Closes #1746
=> fix: allow disconnected outputs in SiblingSubgraph::from_node

hugr-cli/src/lib.rs, hugr-cli/tests/validate.rs
BREAKING CHANGE: Deprecated `Package` re-export from hugr-cli removed.
BREAKING CHANGE: Deprecated `HugrArgs::get_package` removed.
=> refactor(cli)!: remove deprecations

hugr-core/src/extension/resolution.rs, hugr-core/src/extension/resolution/types.rs, hugr-core/src/extension/resolution/types_mut.rs, hugr-py/tests/test_hugr_build.py
Collects and resolves extensions in the types stored inside a `Value`. This includes the specified type of a `Sum` and other cached types.
Since we expect `CustomConst`'s `get_type` method to always return signatures computed by a binary definition.
For some reason there's a random test on `hugr-py` that starts failing when we enable this:
```
=================================== FAILURES ===================================
______________________________ test_higher_order _______________________________
Error parsing package: Error resolving opaque operation: Error in signature of operation 'prelude.Noop' in Node(3): Type arguments of node did not match params declared by definition: Wrong number of type arguments: 0 vs expected 1 declared type parameters
```
The fix for #1774 that I'm …
=> fix: Resolve types in `Value`s and custom consts

hugr-core/src/extension/prelude.rs, hugr-core/src/extension/resolution.rs, hugr-core/src/extension/resolution/test.rs, hugr-core/src/extension/resolution/types_mut.rs, hugr-core/src/ops/constant.rs, hugr-core/src/ops/constant/custom.rs, hugr-core/src/std_extensions/collections/list.rs
Closes #1742.
Adds a (default defined) `update_extensions` call to `CustomConst` so it can update its internal extension `Weak` pointers after loading a serialized hugr.
=> feat: Update extension pointers in customConsts

hugr-core/src/extension/prelude.rs, hugr-core/src/extension/resolution.rs, hugr-core/src/extension/resolution/ops.rs, hugr-core/src/extension/resolution/test.rs, hugr-core/src/extension/resolution/types.rs, hugr-core/src/extension/resolution/types_mut.rs, hugr-core/src/extension/resolution/weak_registry.rs, hugr-core/src/hugr.rs, hugr-core/src/ops/constant.rs, hugr-core/src/ops/constant/custom.rs, hugr-core/src/std_extensions/collections/list.rs, hugr-core/src/types/signature.rs
We'll need this to resolve extension references inside an extension that's being created.
drive-by: Make "node" optional in resolution errors.
BREAKING CHANGE: `::extension::resolve` operations now use `WeakExtensionRegistry`es.
=> feat!: Use registries of `Weak<Extension>`s when doing resolution 

hugr-core/src/extension.rs, hugr-core/src/extension/op_def.rs, hugr-core/src/extension/resolution.rs, hugr-core/src/extension/resolution/extension.rs, hugr-core/src/extension/resolution/test.rs, hugr-core/src/extension/resolution/types_mut.rs, hugr-core/src/extension/type_def.rs, hugr-core/src/package.rs
When deserializing an `ExtensionRegistry`, traverses the extension definitions to update any `Weak<Extension>` so they point to valid extensions (including to extensions in the registry being deserialized!).
This needed a bit of `unsafe` trickery to mimic [`Arc::new_cyclic`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.new_cyclic) but for vectors of extensions.
As with `Package`, I left the `serde::Deserialize` implementation available but now extension registries have a `load_json` method that should be used when possible, as it runs the required pointer updates.
BREAKING CHANGE: Marked `ExtensionBuildError` and `ExtensionRegistryError` as non-exhaustive.
=> feat!: Resolve extension references inside the extension themselves

hugr-core/src/extension/prelude/unwrap_builder.rs, hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/std_extensions/collections/list.rs, hugr-llvm/src/extension/collections/array.rs, hugr-llvm/src/utils/array_op_builder.rs, hugr-passes/src/const_fold/test.rs, hugr-passes/src/monomorphize.rs
Last two remaining usages of `ExtensionRegistry` as redundant parameters. These should have been included in #1784.
BREAKING CHANGE: `UnwrapBuilder` no longer requires an `ExtensionRegistry` as argument.
BREAKING CHANGE: `ListOpInst` no longer requires an `ExtensionRegistry` to produce an `ExtensionOp`.
=> feat!: Remove ExtensionRegistry args in UnwrapBuilder and ListOp

hugr-core/src/extension/op_def.rs, hugr-core/src/extension/resolution.rs, hugr-core/src/extension/resolution/ops.rs, hugr-core/src/hugr.rs, hugr-py/src/hugr/ext.py
Ignores custom operations that are missing their own extension as a runtime req when validating.
drive-by: Update doc that still refered to `extension_requirements`
=> feat: Automatically add the custom op's extension to its 'runtime_reqs' set

hugr-core/src/std_extensions/collections/array.rs, hugr-core/src/std_extensions/collections/list.rs, hugr-llvm/src/extension/collections/array.rs, hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__array__test__emit_array_value@llvm14.snap, hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__array__test__emit_array_value@pre-mem2reg@llvm14.snap, hugr-py/src/hugr/std/collections/array.py, hugr-py/tests/test_tys.py, uv.lock
drive-by: fix Array type annotation
Closes #1771 
TODO:
=> feat: add ArrayValue to python, rust and lowering

hugr-core/src/extension/resolution/test.rs, hugr-core/src/extension/resolution/types.rs, hugr-core/src/extension/resolution/types_mut.rs, hugr-core/src/types.rs
Fixes #1795 
I forgot to track the `type_args` of `Call` and `LoadFunction` when doing extension resolution
drive-by: Add derives to `types::Substitution`
=> fix: `Call` ops not tracking their parameter extensions

hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/tests/snapshots/model__roundtrip_add.snap, hugr-core/tests/snapshots/model__roundtrip_alias.snap, hugr-core/tests/snapshots/model__roundtrip_call.snap, hugr-core/tests/snapshots/model__roundtrip_cfg.snap, hugr-core/tests/snapshots/model__roundtrip_cond.snap, hugr-core/tests/snapshots/model__roundtrip_constraints.snap, hugr-model/capnp/hugr-v0.capnp, hugr-model/src/v0/binary/read.rs, hugr-model/src/v0/binary/write.rs, hugr-model/src/v0/mod.rs, hugr-model/src/v0/scope/link.rs, hugr-model/src/v0/scope/mod.rs, hugr-model/src/v0/scope/symbol.rs, hugr-model/src/v0/scope/vars.rs, hugr-model/src/v0/text/hugr.pest, hugr-model/src/v0/text/parse.rs, hugr-model/src/v0/text/print.rs
This PR introduces scoping for symbols, links and variables. It comes with utilities that can be used to resolve names appropriately. Moreover the model data structures are changed so that they always use direct references by indices instead of names in order to streamline the serialisation format.
=> feat: Scoping rules and utilities for symbols, links and variables

hugr-py/src/hugr/ops.py, hugr-py/tests/test_cond_loop.py, hugr-py/tests/test_hugr_build.py
=> feat: add wrapper for tagging Some, Left, Right, Break, Continue

release-plz.toml
When creating a release, you can mark one as `latest` so it appears on the left column of the main repository page.
This change makes it so only `hugr` gets marked as it (otherwise `hugr-cli` always gets the spotlight).
Note that python releases are always marked as `latest`.
=> ci: Don't mark subcrates as "latest" github releases

hugr-py/src/hugr/std/prelude.py, hugr-py/tests/test_prelude.py
Closes #1817
Enables strings in Guppy, see CQCL/guppylang#695
=> feat: Add `StringVal` to hugr-py

hugr-py/src/hugr/std/collections/array.py, hugr-py/src/hugr/std/collections/list.py
The rust-side serialization definition for custom constants is a bit more complex than what we had written on the python side for array and list values.
This fixes #1826, and was tested by running the issue's example from guppy.
- > Why aren't we testing this locally?
Constant value deserialization is a "best effort" thing.
If we can match the serialized thing with one of the hardcoded implementors of `CustomConst` (registered in a global var by `typetag`) then we deserialize into the specific class.
If we cannot deserialize into any specific class, we use `CustomSerialized` by default.
So even if we build a constant from python and `validate` using the rust checker, the deserialization will succeed and validate correctly.
It'd be nice to fail the deserialization if a constant claims to …
=> fix(py): Fix array/list value serialization

hugr-core/src/ops/constant.rs, hugr-core/src/types.rs
Some simple helpers I needed while testing, and seem reasonable to have.
=> feat: `Value::some`, `::none`, and `SumType::new_option` helpers

hugr-llvm/src/emit/test.rs, hugr-llvm/src/extension/int.rs, hugr-llvm/src/test.rs
More work on #1702. Adds `ine`, `iabs`, `imax_{s,u}`, `imin_{s,u}`, `ishl`, `ishr`, `ixor`, `ior`, `inot`, `iand`
=> feat(hugr-llvm): Emit more int ops

hugr-llvm/src/extension/int.rs
The `!1 = 0` test doesn't work because the ints it's run on are more than 1 bit wide. I tried reducing the width but it seems the hugr-llvm conversion isn't faithful, downcasting smaller int types to `u8`, meaning `!1` would be `254`
=> test: Fix failing inot test

.github/workflows/ci-rs.yml, .github/workflows/semver-checks.yml, devenv.lock, devenv.nix, devenv.yaml, hugr-core/src/hugr/serialize.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/sibling.rs, hugr-llvm/Cargo.toml, hugr-llvm/src/lib.rs, uv.lock
- Updates devenv to match rust version on CI (1.84)
- clippy fixes
- Installs llvm all the time and removes separate hugr-llvm job because runner image no longer has LLVM to link to.  Follow up issue: https://github.com/CQCL/hugr/issues/1851
- ~[Nightly is failing](https://github.com/CQCL/hugr/actions/runs/12696563342/job/35390874375?pr=1847) for what appears to be an unrelated rustc bug.~ has been fixed!
- Semver checks failing because adding "llvm-14" to the `apt-dependencies` appears to not be changing anything??? https://github.com/CQCL/hugr/actions/runs/12707081975/job/35421268084?pr=1847 https://github.com/CQCL/hugr/issues/1852
Closes #1843
=> ci: fixes to runner image update

Cargo.toml, hugr-core/src/import.rs, hugr-model/Cargo.toml, hugr-model/capnp/hugr-v0.capnp, hugr-model/src/v0/binary/read.rs, hugr-model/src/v0/binary/write.rs, hugr-model/src/v0/mod.rs, hugr-model/src/v0/text/hugr.pest, hugr-model/src/v0/text/parse.rs, hugr-model/src/v0/text/print.rs, hugr-model/tests/binary.rs, hugr-model/tests/fixtures/model-literals.edn, hugr-model/tests/snapshots/text__literals.snap
Adds a term for byte literals to hugr-model.
In the text format, byte literals are represented as base64 encoded strings.
Closes #1545.
=> feat: Bytes literal in hugr-model.

hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/tests/snapshots/model__roundtrip_cfg.snap, hugr-core/tests/snapshots/model__roundtrip_constraints.snap, hugr-model/tests/fixtures/model-cfg.edn, hugr-model/tests/fixtures/model-constraints.edn
This PR fixes three bugs in the import/export between `hugr_model` and `hugr_core`.
1. The types of the source and target ports of a CFG region must be wrapped in a `ctrl` type on export.
2. Importing links that have a single input or output but aren't otherwise connected should be valid.
3. Runtime types are valid `TypeArg`s.
=> fix: Three bugfixes in model import and export.

hugr-core/src/ops/dataflow.rs
=> docs: Fix typo in `DataflowParent` doc

hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/tests/snapshots/model__roundtrip_call.snap, hugr-core/tests/snapshots/model__roundtrip_const.snap, hugr-model/capnp/hugr-v0.capnp, hugr-model/src/v0/binary/read.rs, hugr-model/src/v0/binary/write.rs, hugr-model/src/v0/mod.rs, hugr-model/src/v0/text/hugr.pest, hugr-model/src/v0/text/parse.rs, hugr-model/src/v0/text/print.rs, hugr-model/tests/fixtures/model-call.edn, hugr-model/tests/fixtures/model-const.edn, hugr-model/tests/fixtures/model-decl-exts.edn, hugr-model/tests/snapshots/text__declarative_extensions.snap
Closes #1848 by using a term-based representation for metadata items.
=> feat: Improved representation for metadata in `hugr-model`

Cargo.toml, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/sibling.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr/benches/benchmarks/subgraph.rs
The new portgraph release comes with some perf improvements.
We require this update for #1869.
Closes #1872.
I added a benchmark variation for subgraphs with few nodes as a drive-by.
This got improved by the new portgraph (skipping a full graph traversal), but the runtime is still mostly the `O(n)` full-graph traversal required for the convexity checking when building the subgraph.
BREAKING CHANGE: Bumped public dependency `portgraph` to breaking version `0.13`.
=> chore!: Update to `portgraph 0.13` / `petgraph 0.7`

hugr-passes/src/dead_funcs.rs, hugr-passes/src/lib.rs
The `RemoveDeadFuncsPass` returns this error, which was hidden inside a private module.
Adds missing docs to the struct, and converts the tuple variant into a regular struct.
=> fix: Export `RemoveDeadFuncsError`

.github/workflows/release-plz.yml
Fixes #1880.
See https://github.com/CQCL/hugr/issues/1851, although this may be unavoidable here.
=> ci: Install LLVM before running release-plz

.github/workflows/release-plz.yml
It seems the `install-llvm-action` downloads it directly into the working directory, and makes the workflow fail due to uncommitted changes:
https://github.com/CQCL/hugr/actions/runs/12870816871/job/35882749195#step:6:275
Can't really test this without merging, but I think it should work alright...
=> ci: Fix llvm install on release-plz workflow (again)

hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/src/std_extensions/arithmetic/float_types.rs, hugr-core/src/std_extensions/arithmetic/int_types.rs, hugr-core/src/std_extensions/collections/array.rs, hugr-core/tests/snapshots/model__roundtrip_const.snap, hugr-model/Cargo.toml, hugr-model/capnp/hugr-v0.capnp, hugr-model/src/v0/binary/read.rs, hugr-model/src/v0/binary/write.rs, hugr-model/src/v0/mod.rs, hugr-model/src/v0/text/hugr.pest, hugr-model/src/v0/text/parse.rs, hugr-model/src/v0/text/print.rs, hugr-model/tests/fixtures/model-const.edn, hugr-model/tests/fixtures/model-literals.edn, hugr-model/tests/snapshots/text__literals.snap
This PR special cases the import/export of array, float and int constants so that they are represented as terms in `hugr-model`. This representation is a lot more efficient to handle than the encoding as JSON. In the future we should do this for all constants.
=> feat: Special cased array, float and int constants in hugr-model export

hugr-core/src/import.rs, hugr-core/tests/snapshots/model__roundtrip_constraints.snap, hugr-model/tests/fixtures/model-constraints.edn
Import now determines the bound of the custom type correctly.
Fixes #1876.
=> fix: determine correct bounds of custom types

hugr-core/src/export.rs, hugr-core/tests/snapshots/model__roundtrip_cfg.snap
=> fix: Exporting converging control flow edges

hugr-passes/src/const_fold.rs, hugr-passes/src/const_fold/test.rs
Minimal, non-breaking, fix for #1797, this seems consistent with what dataflow analysis does.
=> fix: const-folding Module keeps at least "main"

hugr-core/src/std_extensions/logic.rs, hugr-llvm/src/extension/logic.rs, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__logic__test__eq@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__logic__test__eq@pre-mem2reg@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__logic__test__xor@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__logic__test__xor@pre-mem2reg@llvm14.snap, hugr-py/src/hugr/std/_json_defs/logic.json, specification/std_extensions/logic.json
=> feat: add xor to logic extension

hugr-core/src/hugr/views/impls.rs
Without delegating all methods with default impls, you get the following weirdness that drove me crazy this morning
```rust
trait TraitFoo {
fn something(&self) -> usize {
return 42;
}
}
impl<'t, T: TraitFoo> &'t T {}
struct A;
impl TraitFoo for A {
fn something(&self) -> usize {
return 0;
}
}
let a = A();
a.something()     // is 0
(&a).something()  // is 42 :(
```
=> fix: delegate default impls in HugrView

hugr-core/Cargo.toml, hugr-llvm/Cargo.toml, hugr/Cargo.toml
found using cargo-machete
no easy way to remove unused entries from the workspace Cargo.toml
BREAKING CHANGE: Removed some unused dependencies from hugr-llvm test-utils feature.
=> refactor!: remove unused dependencies

hugr-model/Cargo.toml
Fixes #1939
The semver checks run still fail here because the `main` baseline still has the error 💀
=> fix: Hugr-model using undeclared derive_more features

hugr-core/src/builder/build_traits.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/builder/tail_loop.rs, hugr-core/src/extension/prelude.rs, hugr-core/src/hugr.rs, hugr-core/src/hugr/rewrite/inline_dfg.rs, hugr-core/src/hugr/validate/test.rs, hugr-llvm/src/extension/prelude.rs, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__prelude__test__prelude_barrier@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__prelude__test__prelude_barrier@pre-mem2reg@llvm14.snap, hugr-passes/src/merge_bbs.rs, hugr-py/src/hugr/std/_json_defs/prelude.json, specification/std_extensions/prelude.json
Difference is barrier does not add extensions
The first two commit is worth merging even without the rest.
BREAKING CHANGE: Lift op in prelude replaced with a Barrier that behaves similarly except does not add any extensions.
=> feat!: replace `Lift` with `Barrier`

hugr-core/Cargo.toml
=> revert: `unstable-*` features should not be default

hugr-py/pyproject.toml, hugr-py/src/hugr/envelope.py, hugr-py/src/hugr/package.py, hugr-py/tests/conftest.py, hugr/Cargo.toml, pyproject.toml, uv.lock
Closes #1979 
- Adds a default `zstd` feature to `hugr-rs`, so `hugr-cli` supports it.
- Updates the `validate` conftest util to test both binary and textual encodings.
---
There's multiple python packages which provide bindings for zstd:
- [`zstd`](https://pypi.org/project/zstd), which provides a quite simple encode/decode API. It seems to follow `zstd` releases quite closely.
- [`zstandard`](https://pypi.org/project/zstandard/), a "rich Pythonic interface" to the zstd bindings, listed as an alternative by `zstd`.
- [`pyzstd`](https://pypi.org/project/pyzstd/#files), similar to `zstd`.
I went with the former since it's the most popular one.
There's an open vuln report for this: https://osv.dev/vulnerability/PYSEC-2023-121, but it is outdated and the current version already patches it …
=> feat(hugr-py): Support envelope compression

DEVELOPMENT.md
With the new envelopes and work on `hugr-model`, the section became quite outdated.
We could add it back once model is stabilized.
=> chore: Drop Serialization section from DEVELOPMENT.md

hugr-cli/src/hugr_io.rs, hugr-cli/src/lib.rs
Minor special-casing for CLI message error.
Before:
```
$ hugr validate invalid.hugr
Error decoding HUGR envelope: Bad magic number. expected 0x4855475269484A76 found 0x7B0A20202020226D
```
After:
```
$ hugr validate invalid.hugr
Input file is not a HUGR envelope. Invalid magic number.
Use `--hugr-json` to read a raw HUGR JSON file instead.
```
=> feat(hugr-cli): Nicer error when passing a non-envelope file

hugr-core/src/extension/prelude.rs, hugr-llvm/src/extension/prelude.rs, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__prelude__test__prelude_exit@llvm14.snap, hugr-llvm/src/extension/snapshots/hugr_llvm__extension__prelude__test__prelude_exit@pre-mem2reg@llvm14.snap, hugr-py/src/hugr/std/_json_defs/prelude.json, specification/std_extensions/prelude.json
Closes #1966
panic ends all shots, exit ends current shot and signals next shot can still run
By default they are handled identically with an abort in codegen - I am not sure if this is the right thing to do.
=> feat: add exit operation to prelude

hugr-core/src/envelope/header.rs, hugr-py/src/hugr/envelope.py, uv.lock
We did a hugr-rs minor release changing the default binary envelope encoding to have compression enabled.
Since compression support was added in the same minor match, previous semver-compatible releases will fail to read such envelopes.
This PR disables default compression. We should enable it on the next breaking release instead.
=> fix: Don't enable envelope compression by default (yet)

hugr-core/src/hugr/views/sibling_subgraph.rs
`SiblingSubgraph::from_nodes` and `from_node` have different definitions.
The former takes a set of nodes and defines a subgraph where the inputs and outputs correspond to all edges connecting the chosen nodes to external ones.
When a node has a disconnected port, it is ignored.
The latter does not check edges. It takes a single node and creates a subgraph using the dataflow signature of the operation.
Both definitions are valid and useful on their own, when calling `from_nodes` with a single-element vector we redirected the call to `from_node`, resulting in different port definitions.
This PR fixes that.
=> fix: Inconsistent behaviour in `SiblingSubgraph::from_nodes`

hugr-py/pyproject.toml, hugr-py/src/hugr/build/cond_loop.py, hugr-py/src/hugr/package.py, uv.lock
`typing_extensions` defines a `@deprecated` decorator compatible with `python<3.13`
drive-by: Added decorator to `Else.finish`, which said it was deprecated in its docstring but didn't raise any warnings.
=> chore: Enable deprecation warnings on pre-313 python

hugr-core/src/builder.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/envelope.rs, hugr-core/src/hugr.rs, hugr-passes/src/monomorphize.rs, hugr-passes/src/nest_cfgs.rs, uv.lock
It's rust release week!
New lint warnings checked with `rustup override set beta`.
It's mostly `doc_overindented_list_items` and a case of `Iterator::last` called where `DoubleEndedIterator::next_back` could be used instead.
=> chore: Fix lints coming in rust 1.86

Cargo.lock, hugr-passes/Cargo.toml, hugr-passes/src/lib.rs, hugr-passes/src/untuple.rs
Imports the `MakeTuple -> UnpackTuple` elimination pass from tket2.
This removes tuple unpacks consuming the output of a `MakeTuple`, and deletes the packing operation when possible.
This pass *does not* remove the reverse case, `Unpack->MakeTuple`. Should it be added here? We should avoid producing overlapping rewrites if doing that (the simple `Pack->Unpack->Pack` case is easy, but multiports can make things interesting). 
Requires #2011
Closes #1810
=> feat: MakeTuple->UnpackTuple elision pass

hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/tests/model.rs, hugr-core/tests/snapshots/model__roundtrip_order.snap, hugr-model/src/v0/ast/hugr.pest, hugr-model/src/v0/mod.rs, hugr-model/tests/fixtures/model-order.edn, hugr-py/src/hugr/model/export.py
This PR introduces metadata to encode order edges in `hugr-model`. The children of a dataflow region can be assigned a key via `order_hint.key` metadata. Then `order_hint.order` metadata on the dataflow region encodes order edges between keys. The PR includes the necessary import and export code in `hugr-core`.
=> feat: Represent order edges in `hugr-model` as metadata.

hugr-core/src/core.rs
This sightly changes the debug output of `Wire<Node>`, but it shouldn't matter much since this is not the `Display` impl.
before: `Wire { node: 42, port: OutgoingPort(2) }`
after: `Wire { node: Node(42), port: OutgoingPort(2) }`
=> feat: Implement Debug for generic Wire<N>s

hugr-core/src/ops.rs, hugr-core/src/ops/custom.rs
- We had `OpType::cast` but were missing it in `ExtensionOp` itself.
- Adds a `ExtensionOp::extension_id` call
=> feat: Add ExtensionOp helpers

hugr-core/src/extension.rs, hugr-core/src/hugr/serialize/upgrade.rs, hugr-core/src/import.rs, hugr-model/src/v0/ast/resolve.rs, hugr-model/src/v0/table/mod.rs, hugr-passes/src/lower.rs, hugr-passes/src/non_local.rs, hugr-passes/src/replace_types/linearize.rs, hugr-passes/src/validation.rs
#2027 ended up being breaking due to adding a new variant to an error enum missing the `non_exhaustive` marker.
This (breaking) PR makes sure all error enums have the flag.
BREAKING CHANGE: Marked all Error enums as `non_exhaustive`
=> feat!: Mark all Error enums as non_exhaustive

hugr-core/src/ops.rs, hugr-core/src/ops/handle.rs
Adds a generic node type to the `NodeHandle` type.
This is a required change for #2029.
drive-by: Implement the "Link the NodeHandles to the OpType" TODO
=> feat: Make NodeHandle generic

hugr-core/src/hugr/patch/simple_replace.rs, hugr-passes/src/lower.rs
It is currently impossible to obtain the map from nodes in the replacement graph to newly inserted nodes in `self` from the `ApplyResult` type for `SimpleReplacement`.
This PR fixes this.
BREAKING CHANGE: The `ApplyResult` associated type of `SimpleReplacement` is now a custom struct. The deleted nodes returned previously can be obtained using the `result.deleted_nodes` field.
=> feat!: Expand SimpleReplacement::ApplyResult type

hugr-passes/src/replace_types.rs, hugr-passes/src/replace_types/handlers.rs, hugr-passes/src/replace_types/linearize.rs
There are two issues:
* Errors. The previous NodeTemplates still always work, but the Call one can fail if the Hugr doesn't contain the target function node. ATM there is no channel for reporting that error so I've had to panic. Otherwise it's an even-more-breaking change to add an error type to `NodeTemplate::add()` and `NodeTemplate::add_hugr()`. Should we? (I note `HugrMut::connect` panics if the node isn't there, but could make the `NodeTemplate::add` builder method return a BuildError...and propagate that everywhere of course)
* There's a big limitation in `linearize_array` that it'll break if the *element* says it should be copied/discarded via a NodeTemplate::Call, as `linearize_array` puts the elementwise copy/discard function into a *nested Hugr* (`Value::Function`) that won't …
=> feat!: ReplaceTypes: allow lowering ops into a Call to a function already in the Hugr

.github/workflows/ci-rs.yml, hugr-core/Cargo.toml, hugr-core/README.md, hugr-core/src/envelope.rs, hugr-core/src/lib.rs, hugr-core/src/std_extensions/arithmetic/float_types.rs, hugr-core/src/std_extensions/arithmetic/int_types.rs, hugr-core/src/std_extensions/collections/array.rs, hugr/Cargo.toml, hugr/benches/benchmarks/hugr.rs, release-plz.toml
This PR removes the `model_unstable` feature flag across the repository. Closes #2104.
BREAKING CHANGE: Downstream crates need to remove the `model_unstable` feature flag when referencing `hugr` or `hugr-core`.
=> feat!: Removed `model_unstable` feature flag.

hugr-core/Cargo.toml, hugr-core/src/builder/dataflow.rs, hugr-core/src/builder/module.rs, hugr-core/src/hugr.rs, hugr-core/src/hugr/hugrmut.rs, hugr-core/src/hugr/internal.rs, hugr-core/src/hugr/rewrite.rs, hugr-core/src/hugr/rewrite/inline_call.rs, hugr-core/src/hugr/rewrite/replace.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/descendants.rs, hugr-core/src/hugr/views/impls.rs, hugr-core/src/hugr/views/root_checked.rs, hugr-core/src/hugr/views/sibling.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/package.rs, hugr-llvm/src/utils/inline_constant_functions.rs, hugr-passes/src/half_node.rs, hugr-passes/src/lower.rs, hugr-passes/src/merge_bbs.rs, hugr-passes/src/monomorphize.rs, hugr-passes/src/nest_cfgs.rs, hugr/src/hugr.rs, uv.lock
Closes #2077
BREAKING CHANGE: Removed `RootTagged` trait. Now `RootChecked` is a non-hugrview wrapper only used to verify inputs where appropriate.
=> feat!: Remove `RootTagged` from the hugr view trait hierarchy

hugr-core/src/hugr/patch/port_types.rs, hugr-core/src/hugr/patch/simple_replace.rs, hugr-core/src/hugr/views/sibling_subgraph.rs
Currently, SimpleReplacement stores its output boundary map nu_out by referring to nodes outside the deleted subgraph in the host graph. This forces the invalidation set of the replacements to include nodes past the output, forbidding simultaneous adjacent replacements.
This PR fixes this by allowing the keys of `nu_out` (i.e. the ports on the output boundary of the subgraph) to be either incoming ports (as before), or outgoing ports (in which case this is equivalent to specifying the map on all incoming ports linked to the given outgoing ports). The latter is less general but covers most use cases and reduces the size of the invalidation set.
Closes https://github.com/CQCL/hugr/issues/2098
BREAKING CHANGE: Generalised arguments to [`SimpleReplacement::new`] and …
=> feat!: Accept outgoing ports in SimpleReplacement nu_out

hugr-llvm/src/utils/inline_constant_functions.rs
=> fix: Fix `inline_constant_functions` pass

hugr-core/src/types.rs
`then_some` is not lazy so 0 indexing panics
=> fix: `as_unary_option` indexing bug

hugr-llvm/src/extension/collections/array.rs
So we can use it when lowering other extensions that need to output arrays
=> feat: Make `hugr_llvm::extension::collections::array::build_array_alloc` public

hugr-core/src/hugr/internal.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/hugr/views/impls.rs, hugr-core/src/hugr/views/rerooted.rs, hugr-llvm/src/emit/ops.rs, hugr-passes/src/force_order.rs
Closes #2158
Annoyingly, we still need to return a `FlatRegion` (or some other concrete wrapper) here so that _references_ to the graph implements some of petgraph's traits (like `IntoNodeIdentifiers`) which are normally implemented for `&'_ G`. There's no way to write that in a GAT constraint :/
We'll have to wait for the big petgraph rewrite to clean that.
BREAKING CHANGE: `HugrInternals::region_portgraph` now also returns a node mapping between hugr and portgraph nodes
=> feat!: Return a node mapping in HugrInternals::region_portgraph

hugr-cli/src/validate.rs, hugr-core/src/builder.rs, hugr-core/src/builder/build_traits.rs, hugr-core/src/builder/cfg.rs, hugr-core/src/builder/conditional.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/builder/module.rs, hugr-core/src/builder/tail_loop.rs, hugr-core/src/extension/resolution.rs, hugr-core/src/hugr.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/impls.rs, hugr-core/src/hugr/views/rerooted.rs, hugr-core/src/ops.rs, hugr-core/src/ops/custom.rs, hugr-core/src/ops/validate.rs, hugr-core/src/package.rs, hugr-core/src/std_extensions/ptr.rs, hugr-passes/src/composable.rs, hugr-passes/src/dead_funcs.rs, hugr-passes/src/monomorphize.rs
Removes the dependency on `base_hugr` when validating views.
Now the validation code runs directly on any given `HugrView`.
To make this work I had to add `<N: HugrNode>` parameters to multiple error types.
This makes sense, as now validating a non-`Node` hugr will return errors with the correct indices.
BREAKING CHANGE: Added node parameters to multiple error types, including the one returned by `HugrView::validate`.
=> feat!: Validate any HugrView, make errors generic

hugr-core/src/hugr.rs, hugr-core/src/hugr/hugrmut.rs
Removes another use of `HugrInternals::portgraph`
=> feat: Reimplement `insert_hugr` using only `HugrView`

hugr-core/src/envelope.rs, hugr-llvm/src/extension/collections/array.rs, hugr-llvm/src/extension/int.rs, hugr-llvm/src/utils.rs, hugr-llvm/src/utils/array_op_builder.rs, hugr-passes/src/dataflow.rs, hugr-passes/src/lib.rs, hugr-passes/src/monomorphize.rs
Closes #2117.
Some remaining deprecations will be removed by the other open PRs. 
BREAKING CHANGE: Removed `EnvelopeError::MultipleHugrs`
BREAKING CHANGE: Removed `add_int_extension` alias in `hugr_llvm::extension`
BREAKING CHANGE: Removed re-export of `ArrayOpBuilder` in `hugr_llvm`
BREAKING CHANGE: Removed unused `ConstLoader::value_from_function` in `hugr_passes`
BREAKING CHANGE: `Monomorphize` pass in `hugr_passes` no longer removes the poly functions.
=> chore!: Remove deprecated definitions

Cargo.lock, hugr-py/Cargo.toml
the others found by cargo-machete were bogus
=> chore: remove unused smolstr dep

hugr-cli/tests/validate.rs, hugr-core/src/package.rs
Closes #2185, by shifting the responsibility to the user.
It also helps greatly reduce payload size, as we don't encode the prelude extension anymore :)
=> feat: Packages do not include the hugr extensions by default

hugr-core/src/hugr/views/sibling_subgraph.rs
Previously, `region_portgraph` was called twice: once to construct the convexity checker (e.g. in `try_from_nodes`), and once to actually construct the subgraph (in `try_new_with_checker`). As a result, if the results from `region_portgraph` were not deterministic, the checker would not be valid and the convexity check might fail. I've had to narrow down the argument type, but there is currently only one type of convexity checker used, so this should not impact anyone.
BREAKING CHANGE: `SiblingSubgraph` only accepts `TopoConvexChecker` as convexity checker type
=> fix!: Use unique region_portgraph in convexity check

.github/workflows/ci-rs.yml, hugr-core/src/envelope.rs, hugr-core/src/envelope/header.rs, hugr-core/src/envelope/package_json.rs, hugr-core/src/extension/resolution/test.rs, hugr-core/src/hugr.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/ops/custom.rs, hugr-core/src/package.rs, justfile
`verify` was calling an internal serialization test helpers to check that roundtrip encoding was correct. With the latest changes, this wasn't checking the actual user-facing envelope encoding.
~This PR currently fails some checks due to #2185~
=> test: check envelope roundtrips rather than json in `HugrView::verify`

hugr-core/src/envelope.rs, hugr-core/src/envelope/header.rs, hugr-model/src/v0/ast/mod.rs
Adds experimental model s-expressions to the supported envelope formats
=> feat: Define text-model envelope formats

hugr-core/src/hugr/ident.rs
This PR fixes a bug that led to a panic in import when the name of an extension exceeded 23 bytes.
This was caused by a misreading of `IdentList::new_unchecked`: this method not only avoids checking the identifier for validity but also assumes that the input will fit into the 23 byte inline capacity of a `SmolStr`.
=> fix: Panic when an extension name is too long.

hugr-core/src/import.rs, hugr-core/src/ops/custom.rs, hugr-py/src/hugr/_serialization/ops.py, hugr-py/src/hugr/ops.py, specification/schema/hugr_schema_live.json, specification/schema/hugr_schema_strict_live.json, specification/schema/testing_hugr_schema_live.json, specification/schema/testing_hugr_schema_strict_live.json
This PR removes the description field on opaque operations. The description can and should be derived when resolving the operation; there is no need for every instance of an operation to carry its own individual copy of an operation's documentation.
BREAKING CHANGE:
- Removed `description` parameter from `OpaqueOp::new`.
=> feat!: Remove description on opaque ops.

hugr-core/src/import.rs, hugr-core/tests/snapshots/model__roundtrip_cfg.snap, hugr-model/tests/fixtures/model-cfg.edn, hugr-model/tests/fixtures/model-entrypoint.edn
This PR changes the way that CFG regions are imported, avoiding the need to insert an empty entry block.
=> feat: Import CFG regions without adding an entry block.

hugr-core/src/hugr/patch.rs, hugr-core/src/hugr/patch/simple_replace.rs, hugr-core/src/hugr/views/sibling_subgraph.rs
`SimpleReplacement` is now so much simpler!!
I've just gone ahead and removed the `nu_inp` and `nu_out` maps of `SimpleReplacement`. Makes defining replacements so much less verbose! But you will probably (rightfully!) be sceptical that this can work.
The crux is: there is already a boundary map defined in the `subgraph: SiblingSubgraph`. My claim is: **We can restrict `nu_inp` and `nu_out` to be bijective maps between the boundary as defined by `SiblingSubgraph` and the ports at the Input/Output nodes of the replacement**. And once the map is bijective, we might as well restrict it to the canonical identity map, mapping the i-th port in the subgraph to the i-th port in the replacement.
To convince yourself of that:
Non-injective case: that’s using a value from the host HUGR multiple …
=> feat!: Remove boundary map in SimpleReplacement

hugr-core/src/import.rs
This PR fixes a bug in import: variables were always imported with the copyable bound, ignoring the type bound on the variable given by non-linear constraints.
=> fix: Respect type bounds on local variables when importing.

hugr-core/src/envelope/serde_with.rs, hugr-core/src/hugr/serialize.rs
The `AsStringEnvelope` wrapper works well enough, but doesn't allow defining which extension sets to use when loading the Package/Hugrs.
Unfortunately, there is no way to define custom extension registers due to the way in which `serde_with` works.
The solution here is to add a public macro that implements the required traits.
This is needed for the ECC sets definition in `tket2`, which encode hugrs containing tket2-extension operations inside a serde struct.
=> feat: Export macro for hugr serde wrappers with custom extensions

hugr-core/src/builder/build_traits.rs, hugr-core/src/builder/dataflow.rs, hugr-core/src/builder/module.rs, hugr-core/src/export.rs, hugr-core/src/extension/resolution/types.rs, hugr-core/src/extension/resolution/types_mut.rs, hugr-core/src/hugr.rs, hugr-core/src/hugr/hugrmut.rs, hugr-core/src/hugr/serialize/test.rs, hugr-core/src/hugr/validate.rs, hugr-core/src/hugr/validate/test.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/render.rs, hugr-core/src/hugr/views/sibling_subgraph.rs, hugr-core/src/import.rs, hugr-core/src/ops/module.rs, hugr-llvm/src/emit.rs, hugr-llvm/src/utils/inline_constant_functions.rs, hugr-passes/src/dead_funcs.rs, hugr-passes/src/monomorphize.rs, hugr-passes/src/replace_types.rs
Accessors ::func_name, ::func_name_mut, ::signature, ::signature_mut.
Constructor ::new takes name + sig using `impl Into`.
BREAKING CHANGE: construction, destruction, and field access should use new methods
=> feat!: Hide FuncDefn/cl fields, add accessors and ::new(...)

hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/tests/snapshots/model__roundtrip_call.snap, hugr-core/tests/snapshots/model__roundtrip_cfg.snap, hugr-core/tests/snapshots/model__roundtrip_const.snap, hugr-core/tests/snapshots/model__roundtrip_entrypoint.snap, hugr-core/tests/snapshots/model__roundtrip_loop.snap, hugr-model/src/v0/table/mod.rs, hugr-model/tests/fixtures/model-cfg.edn, hugr-model/tests/fixtures/model-const.edn, hugr-model/tests/fixtures/model-loop.edn
Symbols in `hugr-model` such as functions or constructors can have parameters whose value can be inferred from context. So far it was already possible to pass wildcard terms to these parameters to indicate that they should be inferred. Noticing that redundant parameters often form a prefix of a symbol's parameter list, this PR adds the ability to apply a symbol with fewer arguments than it has parameters, automatically padding the arguments with wildcards in the front.
=> feat: Symbol applications can leave out prefixes of wildcards.

hugr-py/src/hugr/envelope.py, hugr-py/src/hugr/hugr/base.py, hugr-py/tests/conftest.py, hugr-py/tests/serialization/test_basic.py
Followup to #2148
- Adds envelope reading/writting methods to `Hugr` (py) that mimic Package.
- Deprecates `to_json` and `load_json`.
- Uses envelopes in python tests.
Note that `EnvelopeConfig.BINARY` is still set to JSON.
Using `hugr-module` there currently causes errors.
=> feat(hugr-py): Add `to/from_bytes/str` to Hugr, using envelopes

hugr-py/src/hugr/_serialization/ops.py, hugr-py/src/hugr/std/collections/array.py, hugr-py/src/hugr/std/collections/list.py, hugr-py/src/hugr/std/collections/static_array.py, hugr-py/src/hugr/std/collections/value_array.py, hugr-py/src/hugr/std/float.py, hugr-py/src/hugr/std/int.py, hugr-py/src/hugr/std/prelude.py, hugr-py/src/hugr/val.py, hugr-py/tests/serialization/test_extension.py, specification/schema/hugr_schema_live.json, specification/schema/hugr_schema_strict_live.json, specification/schema/testing_hugr_schema_live.json, specification/schema/testing_hugr_schema_strict_live.json
This was missed in #1906 
It was detected downstream when tket2 generated HUGRs could not be read in.
We need round trip tests that go Python -> serialised -> rust -> deserialized -> Python, might need a special binding in the validation code to do this.
=> fix(py): deprecate extensions sets in values

hugr-core/src/hugr/patch/port_types.rs, hugr-core/src/hugr/patch/simple_replace.rs
I believe these methods finally expose the "right" way to think of the boundary between a replacement and its subgraph, in particular this won't be broken as we extend `SiblingSubgraph` to express more types of subgraphs (see issue #2212).
The idea is simple: for any replacement, there must be links between ports that are just outside the `subgraph` in host, and ports that are linked to the input and output nodes of the `replacement`. These links are precisely the edges that will need to be added when the replacement is applied, between the existing host HUGR and the newly added nodes of the `replacement`. Specifically these edges link:
- outgoing ports in `host` that are "just before the subgraph" (i.e. ports linked to an incoming port of `subgraph`) to incoming ports in `replacement` …
=> feat: Add boundary edge traversal in SimpleReplacement

hugr-py/src/hugr/ops.py, hugr-py/tests/__snapshots__/test_hugr_build.ambr, hugr-py/tests/test_hugr_build.py, hugr-py/tests/test_ops.py
Fixes #1968
drive-by `Call` now inherits from `DataflowOp`
=> fix: handle order port case for missing dataflow ops

hugr-core/src/types.rs, hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__static_array__test__static_array_const_codegen@llvm14_2.snap, hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__static_array__test__static_array_const_codegen@llvm14_3.snap, hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__static_array__test__static_array_const_codegen@pre-mem2reg@llvm14_2.snap, hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__static_array__test__static_array_const_codegen@pre-mem2reg@llvm14_3.snap
`SumType` can represent the same sum of empty tuples in two different ways, but its equality implementation didn't consider them equal.
This PR fixes this by manually implementing `PartialEq`, as well as `Hash` (to preserve correctness).
We already do that on the python side
https://github.com/CQCL/hugr/blob/940895cf3eae57bb6cae6d13f96bf4f065cb4d2b/hugr-py/src/hugr/tys.py#L311-L312
Ideally we'd make the general-sum-of-empty-tuples unrepresentable, but since `SumType` is an enum (with public member), we are not able to avoid arbitrary mutation.
=> fix: Make SumType::Unit(N) equal to SumType::General([(); N])

hugr-core/src/hugr/views/root_checked/dfg.rs
Fixes #2252 .
Still waiting for my local run of the unsoundess checks to complete: they take an age! But these tests appear to be the culprits.
=> test: Ignore miri errors in tests involving `assert_snapshot`

hugr-py/src/hugr/build/dfg.py, hugr-py/src/hugr/hugr/base.py, hugr-py/src/hugr/hugr/node_port.py
`list.index` call to update parent was very costly for nodes with many children. This was only necessary because Node was frozen, this can be avoided with a custom hash.
=> perf(py): mutable `Node` to avoid linear update cost

Cargo.lock, Cargo.toml, hugr-cli/Cargo.toml, hugr-cli/src/main.rs, hugr-cli/tests/external.rs, hugr-cli/tests/validate.rs
This PR adds support for external subcommands in the `hugr-cli`binary, as per the feature request from issue #1343. 
Now when you run:
```bash
hugr <subcommand> [args…]
```
if an executable named `hugr-<subcommand>` is on your `PATH`, it will be called with the same `[args…]`. If the binary is missing or fails, you get a clear error and non-zero exit code.
---
**Functionality:**
* **`src/main.rs`**
1. Checks for no subcommand and errors out.
2. Builds `hugr-<subcommand>` from the first arg.
3. Runs it with `std::process::Command`, passing the remaining args.
4. On error:
* If not found →
```
error: no such subcommand: '<subcommand>'.  
Could not find 'hugr-<subcommand>' in PATH.
```
* Other I/O errors →
```
error: failed to invoke '<executable>': <error>
```
**Testing:**
* …
=> feat: support external subcommands via PATH (#1343)

Cargo.lock, hugr-core/Cargo.toml, hugr-core/src/export.rs, hugr-core/src/import.rs, hugr-core/src/types/type_param.rs, hugr-core/tests/snapshots/model__roundtrip_params.snap, hugr-model/tests/fixtures/model-params.edn, hugr-py/src/hugr/_serialization/tys.py, hugr-py/src/hugr/tys.py, hugr-py/tests/test_hugr_build.py, hugr-py/tests/test_tys.py, specification/hugr.md, specification/schema/hugr_schema_live.json, specification/schema/hugr_schema_strict_live.json, specification/schema/testing_hugr_schema_live.json, specification/schema/testing_hugr_schema_strict_live.json, uv.lock
This PR adds floating point and bytes literals to the core and Python representation of terms to make it closer to terms in `hugr-model`.
BREAKING CHANGE: Added `TypeParam`s and `TypeArg`s corresponding to floats and bytes.
Closes #2292.
=> feat!: Added float and bytes literal to core and python bindings.

hugr-py/tests/conftest.py
The Python testing suite defined an extension named `pytest.quantum,`. The `,` is not allowed as part of an extension name, making the model import fail.
=> fix: Fixed invalid extension name in test.

hugr-py/src/hugr/model/export.py
This PR fixes a bug in the Python model export: `Call` nodes referred to themselves instead of the function to be called.
=> fix: Fixed bug in python model export name mangling.

hugr-core/src/import.rs, hugr-py/src/hugr/model/export.py
This PR fixes two bugs: The first bug exported the type `LoadFunc` nodes incorrectly from Python. The second imported the type of `core.call_indirect` operations incorrectly.
=> fix: Fixed two bugs in import/export of function operations

Cargo.lock, hugr-cli/Cargo.toml, hugr-cli/src/extensions.rs, hugr-cli/src/hugr_io.rs, hugr-cli/src/lib.rs, hugr-cli/src/main.rs, hugr-cli/src/mermaid.rs, hugr-cli/src/validate.rs, hugr-core/src/envelope.rs, hugr-core/src/package.rs
This PR streamlines the error reporting in `hugr-cli`, displaying error source trails and setting up the tracing crate. For that, some error trait implementations were migrated to `thiserror`. The PR also simplifies the `clap` structures by pulling out the verbosity level from the individual commands. The commands should use tracing macros instead of relying on filtering for verbosity themselves.
BREAKING CHANGE: Reorganised `clap` commands and errors in `hugr-cli` which is only visible when it is used as a library.
=> feat!: Better error reporting in `hugr-cli`.

hugr-core/src/envelope/header.rs, hugr/benches/benchmarks/hugr.rs
non exhaustive structs require constructors to be usable outside the crate
=> feat(core): builder pattern for EnvelopeConfig

hugr-persistent/src/lib.rs, hugr/src/lib.rs
As discussed, I am hiding all docs related to `hugr-persistent`, so that future breaking changes won't trip up the changelog generation.
=> docs: Hide hugr-persistent docs

hugr-core/src/hugr/patch.rs, hugr-core/src/hugr/patch/consts.rs, hugr-core/src/hugr/patch/inline_call.rs, hugr-core/src/hugr/patch/inline_dfg.rs, hugr-core/src/hugr/patch/insert_cut.rs, hugr-core/src/hugr/patch/insert_identity.rs, hugr-core/src/hugr/patch/outline_cfg.rs, hugr-core/src/hugr/patch/replace.rs, hugr-core/src/hugr/patch/simple_replace.rs, hugr-persistent/src/persistent_hugr.rs
Currently a Patch(Verification) has to report its `invalidation_set` without being able to see the Hugr on which it will act (and without being able to verify itself against that Hugr - well the set is meaningless if it doesn't verify/apply, but nonetheless). This would be really useful in #2290 for one...
So, this PR adds a new method `invalidated_nodes` which is like `invalidation_set` but takes an `&impl HugrView`; and deprecates the old `invalidation_set`.
Annoyingly deprecating a method in a trait doesn't flag up *implementations* of the method, only calls to it. So the breaking change follow-up to remove invalidation_set (and *require* an implementation of invalidated_nodes) will be significantly breaking. (If we didn't have the default now, this would be breaking and the follow-up …
=> feat: Deprecate invalidation_set, add invalidated_nodes and SimpleReplacement::invalidation_set

hugr-core/src/builder/dataflow.rs, hugr-core/src/builder/module.rs
So we can use the builder machinery to make new definitions on an existing hugr.
=> feat: Create Module/FunctionBuilders from existing Hugrs

hugr-cli/src/main.rs, hugr-core/src/hugr/views.rs, hugr-persistent/src/state_space.rs, hugr-persistent/src/tests.rs, hugr-persistent/src/trait_impls.rs, hugr-persistent/src/walker.rs
Fixes the new lints in rust/clippy 1.88
Inlines variables in `format!` strings to follow the [new lint](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args).
Most of these were already fixed on the edition update PR #2195.
=> chore: Fix new rust lints

hugr-core/src/builder/dataflow.rs
Missed this when updating the builder; the methods `FunctionBuilder::add_input` and `::add_output` are restricted to `FunctionBuilder<Hugr>` but they could as well be used for any `AsMut<Hugr>`.
=> feat: Call `FunctionBuilder::add_{in,out}put` for any AsMut<Hugr>

hugr-core/src/hugr/views/root_checked/dfg.rs
Previously, methods such as `get_io` and `map_function_type` were only defined on root checked Hugrs with root tag `DfgId`. I've turned this into a macro and implemented the types for `DataflowParentId` as well.
=> feat: Add Root checked methods to DataflowParentID

.github/workflows/ci-rs.yml, hugr-core/src/envelope/package_json.rs, hugr-core/src/hugr/serialize/test.rs, justfile
=> test: Check hugr json serializations against the schema (again)

hugr-passes/src/call_graph.rs, hugr-passes/src/composable.rs, hugr-passes/src/const_fold.rs, hugr-passes/src/dataflow.rs, hugr-passes/src/dead_funcs.rs, hugr-passes/src/lib.rs, hugr-passes/src/lower.rs, hugr-passes/src/non_local.rs, hugr-passes/src/replace_types.rs
`missing_docs` is still allowed in `hugr-llvm`
https://github.com/CQCL/hugr/blob/7902ebcf47c427dc2fc9ed74f81b78254c0724b5/hugr-llvm/src/lib.rs#L64
=> chore: require docstrings in hugr-passes

hugr-persistent/src/lib.rs, hugr-persistent/src/state_space.rs, hugr-persistent/src/subgraph.rs, hugr-persistent/src/walker.rs, hugr-persistent/tests/persistent_walker_example.rs
I've factored out the logic that computes the subgraph of a `PersistentHugr` when constructing a `SimpleReplacement` into a new type `PinnedSubgraph`. This is required so that commit factories in `tket2` are able to compute the matched subgraph and extract the matched subHUGRs.
This is very similar to `SiblingSubgraph`, with the nuance that the same subgraph can be applied to multiple `PersistentHugr`s, as long as they all share the same pinned nodes (in particular when the different `PersistentHugr`s stem from the different expansions of the same `Walker`). Conversions to and from `SiblingSubgraph`s are provided.
=> feat: Add PinnedSubgraph

Cargo.toml, hugr-persistent/CHANGELOG.md, hugr-persistent/Cargo.toml, hugr-persistent/README.md, release-plz.toml
Some last config and metadata updates before we publish the crate (required to publish `hugr 0.21`).
The bot does not have permissions to create new crates, so I'll do it manually.
=> chore: Setup hugr-persistent for release

hugr-passes/src/linearize_array.rs, hugr-passes/src/replace_types.rs, hugr-passes/src/replace_types/linearize.rs
* Add `replace_parametrized_op_with` and `replace_op_with` which allow specifying a ReplacementOptions struct
* For now, ReplacementOptions has only one option, to allow running the linearizer on all outports of the replacement
* Test demonstrates - of course the replacement Hugr is invalid (unconnected port) before linearization.
=> feat: ReplaceTypes allows linearizing inside Op replacements

hugr-py/src/hugr/std/collections/static_array.py, hugr-py/tests/conftest.py
The eager encoding of `StaticArrayVal`'s payload caused the nested values to be encoded as _escaped_ strings, causing errors on the rust decoder.
This PR rollbacks the changes to `StaticArrayVal` done in #2436 and adds a better workaround in the roundtrip test instead.
=> fix: StaticArrayVal payload encoding, improve roundtrip checker

hugr-core/src/envelope.rs, hugr-core/src/envelope/header.rs, hugr-py/src/hugr/envelope.py
When reading an envelope header flags, we ignored any unrecognised bits.
This change adds a new error to both the python and rust decoders, that ensures we detect and report this unexpected flags (nudging the user to update their HUGR version).
This will let us add new config flags in the future that change the payload format, having older versions gracefully fail to read them.
=> feat: Detect and fail on unrecognised envelope flags

.config/nextest.toml, .github/workflows/unsoundness.yml, hugr-core/src/envelope/serde_with.rs
Fixes #2457
Ci run: https://github.com/CQCL/hugr/actions/runs/16420064018/job/46395888590
drive-by: Use `nextest` for miri runs. This way we can use multiple threads for testing, and we also report each test duration in the log (so we know if any is particularly long and should be skipped).
See https://nexte.st/docs/integrations/miri/#benefits
drive-by: Skip tests that take over 5mins to run (See linked CI run, most test take 10-20s).
In general any test defining new extensions seems to be really slow. Things dealing with `Term::is_supertype` also seem slow.
I don't know if that's because of miri, or because of Hugr...
With the improved parallelism and skipped tests the unsoundness test now takes <1h rather than 5h :)
=> ci: Disable zstd for miri tests

hugr-passes/src/inline_dfgs.rs, hugr-passes/src/lib.rs
=> feat: Add pass for DFG inlining

hugr-core/src/builder/build_traits.rs, hugr-core/src/hugr/hugrmut.rs, hugr-core/src/hugr/views/impls.rs, hugr-core/src/hugr/views/rerooted.rs
Required for #2462, as we will no longer be able to insert a conditional using `insert_hugr`.
BREAKING CHANGE: Added new `insert_region` method to `HugrMut`
=> feat!: Add `insert_region` to HugrMut

hugr-py/src/hugr/_serialization/ops.py, hugr-py/src/hugr/val.py, specification/schema/hugr_schema_live.json, specification/schema/hugr_schema_strict_live.json, specification/schema/testing_hugr_schema_live.json, specification/schema/testing_hugr_schema_strict_live.json
The python lib had a `_serialization.ops.TupleValue` struct for special cases of single-variant sums, that got encoded with an special tag.
The rust does not have the specialized varinat, and simply loads it as `SumValue`.
This PR removes the unnecessary special case from the python side, to simplify the serialization logic and help with the roundtrip checks.
The json schemas have been updated, but the change is non-breaking.
=> feat(py): Use SumValue serialization for tuples

hugr-core/src/export.rs, hugr-core/tests/snapshots/model__roundtrip_entrypoint.snap, hugr-py/src/hugr/model/export.py
This PR allows to mark any node as an entrypoint in `hugr-model`.
=> feat: Non-region entrypoints in `hugr-model`.

hugr-py/tests/conftest.py
~Blocked by https://github.com/CQCL/hugr/issues/2454~
~Blocked by https://github.com/CQCL/hugr/issues/2464~
~Blocked by #2466~
=> test: Enable model-exts for python roundtrip tests

Cargo.lock, Cargo.toml, hugr-core/src/hugr/serialize.rs, hugr-core/src/hugr/serialize/test.rs, hugr-persistent/src/state_space.rs
We reverted the serialisation changes in portgraph and yanked the `15.0` release. We can thus revert the serialisation patches of https://github.com/CQCL/hugr/pull/2455.
~There are some breaking tests that I do not yet understand. Will look into these next.~
EDIT: all tests have been fixed.
=> chore(deps-rs): Bump portgraph to 0.15.1

.github/workflows/release-plz.yml
See https://crates.io/docs/trusted-publishing.
I enabled it for the hugr crates.
=> ci: Enable crates.io trusted publishing

.github/workflows/release-plz.yml
Missed this requirement -.-
Error: https://github.com/CQCL/hugr/actions/runs/16500206533/job/46656393076#step:5:13
```
Error: Please ensure the 'id-token' permission is set to 'write' in your workflow. For more information, see: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
```
=> ci: Add openID permissions to release-plz publishing

hugr-passes/src/linearize_array.rs, hugr-passes/src/replace_types/linearize.rs
…thus no need to add in linearize_array / LinearizeArrayPass
=> feat: Include copy_discard_array in DelegatingLinearizer::default

hugr-py/src/hugr/build/function.py, hugr-py/tests/test_hugr_build.py
The Python builder for function declarations did not create a static output port when the function declaration is not used. This caused the json to json roundtrip test to fail, since the json deserialisation does add the static output port.
=> fix(py): Python builder for function declarations did not create static output port

hugr-core/src/export.rs, hugr-core/src/extension/resolution/types.rs, hugr-core/src/extension/resolution/types_mut.rs, hugr-core/src/import.rs, hugr-core/src/types.rs, hugr-core/src/types/serialize.rs, hugr-core/src/types/type_param.rs, hugr-core/tests/snapshots/model__roundtrip_const.snap, hugr-model/tests/fixtures/model-const.edn, hugr-py/src/hugr/_serialization/tys.py, hugr-py/src/hugr/tys.py, hugr-py/tests/test_hugr_build.py, hugr-py/tests/test_tys.py, specification/schema/hugr_schema_live.json, specification/schema/hugr_schema_strict_live.json, specification/schema/testing_hugr_schema_live.json, specification/schema/testing_hugr_schema_strict_live.json
This PR adds a `Term::Const` variant, representing the type of constants for a given runtime type. This corresponds to the `core.const` type in `hugr-model`.
Closes #2304.
=> feat: Type of constants in `core` `Term`s.

hugr-py/src/hugr/hugr/base.py, hugr-py/src/hugr/hugr/render.py, hugr-py/tests/__snapshots__/test_hugr_build.ambr, hugr-py/tests/test_hugr_build.py
For moderately sized hugrs, rendering the whole hugr produces sprawling images that are difficult to analyse. This feature allows one to select a region to render.
Example output:
[h_10.pdf](https://github.com/user-attachments/files/21509633/h_10.pdf)
=> feat: Add option to render a subgraph of a hugr.

Cargo.toml, hugr-core/src/envelope.rs, hugr-core/src/extension/resolution.rs, hugr-core/src/types.rs, hugr-core/src/types/signature.rs, hugr-llvm/src/custom.rs, hugr-llvm/src/custom/extension_op.rs, hugr-llvm/src/custom/load_constant.rs, hugr-llvm/src/utils/fat.rs, hugr-passes/src/dataflow.rs, hugr-passes/src/dataflow/partial_value.rs, hugr-passes/src/replace_types.rs, hugr-passes/src/replace_types/linearize.rs
See [`clippy::too_long_first_doc_paragraph`](https://rust-lang.github.io/rust-clippy/master/index.html#too_long_first_doc_paragraph).
>  <img width="730" height="614" alt="image" src="https://github.com/user-attachments/assets/ed6daacd-db92-4465-97b4-3de4fb569b77" />
=> chore: Enable `too_long_first_doc_paragraph` lint

specification/hugr.md
=> docs: Bring specification of `SimpleReplace` up to date.

hugr-core/src/builder/dataflow.rs
We had some functions for creating DFG builders from existing hugrs and changing their handle types, but they were all private. This PR makes them public so they can be used elsewhere (e.g. in tket).
=> feat: Allow creating DFG builders from existing hugrs

release-plz.toml
It'd be nice to have a list of _first contributors_, but that's not currently supported.
See [release-plz/release-plz#1907](https://www.github.com/release-plz/release-plz/issues/1907)
See config: https://release-plz.dev/docs/config#the-git_release_body-field
=> ci: Add contributors list to rust releases

hugr-core/src/envelope.rs
Closes #2579
drive-by: make error fields public for downstream handling
=> fix(core): check extension versions on model import

hugr-core/src/envelope.rs, hugr-core/src/envelope/package_json.rs
Extension resolution computes the actually used extensions in the HUGR and places them inside the HUGR, this can be used to check for version mismatch rather than the registry used for loading
Reverts unnecessary registry returns from https://github.com/CQCL/hugr/commit/91bff6e7a93915696fc67e77870d32b8c877f61d
=> fix(core): check used extension versions against resolved extensions

hugr-core/src/envelope.rs, hugr-core/src/envelope/serde_with.rs, hugr-core/src/extension/resolution.rs, hugr-core/src/hugr/patch.rs, hugr-core/src/hugr/views.rs, hugr-core/src/hugr/views/render.rs, hugr-core/src/hugr/views/rerooted.rs, hugr-llvm/src/extension/collections/stack_array.rs, hugr-passes/src/dead_code.rs, hugr-passes/src/non_local.rs, hugr-persistent/src/parents_view.rs, hugr-persistent/src/trait_impls.rs
In preparation for the breaking release,
- Removes a couple deprecated methods/aliases. (I didn't modify things that are too breaking, like removing `HugrView::mermaid_string_with_config`.
- Adds `since` fields to `#[deprecated]` annotations missing it.
- Replaces `#[allow(deprecated)]`s with `#[expect(deprecated)]` where possible, so we remember to remove them later.
BREAKING CHANGE: Removed deprecated `From` implementation for `ExtensionCollectionError`
BREAKING CHANGE: Removed deprecated `NonLocalEdgesError` alias
=> chore!: Cleanup deprecated definitions
