src/replacement/simple_replace.rs

#139 wasn't compatible with #114

Fix failing CI

---

src/builder/build_traits.rs
src/builder/tail_loop.rs
src/hugr/hugrmut.rs
src/hugr/validate.rs
src/ops/leaf.rs
src/ops/validate.rs

Drop the Copy operation type

---

src/builder/build_traits.rs
src/builder/dataflow.rs
src/builder/module_builder.rs
src/hugr/hugrmut.rs
src/hugr/validate.rs
src/ops/module.rs

Store function name in Def and Declare nodes

---

src/algorithm/half_node.rs
src/algorithm/nest_cfgs.rs
src/builder/build_traits.rs
src/builder/cfg.rs
src/builder/dataflow.rs
src/hugr.rs
src/hugr/hugrmut.rs
src/hugr/validate.rs
src/ops/validate.rs

Make I/O + Entry/Exit valid only as first/second children

---

src/hugr/validate.rs

s/NotADag/NotABoundedDag/ in `ValidationError`

---

specification/hugr.md

Some minor clarifications and typo fixes in the "Functional description" section.
I'll raise Discussions for a couple of points I'm not sure about.

Spec edits

---

src/hugr/serialize.rs

Don't encode other_port offsets on serialization

---

specification/hugr.md

Add appendix with table of node types

---

Cargo.toml
src/builder/build_traits.rs
src/builder/dataflow.rs
src/hugr.rs
src/hugr/hugrmut.rs
src/hugr/serialize.rs
src/hugr/validate.rs
src/ops.rs
src/ops/controlflow.rs
src/ops/custom.rs
src/ops/leaf.rs
src/ops/validate.rs
src/types/simple.rs
src/types/simple/serialize.rs

* remove port counts
* use hugr interfaces for serialization
* proptest does not produce valid hugrs so remove
* Encode types more simply
* store parent along with op type
* use internal tagging for clarity
Closes #177 
Before:
```json
{
"nodes": [
[
0,
0,
0,
{
"Module": []
}
],
[
0,
0,
1,
{
"Def": {
"name": "main",
"signature": {
"input": [
{
"l": {
"Container": {
"Sum": [
{
"c": {
"Int": 64
}
},
{
"l": "Qubit"
}
]
}
}
}
],
"output": [
{
"l": {
"Container": {
"Sum": [
{
"c": {
"Int": 64
}
},
{
"l": "Qubit"
}
]
}
}
}
],
"const_input": [],
"input_resources": [],
"output_resources": []
}
}
}
],
[
1,
0,
2,
{
"Input": {
"types": [
{
"l": {
"Container": {
"Sum": [
{
"c": {
"Int": 64
}
},
{
"l": "Qubit"
}
]
}
}
}
],
"resources": []
}
}
],
[
1,
2,
0,
{
"Output": {
"types": [
{
"l": { …
```

Even more ergonomic serialization

---

Cargo.toml
src/hugr.rs
src/hugr/hugrmut.rs
src/hugr/rewrite/simple_replace.rs
src/hugr/serialize.rs

Update portgraph dep

---

src/ops/constant.rs
src/types/simple.rs
src/types/simple/serialize.rs

[Refactor] Standardize on HugrIntWidthStore / HugrIntValueStore

---

src/hugr.rs

Thanks Agustin for [the suggestion](https://github.com/CQCL-DEV/hugr/pull/186#discussion_r1241875055), definitely an easier form than the one I found  :-)

Add test that Hugr implements Send and Sync

---

specification/hugr.md

Clarify description of DFG signature.

---

specification/hugr.md

I think these are probably obsolete, but if any are not we should capture them as discussions.

Remove comments.

---

specification/hugr.md

There is no alternative.

---

src/hugr/hugrmut.rs
src/hugr/region.rs
src/hugr/serialize.rs
src/hugr/validate.rs
src/replacement.rs

Some minor cleanup changes.
- Add more #[inline]s in `region.rs`.
- Merge `remove_node` and `remove_op` in HugrMut.
- Remove the unused `replacement.rs` file.

Cleanup some code

---

src/hugr/rewrite/simple_replace.rs

Broken out of #225 as that's getting bigger!!

[trivial] simple_replace.rs: use HugrMut::remove_node, includes clearing op_types

---

src/ops/validate.rs

Various of these exist already as methods on the classes in `controlflow.rs`...

src/ops/validate.rs: Common-up some type row calculations

---

src/types/type_param.rs

This is the simplest way to implement #260.
This option goes with adding a general `Value` containing a `serde_yaml::Value` to mimic the extra data in `OpDef`.
Alternatively, this could be done with an Opaque `Box<dyn ...>` and dynamic downcasting.
Or we could have both.
Currently we only use the TypeArgs to compute the signature of external operations once (and cache them afterwards), so there is not much of a difference between both options.

Add a generic `Value` type parameter

---

.github/workflows/ci.yml

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

add merge group event trigger

---

src/hugr/typecheck.rs
src/ops/constant.rs
src/types/custom.rs
src/types/simple.rs
src/types/simple/serialize.rs

move `Opaque` to `Container`

---

src/extensions/rotation.rs
src/ops/custom.rs
src/resource.rs

add resource and description fields for TypeDef

---

src/extensions/rotation.rs
src/resource.rs
src/types/simple.rs
src/types/type_param.rs

Enable TypeDef reporting of type tag.

---

src/ops/constant/typecheck.rs

Improve coverage with some low hanging fruit.
Is this overkill? I'm not sure

[test] Add unit tests for const typechecking

---

devenv.nix

as of now this should be 1.71
hope is to avoid encountering this (or a related) bug:
https://github.com/rust-lang/rust/issues/114110

switch to rust stable channel

---

specification/hugr.md

My granpaw used to say: "If it's worth saying once, it's worth saying again"

[doc] Expand '"' in hierarchy table

---

specification/hugr.md
src/types/simple.rs
src/types/simple/serialize.rs
src/values.rs

In spec and implementation
Closes #361

Remove List and Map types from core

---

src/ops/module.rs
src/types/basic.rs

check compatibility on construction

Tag wrapper for self-reporting leaves

---

src/types/type_enum/serialize.rs

internal tagging with a sequence doesn't work

use field name for sequence variants

---

src/resource.rs
src/types.rs
src/types/leaf.rs
src/types/type_enum.rs
src/types/type_enum/serialize.rs

also move some non-core types to a prelude resourece
rename TypeTag -> TypeBound

Move from static type bounds to dynamic

---

src/extensions/arithmetic/conversions.rs
src/extensions/arithmetic/float_ops.rs
src/extensions/arithmetic/float_types.rs
src/extensions/arithmetic/int_types.rs

Implement arithmetic const nodes.

---

src/std_extensions/quantum.rs

I need these gates to benchmark against Quartz.

feat: add T, Tdg, X gates

---

src/std_extensions/quantum.rs

Refs: d81f724dbf0f82f6819429d3842fe2a1c934ab61.

revert: add T, Tdg, X gates (#466)

---

src/lib.rs

https://rust-lang.github.io/rust-clippy/master/index.html#/debug_assert_with_mut_call

feat: Add clippy lint for mut calls in a debug_assert

---

src/hugr/views/petgraph.rs

I couldn't work out how to do the lifetimes in IntoNodeReferences so had to pull that out.
But, well, I think the objections here are pretty obvious...
The line count is pretty good though!!

RFC: Into #498: properly parametrize macro

---

src/hugr/views/sibling_subgraph.rs

Removes HUGR borrows in `SiblingSubgraph`. This is necessary to be able to use it to specify subgraphs for rewriting (as the rewriter will need exclusive `mut` access to the Hugr).
I've taken the opportunity to clean up the interface by removing close-to duplicate methods and making the naming more consistent.

feat!: SiblingSubgraph does not borrow Hugr

---

specification/hugr.md

Update terminology for types in spec.

---

src/hugr/rewrite/outline_cfg.rs

Forgot to notice this in #534 before it was merged!

cleanup: Remove outdated comment

---

src/extension/infer.rs

fix(Inference): Account for self-referencial constraints

---

devenv.nix
justfile

justfile is minimal for now but can be added to

chore: add justfile and devenv dependency

---

src/ops/validate.rs

Makes the error easier to use and harder to get wrong

[refactor][tiny]Remove redundant field of InvalidConditionalPredicate

---

.github/workflows/issue.yml

The code seems to work! ...In the case where there is a priority label on the issue. Jira complains if the priority field is just "", so we need to get rid of it

fix(Jira): Handling of issues with no priority label

---

.github/workflows/issue.yml

chore(Jira): Try to fix Jira creation for issues with no priority

---

.github/workflows/notify-coverage.yml

This avoids having differing percentages in the notification vs on the webapp.

ci: Use codecov's results for the coverage notification

---

src/lib.rs

docs: Improve crate-level docs, including example code.

---

devenv.lock
devenv.nix

chore: devenv update + rust beta channel

---

specification/hugr.md

A couple of small clarifications suggested by Will.

docs: Spec clarifications

---

.github/workflows/release-plz.yml
README.md
cliff.toml
release-plz.toml

- Setups automatic changelog generation on merges to `main`
- Updates the README with the appropriate links (assuming the crate is already released)

ci: Setup release-plz and related files

---

src/hugr/rewrite/consts.rs

leftover review comment:
https://github.com/CQCL/hugr/pull/757#discussion_r1439399609

refactor: simplify removeconstignore verify

---

src/extension/prelude.rs

feat: add panic op to prelude

---

Cargo.toml
devenv.nix
specification/schema/hugr_schema_v0.json
src/hugr/serialize.rs

requires minor fixes to schema
use json rather than rmp for tests for debuggability

test: add schema validation to roundtrips

---

specification/hugr.md

Also, drive-by formatting of the edge table

docs(spec): Clarify note on edges

---

.github/workflows/python-wheels.yml

This should be the last one...

ci: Fix pypi token config

---

hugr/src/extension/prelude.rs
hugr/src/std_extensions/arithmetic/float_ops.rs
hugr/src/std_extensions/arithmetic/float_ops/const_fold.rs
hugr/src/std_extensions/arithmetic/int_ops.rs
specification/hugr.md

feat: Add `string` type and `print` function to `prelude`

---

devenv.nix

chore: run `just setup` at devenv shell init

---

specification/hugr.md

docs: Update specification of prelude panic op.

---

.github/workflows/unsoundness.yml

ci: Fix miri proptest error

---

release-please-config.json

To avoid spamming the reviewers
Closes #1077

ci: Create release-please's PRs as draft

---

.github/change-filters.yml
hugr-py/tests/conftest.py

And include rust code filter in criteria for running python tests on CI.

test: Add "validate" to hugr CLI command.

---

hugr-core/src/hugr/serialize/upgrade.rs

Matches existing serialization test.
Manual run: https://github.com/CQCL/hugr/actions/runs/10091633882

test: miri gate serialization upgrades

---

.gitignore

This is just a test PR to check if #1384 worked.

chore: Cleanup gitignore

---

hugr-py/src/hugr/__init__.py
hugr-py/src/hugr/serialization/extension.py
hugr-py/src/hugr/serialization/serial_hugr.py
hugr-py/tests/serialization/test_basic.py
hugr-py/tests/serialization/test_extension.py
poetry.lock
scripts/generate_schema.py
specification/schema/hugr_schema_live.json
specification/schema/hugr_schema_strict_live.json
specification/schema/testing_hugr_schema_live.json
specification/schema/testing_hugr_schema_strict_live.json

feat: `Package` pydantic model for modules + extensions

---

hugr-cli/Cargo.toml
hugr-cli/src/main.rs
hugr-cli/src/validate.rs
hugr-cli/tests/validate.rs

feat(hugr-cli): validate with extra extensions and packages

---

hugr-py/src/hugr/tys.py

feat(hugr-py): add type_bound method to `Type`

---

.pre-commit-config.yaml
hugr-py/src/hugr/hugr.py
hugr-py/tests/conftest.py
hugr-py/tests/test_hugr_build.py

drive-by: For some reason mypy started complaining about some unrelated imports, this includes a fix  -.-'

feat(py): `Hugr.to_json` and `.load_json` helpers

---

.github/workflows/ci-rs.yml

As proposed in https://github.com/CQCL/hugr/pull/1518

ci: Make the std extensions job a required check

---

hugr-core/Cargo.toml

release workflow failed because of this

chore: specifcy hugr-model version

---

.github/workflows/unsoundness.yml

ci: Run unsoundness checks on a set schedule

---

hugr-llvm/src/emit/test.rs
hugr-llvm/src/utils/array_op_builder.rs

fix: hugr-llvm extension deltas

---

hugr-llvm/src/utils/array_op_builder.rs

fix: unused import from #1683

---

hugr-core/src/extension/prelude/generic.rs
hugr-llvm/src/extension/prelude.rs
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__prelude__test__prelude_load_nat@llvm14.snap
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__prelude__test__prelude_load_nat@pre-mem2reg@llvm14.snap

feat: Lower LoadNat to LLVM

---

devenv.lock
devenv.yaml
hugr-core/src/builder/build_traits.rs
hugr-core/src/hugr/ident.rs
uv.lock

includes devenv update to get 1.85

chore: clippy fix 1.85

---

Cargo.toml
hugr-core/Cargo.toml
hugr-core/src/extension/prelude.rs
hugr-core/src/extension/simple_op.rs
hugr-core/src/std_extensions/arithmetic/conversions.rs
hugr-core/src/std_extensions/arithmetic/float_ops.rs
hugr-core/src/std_extensions/arithmetic/int_ops.rs
hugr-core/src/std_extensions/collections/array/array_op.rs
hugr-core/src/std_extensions/collections/list.rs
hugr-core/src/std_extensions/logic.rs
hugr-core/src/std_extensions/ptr.rs

macros are available from derive feature

chore: simplify strum dependency

---

hugr-py/src/hugr/build/dfg.py
hugr-py/src/hugr/hugr/base.py
hugr-py/tests/test_hugr_build.py

Closes #1969 
Closes #1970
drive-by add `add_order_link` to `Hugr`

fix(hugr-py): output and delete node issues

---

hugr-llvm/src/extension/int.rs
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__int__test__emission@llvm14_ineg_[2].snap
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__int__test__emission@llvm14_is_to_u_[3].snap
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__int__test__emission@llvm14_iu_to_s_[3].snap
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__int__test__emission@pre-mem2reg@llvm14_ineg_[2].snap
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__int__test__emission@pre-mem2reg@llvm14_is_to_u_[3].snap
hugr-llvm/src/extension/snapshots/hugr_llvm__extension__int__test__emission@pre-mem2reg@llvm14_iu_to_s_[3].snap
hugr-llvm/src/snapshots/hugr_llvm__sum__test__build_untag_tag@llvm14.snap
hugr-llvm/src/test.rs

feat(hugr-llvm): Emit iu_to_s and is_to_u

---

devenv.lock
devenv.nix
devenv.yaml

mainly for better uv/venv interaction

chore: minor devenv cleanups

---

hugr-py/pyproject.toml
hugr-py/src/hugr/qsys_result.py
hugr-py/src/hugr/qsystem/__init__.py
hugr-py/src/hugr/qsystem/result.py
hugr-py/tests/test_qsys_result.py
pyproject.toml
uv.lock

Guppy PR: https://github.com/CQCL/guppylang/pull/918

feat(hugr-py): move in result classes from guppylang

---

hugr-passes/src/lib.rs
hugr-passes/src/monomorphize.rs

for use in tket2/other downstream compilation tools

feat: export mangle name function

---

hugr-core/src/hugr/views.rs
hugr-core/src/hugr/views/impls.rs
hugr-core/src/hugr/views/render.rs
hugr-core/src/hugr/views/rerooted.rs

refactor: do not use .portgraph in mermaid/graphviz

---

hugr-passes/src/composable.rs
hugr-passes/src/const_fold.rs
hugr-passes/src/dead_code.rs
hugr-passes/src/dead_funcs.rs
hugr-passes/src/linearize_array.rs
hugr-passes/src/monomorphize.rs
hugr-passes/src/replace_types.rs
hugr-passes/src/untuple.rs

Closes #2178 
BREAKING CHANGE: Added a `HugrMut` type parameter to `ComposablePass`

feat!: Explicit hugr type param to ComposablePass

---

hugr-llvm/src/extension/collections.rs
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_all_ops@llvm14.snap
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_all_ops@pre-mem2reg@llvm14.snap
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_array_value@llvm14.snap
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_array_value@pre-mem2reg@llvm14.snap
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_clone@llvm14.snap
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_clone@pre-mem2reg@llvm14.snap
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_get@llvm14.snap
hugr-llvm/src/extension/collections/snapshots/hugr_llvm__extension__collections__stack_array__test__emit_get@pre-mem2reg@llvm14.snap
hugr-llvm/src/extension/collections/stack_array.rs

feat: Restore old array lowering

---

.github/workflows/ci-rs.yml

ci: Pin CI to non-segfaulting rust nightly

---

hugr/benches/benchmarks/hugr.rs
hugr/benches/benchmarks/subgraph.rs
hugr/benches/benchmarks/types.rs

chore: use std `black_box` in benchmarks

---

hugr-py/src/hugr/_serialization/extension.py
hugr-py/src/hugr/ext.py
hugr-py/tests/serialization/test_extension.py
hugr-py/tests/test_package.py
specification/schema/hugr_schema_live.json
specification/schema/hugr_schema_strict_live.json
specification/schema/testing_hugr_schema_live.json
specification/schema/testing_hugr_schema_strict_live.json

fix: use envelopes for `FixedHugr` encoding

---

hugr-llvm/src/custom/extension_op.rs
hugr-llvm/src/custom/load_constant.rs
hugr-llvm/src/emit/func.rs
hugr-llvm/src/emit/ops/cfg.rs
hugr-llvm/src/utils/type_map.rs

I don't believe any of these changes are breaking or cause serious performance regressions but worth double checking. Should help with determinism (avoiding future pit-falls even if not resolving any current issues)

refactor(llvm): replace HashMap with BTreeMap

---

hugr-core/src/envelope.rs

We should call `ExtensionRegistry::load_json` instead of raw `serde_json::from_reader`, otherwise it skips the extension resolution steps.
This failed in #2317, when changing the default binary encoding to `ModelWithExtensions`

fix: Do extension resolution on loaded extensions from the model format

---

hugr-persistent/src/tests.rs

I'm not quite sure how this was able to be merged but anyway

chore(hugr-persistent): Fix clippy

---

.github/workflows/ci-rs.yml

This got pinned in #2229, but the issue #2227 has long been fixed.

ci: Unpin rust nightly
